### ISSUE TITLE
missing libs?

### ISSUE THREAD

**Issue by mebigfatguy** [spotbugs/spotbugs#1]
looks like asm and bcel jars didn't come over, or am i missing something?

**Comment by mebigfatguy** [comment]
hmm is see you added dynamic pulling but i get

/home/dave/dev/spotbugs/build.xml:18: The following error occurred while executing this line:
/home/dave/dev/spotbugs/findbugs/build.xml:1295: org.mozilla.javascript.EcmaError: ReferenceError: "Java" is not defined.

**Comment by jsotuyod** [comment]
Those changes were introduced back in FindBugs, however, it seems you can access Java [classes directly](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Scripting_Java), I'm submitting a PR for you to check.

However, we should start discussing build process unification. Right now we have Ant & Maven, where Maven is incomplete.

I'll open a new issue to discuss it.
