### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by jsotuyod** [spotbugs/spotbugs#10]
As per #4, particularly https://github.com/spotbugs/spotbugs/issues/4#issuecomment-258701234 and https://github.com/spotbugs/spotbugs/issues/4#issuecomment-258702861 we need to improve upon current test architecture.

This issue keeps open for discussion as to the approach to testing to move forward.

**Comment by jsotuyod** [comment]
With #12 and #16 we have completed CI integration. Unit testing revamping still pending.

**Comment by jsotuyod** [comment]
Given the current test architecture has proven incapable of actually testing violations on lambdas, which are the corner stone of all tasks we need to perform to have full Java 8 support, I'm raising this task's priority.

As previously stated I like @h3xstream's approach in find-sec-bugs. The hamcrest matcher is easy to use and flexible, and can easily be integrated with the current use of the engine within tests. Some helpers could be added to convert `@ExpectWarning` and other annotations to assertions, meaning we could get rid of the `CheckExpectedWarnings` detector.

I'll try to get a working draft on this for review adding the find-sec-bugs testutils lib directly.

**Comment by h3xstream** [comment]
In case it is needed, you can reuse find-sec-bugs test utility (move the code partially or as-is). It is LGPL anw.

**Comment by jsotuyod** [comment]
@h3xstream thanks! I'll make sure to provide proper acknowledgements
