### ISSUE TITLE
False-positive in URLCONNECTION_SSRF_FD

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs#1011]
With this code:
```java
public class Version {
    private static final URL versionPropertiesResource =
            Version.class.getResource("../version.properties");
    public Version() {
        Properties versionProperties = new Properties();
        try (InputStream versionPropertiesStream = versionPropertiesResource.openStream()) {
            versionProperties.load(versionPropertiesStream);
        } catch (IOException ignored) {
        }
    }
}
```
`URLCONNECTION_SSRF_FD` complains about using `openStream()` on a user-supplied URL which clearly is not the case. (It is in a private static final field to be able to easily replace it for testing)

**Comment by ThrawnCA** [comment]
Are you using `FindSecBugs`? That doesn't sound like a core detector.

**Comment by Vampire** [comment]
Indeed, is there someone who is admin in both and can move the issue to the correct project?

**Comment by KengoTODA** [comment]
better to issue a new one at [their issue tracker](https://github.com/find-sec-bugs/find-sec-bugs/issues).
