### ISSUE TITLE
maven plugin configuration to fail build

### ISSUE THREAD

**Issue by kofemann** [spotbugs/spotbugs#1026]
First of all, thanks to a great tool!

We have a legacy code and would like to fix spotbugs reported issues working on then type-by-type. For example fix all `HE_EQUALS_NO_HASHCODE`.

As soon as it's fixed, I would like to get a configuration, where build will fail if new code change introduces this warning again. The currently available solution is to disable all warnings and include only `HE_EQUALS_NO_HASHCODE`. However, I will prefer to always generate full report but fail on some particular warnings. Eventually, we will endup with handful of warnings that may go into ignore list and cleanup our legacy code.

**Comment by ThrawnCA** [comment]
You can add the SpotBugs plugin to your Maven `reporting` configuration to generate a report.

**Comment by hazendaz** [comment]
old issue closing, not quite sure I understood entire issue here but maven items need opened on the maven plugin as that differs from the core of spotbugs.
