### ISSUE TITLE
spotbugs building issues - missing libraries

### ISSUE THREAD

**Issue by anil-rug** [spotbugs/spotbugs#1037]
Steps:
1. I tried building the project using gradle from the directory "\spotbugs".
2. It build without error.
3. The build directory only has the spotbugs.jar in libs folder. Shouldn't there be more dependent libraries?
<img width="589" alt="error" src="https://user-images.githubusercontent.com/54888589/69193420-efea6480-0b26-11ea-8305-7f9fee2a4ba8.png">

**Comment by ThrawnCA** [comment]
Have you checked your local Maven repository?

**Comment by anil-rug** [comment]
How do I check that? Is there some steps that I can follow?

**Comment by ThrawnCA** [comment]
https://maven.apache.org/guides/introduction/introduction-to-repositories.html

Gradle reuses the Maven repo.

**Comment by anil-rug** [comment]
Thank you...Its working now
