### ISSUE TITLE
Unable to see the source code panel for SpotBugs GUI

### ISSUE THREAD

**Issue by anil-rug** [spotbugs/spotbugs#1040]
When running the SpotBugs GUI with a code, I am able to see the bugs present in the code however the source code panel is always empty. Can you please help in this?

![image](https://user-images.githubusercontent.com/54888589/69557934-af1ba100-0fa7-11ea-8f21-64018fd29c50.png)

**Comment by ThrawnCA** [comment]
Was your code compiled with debugging information?

**Comment by anil-rug** [comment]
Found the issue, I needed to specify the root folder of the code in order to get the source code panel. Thanks, again.
