### ISSUE TITLE
Documentation for Spotbugs - Technical tool analysis

### ISSUE THREAD

**Issue by anil-rug** [spotbugs/spotbugs#1044]
As part of a mini-project, my team is performing software maintenance and evolution top-down check to analyze the SpotBugs software and check the modularity of the code. I see that there is good documentation regarding the working of the application. But as we are performing in-depth testing of the tool, it would be helpful if you would have some software architecture documentation like Architecture diagrams, UML diagrams or technical requirements?

@ThrawnCA

**Comment by ThrawnCA** [comment]
I'm not sure why I was specifically tagged in this...but no, I'm not aware of any architecture diagrams, sorry. If there are any, I'd be looking for them by browsing the repo, which I imagine you've already started doing.

**Comment by Betty42** [comment]
@anil-rug now that I'm working on a similar mini-project, any chance you could share your insights about spotbugs?
