### ISSUE TITLE
False-positive in OPM_OVERLY_PERMISSIVE_METHOD for equals

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs#1055]
`OPM_OVERLY_PERMISSIVE_METHOD` in SpotBugs 3.1.12 just told me I should make `equals` `protected`, which of course would be invalid.
The class is package-private which triggers the bug I think.

**Comment by gtoison** [comment]
Sorry for the belated answer, that bug is reported by https://github.com/mebigfatguy/fb-contrib so the issue should be reported there

**Comment by Vampire** [comment]
Whoops, my bad, sorry and thanks: mebigfatguy/fb-contrib#468
