### ISSUE TITLE
Hide lombok warnings

### ISSUE THREAD

**Issue by rafalschmidt97** [spotbugs/spotbugs#1058]
Hi,
I use lombok im my project and I cannot get ride of warnings with it.

I've found [one solution](https://github.com/spotbugs/spotbugs/issues/464#issuecomment-359021222) for it but it seems like it doesn't work

```
> Task :spotbugsMain
Warning at xsl:variable on line 348 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
Warning at xsl:variable on line 351 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
The following classes needed for analysis were missing:
  lombok.extern.slf4j.Slf4j
  lombok.Data
  lombok.NoArgsConstructor
```

Is it even possible to hide it?

**Comment by kec2** [comment]
I don't think it has anything to do with Lombok. I get the same error.

> Task :spotbugsTest
Warning at xsl:variable on line 348 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
Warning at xsl:variable on line 351 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect

> Task :spotbugsMain
Warning at xsl:variable on line 348 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
Warning at xsl:variable on line 351 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect

**Comment by hazendaz** [comment]
closing as never seen issues with lombok usage.  Would need far more details and other user noted not likely due to lombok which I suspect is true.
