### ISSUE TITLE
Spotbugs needs to specify which sfl4j jar is needed for execution. 

### ISSUE THREAD

**Issue by linusjf** [spotbugs/spotbugs#1089]
https://github.com/Fernal73/LearnJava/blob/master/spotbugs

https://github.com/Fernal73/LearnJava/blob/master/spotbugs.cp

The above is my Spotbugs script and classpath.

Using slf4j-log4j12.jar (downloaded from maven repository) throws an exception while running spotbugs. It can't find systemProperties.properties (apparently).

 Adding nop jar to classpath fixed the warning. Still need help with output XML.
Removing sortByClasses resolves the issue.

spotbugs/spotbugs-gradle-plugin#114 (https://github.com/spotbugs/spotbugs-gradle-plugin/issues/114#issuecomment-555819667) 

http://www.slf4j.org/codes.html

[Refer original post here](https://github.com/spotbugs/spotbugs-maven-plugin/issues/98#issuecomment-555789568)

**Comment by hazendaz** [comment]
closing as issue is with usage of slf4j.  Please read up on how to use.  slf4j-log4j12 pipes to log4j1.2.  That is obsolete and not suggested here.  Using this project should auto resolve all its dependencies as is.  Given 3 years here likely not an issue any more.
