### ISSUE TITLE
PGP public key signing spotbugs-4.0.0 (and later?) not available (on keyservers)

### ISSUE THREAD

**Issue by cobratbq** [spotbugs/spotbugs#1125]
Signature for `com.github.spotbugs:spotbugs:jar:4.0.0` cannot be used to validate the library as the PGP public key `A5DEF5A76F94A471` cannot be found on PGP keyservers.

I've tried downloading from `hkps.pool.sks-keyservers.net` and `keyserver.ubuntu.com`. Both failed to find the public key.

The signature packet as downloaded:
```
# off=0 ctb=89 tag=2 hlen=3 plen=540
:signature packet: algo 1, keyid A5DEF5A76F94A471
	version 4, created 1581852609, md5len 0, sigclass 0x00
	digest algo 10, begin of digest 2a 0c
	hashed subpkt 2 len 4 (sig created 2020-02-16)
	subpkt 16 len 8 (issuer key ID A5DEF5A76F94A471)
	data: [4095 bits]
```

I checked spotbugs.github.io but cannot find any info regarding the signing key.
Is the public key uploaded? (or is it made available in some other way that I missed?)

**Comment by KengoTODA** [comment]
@cobratbq Thanks for your report! I've run following commands, could you verify the result?

```
gpg --keyserver hkp://pool.sks-keyservers.net --send-keys A5DEF5A76F94A471
gpg --keyserver hkp://keyserver.ubuntu.com --send-keys A5DEF5A76F94A471
```

**Comment by cobratbq** [comment]
I have successfully downloaded the public key. Thanks!
