### ISSUE TITLE
How can i run findsecbugs rules in spotbugs?

### ISSUE THREAD

**Issue by xsser** [spotbugs/spotbugs#1164]
How can i run findsecbugs rules in spotbugs?

Am i right?

./spotbugs -textui  -pluginList /Users/xxx/Downloads/findsecbugs-plugin-1.11.0-SNAPSHOT.jar   -home .  -low  -output ./aaa -progress -train ./bbb -sourcepath ~/Downloads/codez/test/My-Blog/ -debug -noClassOk -progress -auxclasspath ~/Downloads/codez/test/My-Blog/target/   -choosePlugins edu.umd.cs.findbugs.plugins.core

**Comment by xsser** [comment]
Can you add examples in the docs?

**Comment by hazendaz** [comment]
Best bet would be to go to findsecbugs and read their documentation as to how it works.  There entire purpose for existing is to feed off spotbugs logic so they would have it documented clearly.  I'm not sure its our point to support documentation of other products as we may not even know all of them.
