### ISSUE TITLE
FII_USE_METHOD_REFERENCE 

### ISSUE THREAD

**Issue by sameeragrawal80** [spotbugs/spotbugs#1168]
Error:
[ERROR] Method SSSService.downloadFile(URI) creates an anonymous lamda expression instead of specifying a method reference [SSSService] At SftService.java:[line 117] FII_USE_METHOD_REFERENCE
-----------------

private final WebClient webClient;
------
  private Optional<InputStream> downloadFile(URI uri) {
    return Optional.ofNullable(
        webClient
            .get()
            .uri(uri)
            .retrieve()
            .bodyToMono(InputStreamResource.class)
            .map(
                inputStreamResource -> {
                  try {
                    return inputStreamResource.getInputStream();
                  } catch (IOException e) {
                    throw new IllegalStateException(e);
                  }
                })
            .block());
  }

**Comment by KengoTODA** [comment]
`FII_USE_METHOD_REFERENCE` is not feature in spotbugs, it comes from https://github.com/mebigfatguy/fb-contrib
So please report your issue to that repository.
