### ISSUE TITLE
confidence level

### ISSUE THREAD

**Issue by JamiKX** [spotbugs/spotbugs#1208]
hi,
Because i get the output`<BugInstance type="EI_EXPOSE_REP2" priority="Normal" message="****">` the bug priority is 'Normal', So how i get to know these bugs's priority ahead? which are normal , which are low and which are high?
I didn't find their level descriptions on the official website [spotbugs bug descriptions](https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html), anyone can help me?  Thanks!

**Comment by KengoTODA** [comment]
The confidence level is decided dynamically by code, so we have to read the code to understand how it's decided by detectors. 

In case of `EI_EXPOSE_REP2 `, you can refer [this code](https://github.com/spotbugs/spotbugs/blob/07bf864b83083c467e29f1b2de58a2cf5aa5c0d6/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindReturnRef.java#L129). To identify which detector you need to read, search [`findbugs.xml`](https://github.com/spotbugs/spotbugs/blob/07bf864b83083c467e29f1b2de58a2cf5aa5c0d6/spotbugs/etc/findbugs.xml#L435-L436) by the rule ID like `EI_EXPOSE_REP2`.
