### ISSUE TITLE
Fails with OpenJDK 15-ea: Unsupported class file major version 60

### ISSUE THREAD

**Issue by guw** [spotbugs/spotbugs#1229]
It looks like the Maven plug-in needs an update for JDK 15. I get the following error when switching the JDK:

```
     [java] The following errors occurred during analysis:
     [java]   Error scanning java/lang/Object for referenced classes
     [java]     java.lang.IllegalArgumentException: Unsupported class file major version 60
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
```

**Comment by wreulicke** [comment]
According to [changelogs for ASM](https://asm.ow2.io/versions.html), ASM version 9.0-beta supports JDK 15.
So, spotbugs does not support JDK 15 now.

**Comment by KengoTODA** [comment]
We're waiting the official release of ASM 9.0.
refs #1229 #1230

**Comment by mbarbero** [comment]
It seems that ASM 9.0 has been release on Sept 22 (https://asm.ow2.io/versions.html). Is there anything I can do to help with moving forward wit this issue?

**Comment by iloveeclipse** [comment]
@mbarbero: Push a PR similar to #1230

**Comment by mbarbero** [comment]
uhm, 9.0 is already being used https://github.com/spotbugs/spotbugs/blob/master/spotbugs/build.gradle#L14 and I confirm that version 4.1.4 does not throw @guw's error (even though I see some suspicious false positive in the check result).

I guess this one can be closed then.

**Comment by iloveeclipse** [comment]
Ha, I've missed update too :-)
