### ISSUE TITLE
Errors in findbugs-maven-plugin

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#123]
@jsotuyod can I ask you to handle this? Maybe this is caused by 7fb6ff52bb20363a2684be64e845753f909e1b54.
I tested with `findbugs-maven-plugin:3.0.4`. You can run `mvn findbugs:findbugs` and `mvn site` in https://github.com/KengoTODA/findbugs-slf4j/tree/spot-bugs-3.1 to test.

----

Current `master` cannot work with `findbugs-maven-plugin`. `findbugs:findbugs` works but at `site` goal, it reports following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project test-case: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.4:site failed: No such property: RELEASE for class: edu.umd.cs.findbugs.Version
```

It seems that we've accidentally removed a public field in `Version` class. Refs: https://github.com/findbugsproject/findbugs/blob/94ec4ad/findbugs/src/java/edu/umd/cs/findbugs/Version.java#L133

----

And generated `findbugsXml.xml` has `version="(unknown)"`, this is caused by NPE:

```
     [java] java.lang.NullPointerException
     [java] 	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:441)
     [java] 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:375)
     [java] 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:409)
     [java] 	at java.util.jar.Attributes.read(Attributes.java:376)
     [java] 	at java.util.jar.Manifest.read(Manifest.java:199)
     [java] 	at java.util.jar.Manifest.<init>(Manifest.java:69)
     [java] 	at edu.umd.cs.findbugs.Version.<clinit>(Version.java:49)
```

It seems that `Version.class.getResourceAsStream("META-INF/MANIFEST.MF")` in Version.java returns `null`. I confirmed that `MANIFEST.MF` is packaged to `spotbugs.jar`.

I tried to change `"META-INF/MANIFEST.MF"` to `"/META-INF/MANIFEST.MF"`, but it cannot be solution because it doesn't load file from `spotbugs.jar`. Here is entries in loaded manifest:

```
     [java] Ant-Version: Apache Ant 1.8.4
     [java] Created-By: 1.6.0_65-b14-466-11M4802 (Apple Inc.)
     [java] Manifest-Version: 1.0
```

I guess it loaded data from Maven plugin itself.

**Comment by jsotuyod** [comment]
@KengoTODA That was removed when we cleaned up Version code due to it being unused.

What I guess we could do is reintroduce it, have it share the value with `VERSION_STRING`, and have it marked as `@Deprecated` to be removed in 4.0.0, leaving time for people to move the `Version.VERSION_STRING`.

I'll submit a PR, let me know what you think.
