### ISSUE TITLE
Build with JDK14

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#1244]
Build the project with the latest JDK (14 in this timing) with https://github.com/java9-modularity/gradle-modules-plugin
to make sure we can run tests with Java 9 or later. refs #1136 for example.

This change won't affect the version of .class files (we keep using Java 8 to compile), however, the JPMS support could be updated in this change from using `META-INF` to `package-info.java`.

refs #1123

**Comment by iloveeclipse** [comment]
Could we please stay on Java 11 LTS? Non-LTS Java is not available on RHEL releases.

**Comment by KengoTODA** [comment]
SpotBugs users won't requested to use Java 14, they still can use Java 8 to run. 
This is the proposal to use latest `javac` to build, to let SpotBugs developers to add unit test cases which rely on Java 9 or later like #1136.

**Comment by iloveeclipse** [comment]
Sure, this is clear, but as a developer on RHEL I have no Java 14. Java 11 can also run Java 9+ examples, so that should be fine too.

**Comment by KengoTODA** [comment]
OK first I'll introduce Java 11 the LTS. Later I'll introduce Java 14 to support cases which needs Java 12 or later.

**Comment by KengoTODA** [comment]
#996 is the blocker of this task. Even when I build with `--release 8` option, Java 11 makes different `.class` files and it triggers this issue.

I also tried to add `module-info.java` to each project in 1f671d2, and found that we have several problems to solve:

* Multiple `test-harness` projects provide the same package. Need to rename package to avoid this conflict.
* `jaxen` should be bumped up to `1.2.0` which contains [a fix for jigsaw](https://github.com/jaxen-xpath/jaxen/pull/15/)

**Comment by KengoTODA** [comment]
#996 has been solved. The JPMS problem still exists.

I tried to build the project with Java 14 as #1270, but the build performance was not changed.

**Comment by KengoTODA** [comment]
Now we build with Java 15.
https://github.com/spotbugs/spotbugs/commit/50cb283f3d97bd6de3e1578688eae87d998157e1#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721
