### ISSUE TITLE
Please consider `org.json:json` alternative

### ISSUE THREAD

**Issue by DPUkyle** [spotbugs/spotbugs#1279]
Hi @KengoTODA I see that spotbugs/discuss#95 was merged and released with tool v4.1.0 - that's great!

I have one question about the [license](https://github.com/stleary/JSON-java/blob/20200518/LICENSE) of the `org.json:json` library - it's unconventional and is actually banned by ASF: http://apache.org/legal/resolved.html#category-x -> see "Nonsensical licenses".

Debian lists some alternatives but I'm sure this list is not very current, nor comprehensive: https://wiki.debian.org/qa.debian.org/jsonevil

My organization specifically objects to the license's use of the language "The Software shall be used for Good, not Evil.", as such I'd encourage you to please consider alternative implementations to produce the SARIF report. As a consequence, we will be unable to use spotbugs v4.1.0 or higher ☹️ 

FYI @lgolding @michaelcfanning

**Comment by KengoTODA** [comment]
Working on this issue. Gson seems smaller than Jackson, so I'm trying to play with Gson.

The Gradle plugin isn't working well to generate both annotation and additionalProperties, so reported the issue as https://github.com/eirnym/js2p-gradle/issues/10
If problem will not be resolved, I'll try to code without annotation.

**Comment by sabberworm** [comment]
> My organization specifically objects to the license's use of the language "The Software shall be used for Good, not Evil."

@DPUkyle I think you should quit working for this company ASAP…

**Comment by h-vetinari** [comment]
Any update on this? This is blocking (much of) the hadoop ecosystem from moving to Java 11+, see https://issues.apache.org/jira/browse/HADOOP-17269

**Comment by michaelcfanning** [comment]
@eddynaka @yongyan-gh

 @KengoTODA, want any help with this problem? We're just about to propose a new SARIF contribution that provides for SARIF-friendly rule ids. Maybe we could finish whatever work you've started with gson as well?

Glad to help if you want it.

**Comment by KengoTODA** [comment]
The current blocker for me is [json2pojo does not generate fields of `MessageStrings` as expected](https://github.com/microsoft/sarif-sdk/issues/1952#issuecomment-687668869). 

For the current implementation, I manually coded `MessageStrings` and other classes. But it's better to generate it based on JSON schema. This is why I want to use json2pojo via https://github.com/eirnym/js2p-gradle

**Comment by michaelcfanning** [comment]
ok! we'll take a look and see if we can get the SARIF schema through json2pojo today. More soon...

**Comment by yongyan-gh** [comment]
> The current blocker for me is [json2pojo does not generate fields of `MessageStrings` as expected](https://github.com/microsoft/sarif-sdk/issues/1952#issuecomment-687668869).
> 
> For the current implementation, I manually coded `MessageStrings` and other classes. But it's better to generate it based on JSON schema. This is why I want to use json2pojo via https://github.com/eirnym/js2p-gradle

Hi @KengoTODA , do we have to have POJO classes for resolving this issue? 
Can we leverage existing model classes used to generating Sarif log, and replace org.json lib with gson lib?
I can help with this request.

**Comment by aajisaka** [comment]
Now I think this issue is fixed by #1437 and can be closed. Thank you @yongyan-gh and @KengoTODA!
