### ISSUE TITLE
Problem installing Eclipse plugin in China

### ISSUE THREAD

**Issue by blernermhc** [spotbugs/spotbugs#1294]
I am using the spotbugs Eclipse plugin in my software development class.  I have one student who is in China who is not able to install using the update site.  She always gets a connection refused error shown here.  She is running a VPN and can generally access the Internet, but it seems like github.io gets blocked somehow.  I am wondering if there is a way to get a zip file to install the plug-in instead of going through the update site.

She has been able to install the standalone GUI tool, but that is less convenient than the Eclipse plug-in.  I am attaching a screenshot of the error here.  Any help would be appreciated!

![image](https://user-images.githubusercontent.com/5429878/93480371-5c5efd00-f8cb-11ea-9df5-87e42957c34d.png)

**Comment by KengoTODA** [comment]
One idea is that checking out the `eclipse` project and use zip files in the `gh-pages` branch. `git clone` is rarely blocked, I heard...

https://github.com/spotbugs/eclipse/tree/gh-pages

**Comment by KengoTODA** [comment]
If she can download files from [release page](https://github.com/spotbugs/spotbugs/releases), I'll attach zip file even to there (we did so for 4.0.x but recently removed this mechanism)

**Comment by hazendaz** [comment]
closing as resolved.
