### ISSUE TITLE
BUILD FAILED: Execution failed for task ':spotbugs-annotations:compileJava'. > invalid flag: --release

### ISSUE THREAD

**Issue by YinZho** [spotbugs/spotbugs#1297]
Hi, all
- Operating System
Ubuntu 18.04 (**macOS BUILD SUCCESSFUL**)
- Java Version
openjdk version "11.0.8" 2020-07-14

```
./gradlew clean build 

> Configure project :spotbugs-annotations
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs-ant
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-core
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-jupiter
The signing key and password are null. This can be ignored if this is a pull request.

> Task :spotbugs-annotations:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotbugs-annotations:compileJava'.
> invalid flag: --release

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
But after I tried to comment `options.compilerArgs.addAll(['--release', '8'])` in line11, [java.gradle](https://github.com/spotbugs/spotbugs/blob/master/gradle/java.gradle), it builds successfully.

**I don't know why BUILD SUCCESSFUL on macOS wheras BUILD FAILED on Ubuntu.**

**Comment by pzygielo** [comment]
Can you share the output of `./gradlew --version`.

**Comment by YinZho** [comment]
Ubuntu 18.04
![image](https://user-images.githubusercontent.com/26624606/93716858-94ed2800-fba4-11ea-8d5a-61bdfb7599cd.png)

**Comment by pzygielo** [comment]
As you can see - on `Ubuntu 18.04` your gradle picked JVM 1.8.
Please close this issue.

**Comment by YinZho** [comment]
It seems that the Gradle uses JDK 1.8 version to cause this problem. 
It is solved after I followed the tutorial: [How do I tell Gradle to use specific JDK version?](https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version).
@pzygielo  Thanks a lot!
