### ISSUE TITLE
Annotations should not be deprecated.

### ISSUE THREAD

**Issue by jtnord** [spotbugs/spotbugs#130]
The [findbugs annotations](https://github.com/spotbugs/spotbugs/tree/master/findbugs/src/java/edu/umd/cs/findbugs/annotations) e.g. [`CheckForNull`](https://github.com/spotbugs/spotbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/annotations/CheckForNull.java) [`NonNull`](https://github.com/findbugsproject/findbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/annotations/NonNull.java) etc. should not be marked as deprecated and users should not be directed to use the [JSR-305](https://jcp.org/en/jsr/detail?id=305) equivalents.

JSR-305 is dormant, has been for a long while and shows no hope of ever producing an agreed set of annotations in our lifetime. Further more these annotations use `javax.` packages which it is not possible to use according to the [Oracle Java binary licence](http://www.oracle.com/technetwork/java/javase/terms/license/index.html), so applications can not use and ship these dependencies along with a JRE without violating the Oracle licence agreement.

> F. JAVA TECHNOLOGY RESTRICTIONS. You may not create, modify, or change the behavior of, or authorize your licensees to create, modify, or change the behavior of, classes, interfaces, or subpackages that are in any way identified as "java", "javax", "sun", “oracle” or similar convention as specified by Oracle in any naming convention designation.

The JSR-305 group has not defined any official releases according to its [jsr page](https://jcp.org/en/jsr/detail?id=305) so the only implementations is a seemingly random implementation provided by the FindBugs team. Even if the team where experts on the JSR (which some where) they are not official as there has been no vote and are not available from the JSR hompage - so the  `javax` package name restriction still applies.

So please remove the `@Deprecated` annotation from the spotbugs specific annotations or update the links to point to the new preferred non-jsr305 implementation to use instead.

**Comment by KengoTODA** [comment]
This issue is same with https://github.com/findbugsproject/findbugs/issues/88, and https://github.com/findbugsproject/findbugs/issues/128 contains related discussion.

**Comment by iloveeclipse** [comment]
@KengoTODA : do you plan to PR and merge that?

**Comment by KengoTODA** [comment]
Do you mean #180? In my understanding that is still under discussion.

**Comment by iloveeclipse** [comment]
I don't see any arguments against removing "deprecation" annotations from old FB annotations. JSR-305 is dead, everyone knows it, and the question whether we use some other library in the future is a bit different. Right now we have one set of deprecated annotations and one set of dead JSR-305 annotations violating `javax` package scope. We should of course leave JSR-305 in (there is a lot of code using that), but we should at least provide something which doesn't cause warnings in the code.
