### ISSUE TITLE
Remove the dependency on AppleJavaExtension 

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#1324]
[The library is outdated](https://developer.apple.com/library/archive/samplecode/AppleJavaExtensions/Introduction/Intro.html) and not updated recently. So #418 is caused by the latest macOS.

**Comment by KengoTODA** [comment]
Yes!

**Comment by JuditKnoll** [comment]
@shambhaviprabhat Is there any status update with this issue?

**Comment by shambhaviprabhat** [comment]
> @shambhaviprabhat Is there any status update with this issue?

@JuditKnoll hey sorry, I had not been able to work on this issue due to other commitments.

**Comment by shambhaviprabhat** [comment]
> @shambhaviprabhat Thank you for your answer. Do you still plan to work on it or is it up for grabs?

@JuditKnoll it is free to be grabbed! Thanks!

**Comment by JuditKnoll** [comment]
If anyone is interested, feel free to look into this issue. It looks like we are slowly getting closer to the 5.0.0 release, so if there is a working PR, it won't need to wait so much.

**Comment by Spatrik95** [comment]
I took a look, and overall, it's not that simple. It's easy to remove the 'AppleJavaExtensions', and the only effect of this is that the Mac OS Application bar won't be filled with menu items, just in the application window.
I tried to create a workaround with a JavaFX module, but I couldn't get it to work, unfortunately.

I think the best solution would be to migrate the whole SpotBugs GUI from Java AWT to JavaFX, because the AWT is very old and deprecated and doesn't support modern UI frameworks and solutions.

**Comment by hazendaz** [comment]
@Spatrik95 Take a look at this, https://stackoverflow.com/questions/13978471/com-apple-eawt-what-exactly-i-should-install, sounds like there is an easier way here.

**Comment by hazendaz** [comment]
if you could, send a PR so its easier to know what you have tried and we can also take a look.

**Comment by Spatrik95** [comment]
@hazendaz 
> @Spatrik95 Take a look at this, https://stackoverflow.com/questions/13978471/com-apple-eawt-what-exactly-i-should-install, sounds like there is an easier way here.

The application's console log contains the following when Java tries to use the Apple EAWT components:

```
This version of Mac OS X does not support the Apple EAWT. Application Menu handling has been disabled (java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationAdapter)
```
_(On macOS Sonoma 14.2.1 with M2 Pro)_

The Java 9+ `TaskBar` class only adds menu items and other features to the Dock panel, but it's not what we need.

> if you could, send a PR so its easier to know what you have tried and we can also take a look.

I used the OpenJFX library for this, but we discussed it in another thread, unfortunately, its license is not okay for us.
