### ISSUE TITLE
Spotbugs CLI Option?

### ISSUE THREAD

**Issue by cyberjj999** [spotbugs/spotbugs#1327]
Hello. I am trying to see if there are any Command Line Interface (CLI) options for Spotbugs, I saw this as part of the documentation
![image](https://user-images.githubusercontent.com/51283594/95436702-b90f7e00-0986-11eb-83b5-c3dc568ca98f.png)

However, it seems like I need to have a project file created via the GUI interface? 
I was thinking somewhere along the lines of running a command like
`java -jar spotbugs.jar -inputfile myfile.jar -outputdir /home/user/Desktop/myreport -format xml` or something along this line, may I ask if something similar exist?

Thank you!

**Comment by KengoTODA** [comment]
First of all, I suggest you reading not the FindBugs website but [SpotBugs official manual site](https://spotbugs.readthedocs.io/en/stable/running.html).

The project file is optional. To analyze `myfile.jar`, you need to provide its path as a command-line argument. 
e.g. `java -jar spotbugs.jar -output /home/user/Desktop/myreport.xml -xml myfile.jar`

**Comment by cyberjj999** [comment]
Hello KengoTODA. Thank you so much for the quick response. 
I see, I may have missed the SpotBug's documentation site on the CLI options 😅
Let me give it a shot and update here

**Comment by cyberjj999** [comment]
I can confirm this is the solution, thanks so much for the help!
