### ISSUE TITLE
create custom gradle plugin

### ISSUE THREAD

**Issue by johnscancella** [spotbugs/spotbugs#133]
While it is great that spotbugs is binary compatible with findbugs, I think it would be more helpful to create your own plugin and make it available on the [gradle plugin site](https://plugins.gradle.org/search?term=spotbugs)

**Comment by KengoTODA** [comment]
thanks for your comment, please watch #15 and https://github.com/gradle/gradle/issues/720#issuecomment-258684842 about this topic.

**Comment by johnscancella** [comment]
I mentioned in #15 that the current solution causes problems for me. It is fairly trivial to create a plugin and upload it to the plugins.gradle.org website. Would a pull request for that be welcomed?

**Comment by KengoTODA** [comment]
Closed by #142
