### ISSUE TITLE
./gradlew build is fail with eclipse 4.16.0

### ISSUE THREAD

**Issue by nmtbr1001** [spotbugs/spotbugs#1330]
When running ./gradlew build eclipse with target Eclipse:

Eclipse SDK
Version: 2020-06 (4.16)
PS C:\Users\81804\git\spotbugs\eclipsePlugin> java -version 
 java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
PS C:\Users\81804\git\spotbugs\eclipsePlugin> gradle -version

------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (Oracle Corporation 11.0.8+10-LTS)
OS:           Windows 10 10.0 amd64

I built with reference to　https://github.com/spotbugs/spotbugs/blob/release3.1/eclipsePlugin/doc/building_spotbugs_plugin.txt

Also,I can not run ./gradlew build .
So, I wirrten at C:\Users\81804\git\spotbugs\eclipsePlugin\build.gradle
task wrapper(type: Wrapper) {
    gradleVersion = '6.2.2'//we want gradle 2.10 to run this project
}

help me!! I want to run ./gradlew build!!!

I see errors:

PS C:\Users\81804\git\spotbugs\eclipsePlugin> ./gradlew build    

> Configure project :spotbugs-annotations
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs-ant
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-core
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-jupiter
The signing key and password are null. This can be ignored if this is a pull request.

> Task :spotbugs-annotations:compileJava
ノート:C:\Users\81804\git\spotbugs\spotbugs-annotations\src\main\java\edu\umd\cs\findbugs\annotations\OverrideMustInvoke.javaは推奨されないAPIを使用またはオーバーライドしています。
ノート:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。
<-<-<---
^Z> Task :spotbugs:compileJava
ノート:一部の入力ファイルは推奨されないAPIを使用またはオーバーライドしています。
ノート:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。

> Task :spotbugs:compileGuiJava
ノート:一部の入力ファイルは推奨されないAPIを使用またはオーバーライドしています。
ノート:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。

> Task :eclipsePlugin:compileJava FAILED
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:24: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IResource;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:25: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.CoreException;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:26: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.IProgressMonitor;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:27: エラー: パッケージorg.eclipse.core.runtime.jobsは存在しません
import org.eclipse.core.runtime.jobs.IJobChangeEvent;
                                    ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:28: エラー: パッケージorg.eclipse.core.runtime.jobsは存在しません
import org.eclipse.core.runtime.jobs.JobChangeAdapter;
                                    ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:29: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.IWorkbenchPart;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:25: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IMarker;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:26: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IProject;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:27: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IResource;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:28: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IWorkspace;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:29: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IWorkspaceDescription;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:30: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.ResourcesPlugin;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:31: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.CoreException;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:32: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.IAdaptable;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:33: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.IProgressMonitor;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:34: エラー: パッケージorg.eclipse.jface.actionは存在しません
import org.eclipse.jface.action.IAction;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:35: エラー: パッケージorg.eclipse.jface.dialogsは存在しません
import org.eclipse.jface.dialogs.IDialogConstants;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:36: エラー: パッケージorg.eclipse.jface.dialogsは存在しません
import org.eclipse.jface.dialogs.IDialogSettings;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:37: エラー: パッケージorg.eclipse.jface.dialogsは存在しません
import org.eclipse.jface.dialogs.MessageDialog;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:38: エラー: パッケージorg.eclipse.jface.dialogsは存在しません
import org.eclipse.jface.dialogs.MessageDialogWithToggle;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:39: エラー: パッケージorg.eclipse.jface.preferenceは存在しません
import org.eclipse.jface.preference.IPreferenceStore;
                                   ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:40: エラー: パッケージorg.eclipse.jface.viewersは存在しません
import org.eclipse.jface.viewers.ISelection;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:41: エラー: パッケージorg.eclipse.jface.viewersは存在しません
import org.eclipse.jface.viewers.ISelectionProvider;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:42: エラー: パッケージorg.eclipse.jface.viewersは存在しません
import org.eclipse.jface.viewers.IStructuredSelection;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:43: エラー: パッケージorg.eclipse.jface.viewersは存在しません
import org.eclipse.jface.viewers.TreeViewer;
                                ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:44: エラー: パッケージorg.eclipse.swt.widgetsは存在しません
import org.eclipse.swt.widgets.Display;
                              ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:45: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.IObjectActionDelegate;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:46: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.IPerspectiveDescriptor;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:47: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.IWorkbenchPage;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:48: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.IWorkbenchPart;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:49: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.IWorkbenchPartSite;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:50: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.IWorkbenchWindow;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:51: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.PlatformUI;
                     ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:52: エラー: パッケージorg.eclipse.uiは存在しません
import org.eclipse.ui.WorkbenchException;
                     ^
^ZC:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:73: エラー: シンボルを見つけられません
public class FindBugsAction implements IObjectActionDelegate {
                                       ^
  シンボル: クラス IObjectActionDelegate
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:50: エラー: シンボルを見つけられません
    protected void work(final IWorkbenchPart part, IResource resource, final List<WorkItem> resources) {
                              ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス ClearMarkersAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\ClearMarkersAction.java:50: エラー: シンボルを見つけられません
    protected void work(final IWorkbenchPart part, IResource resource, final List<WorkItem> resources) {
                                                   ^
  シンボル:   クラス IResource
  場所: クラス ClearMarkersAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:34: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IFile;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:35: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IFolder;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:36: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IMarker;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:37: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IProject;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:38: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IResource;
                                 ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:39: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.Assert;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:40: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.CoreException;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:41: エラー: パッケージorg.eclipse.core.runtimeは存在しません
import org.eclipse.core.runtime.IPath;
                               ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:42: エラー: パッケージorg.eclipse.jdt.coreは存在しません
import org.eclipse.jdt.core.ICompilationUnit;
                           ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:43: エラー: パッケージorg.eclipse.jdt.coreは存在しません
import org.eclipse.jdt.core.IJavaElement;
                           ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:44: エラー: パッケージorg.eclipse.jdt.coreは存在しません
import org.eclipse.jdt.core.IJavaProject;
                           ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:45: エラー: パッケージorg.eclipse.jdt.coreは存在しません
import org.eclipse.jdt.core.IPackageFragmentRoot;
                           ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:46: エラー: パッケージorg.eclipse.jdt.coreは存在しません
import org.eclipse.jdt.core.IType;
                           ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:47: エラー: パッケージorg.eclipse.jdt.coreは存在しません
import org.eclipse.jdt.core.JavaCore;
                           ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:48: エラー: パッケージorg.eclipse.jdt.coreは存在しません
import org.eclipse.jdt.core.JavaModelException;
                           ^
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:65: エラー: シンボルを見つけられません
    private final IJavaElement javaElt;
                  ^
  シンボル:   クラス IJavaElement
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:67: エラー: シンボルを見つけられません
    private final IResource resource;
                  ^
  シンボル:   クラス IResource
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:69: エラー: シンボルを見つけられません
    private final IProject project;
                  ^
  シンボル:   クラス IProject
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:71: エラー: シンボルを見つけられません
    public WorkItem(IJavaElement javaElt) {
                    ^
  シンボル:   クラス IJavaElement
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:75: エラー: シンボルを見つけられません
    public WorkItem(IResource resource) {
                    ^
  シンボル:   クラス IResource
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:79: エラー: シンボルを見つけられません
    private WorkItem(IResource resource, IJavaElement javaElt, IProject project) {
                     ^
  シンボル:   クラス IResource
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:79: エラー: シンボルを見つけられません
    private WorkItem(IResource resource, IJavaElement javaElt, IProject project) {
                                         ^
  シンボル:   クラス IJavaElement
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:79: エラー: シンボルを見つけられません
    private WorkItem(IResource resource, IJavaElement javaElt, IProject project) {
                                                               ^
  シンボル:   クラス IProject
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:86: エラー: シンボルを見つけられません
    public void addFilesToProject(Project fbProject, Map<IPath, IPath> outputLocations) {
                                                         ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:86: エラー: シンボルを見つけられません
    public void addFilesToProject(Project fbProject, Map<IPath, IPath> outputLocations) {
                                                                ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:120: エラー: シンボルを見つけら れません
    public void clearMarkers() throws CoreException {
                                      ^
  シンボル:   クラス CoreException
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:145: エラー: シンボルを見つけら れません
    public IProject getProject() {
           ^
  シンボル:   クラス IProject
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:149: エラー: シンボルを見つけら れません
    public IJavaProject getJavaProject() {
           ^
  シンボル:   クラス IJavaProject
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:156: エラー: シンボルを見つけら れません
    private static boolean addClassesForFolder(IFolder folder, Map<IPath, IPath> outLocations, Project fbProject) {
                                               ^
  シンボル:   クラス IFolder
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:156: エラー: シンボルを見つけら れません
    private static boolean addClassesForFolder(IFolder folder, Map<IPath, IPath> outLocations, Project fbProject) {
                                                                   ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:156: エラー: シンボルを見つけら れません
    private static boolean addClassesForFolder(IFolder folder, Map<IPath, IPath> outLocations, Project fbProject) {
                                                                          ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:171: エラー: シンボルを見つけら れません
    private static void addClassesForFile(IFile file, Map<IPath, IPath> outLocations, Project fbProject) {
                                          ^
  シンボル:   クラス IFile
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:171: エラー: シンボルを見つけら れません
    private static void addClassesForFile(IFile file, Map<IPath, IPath> outLocations, Project fbProject) {
                                                          ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:171: エラー: シンボルを見つけら れません
    private static void addClassesForFile(IFile file, Map<IPath, IPath> outLocations, Project fbProject) {
                                                                 ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:202: エラー: シンボルを見つけら れません
    private static String addSecondaryTypesToPattern(IFile file, String fileName, String classNamePattern) {
                                                     ^
  シンボル:   クラス IFile
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:230: エラー: シンボルを見つけら れません
    public @CheckForNull IResource getCorespondingResource() {
                         ^
  シンボル:   クラス IResource
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:249: エラー: シンボルを見つけら れません
    public @CheckForNull IJavaElement getCorespondingJavaElement() {
                         ^
  シンボル:   クラス IJavaElement
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:262: エラー: シンボルを見つけら れません
    public @Nonnull IResource getMarkerTarget() {
                    ^
  シンボル:   クラス IResource
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:288: エラー: シンボルを見つけら れません
    public Set<IMarker> getMarkers(boolean recursive) {
               ^
  シンボル:   クラス IMarker
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:318: エラー: シンボルを見つけら れません
    private static @Nullable IPath getMatchingSourceRoot(@Nullable IPath srcPath, Map<IPath, IPath> outLocations) {
                                                                   ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:318: エラー: シンボルを見つけら れません
    private static @Nullable IPath getMatchingSourceRoot(@Nullable IPath srcPath, Map<IPath, IPath> outLocations) {
                                                                                      ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:318: エラー: シンボルを見つけら れません
    private static @Nullable IPath getMatchingSourceRoot(@Nullable IPath srcPath, Map<IPath, IPath> outLocations) {
                                                                                             ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:318: エラー: シンボルを見つけら れません
    private static @Nullable IPath getMatchingSourceRoot(@Nullable IPath srcPath, Map<IPath, IPath> outLocations) {
                             ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\builder\WorkItem.java:349: エラー: シンボルを見つけら れません
    public @CheckForNull IPath getPath() {
                         ^
  シンボル:   クラス IPath
  場所: クラス WorkItem
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:76: エラー: シンボルを見つけられません
    protected ISelection selection;
              ^
  シンボル:   クラス ISelection
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:81: エラー: シンボルを見つけられません
    private IWorkbenchPart targetPart;
            ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:86: エラー: シンボルを見つけられません
    public final void setActivePart(final IAction action, final IWorkbenchPart targetPart) {
                                          ^
  シンボル:   クラス IAction
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:86: エラー: シンボルを見つけられません
    public final void setActivePart(final IAction action, final IWorkbenchPart targetPart) {
                                                                ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:90: エラー: シンボルを見つけられません
    public static boolean isFindBugsPerspectiveActive(IWorkbenchPart part) {
                                                      ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:96: エラー: シンボルを見つけられません
    public final void selectionChanged(final IAction action, final ISelection newSelection) {
                                             ^
  シンボル:   クラス IAction
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:96: エラー: シンボルを見つけられません
    public final void selectionChanged(final IAction action, final ISelection newSelection) {
                                                                   ^
  シンボル:   クラス ISelection
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:103: エラー: シンボルを見 つけられません
    public void run(final IAction action) {
                          ^
  シンボル:   クラス IAction
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:134: エラー: シンボルを見 つけられません
    protected IDialogSettings getDialogSettings() {
              ^
  シンボル:   クラス IDialogSettings
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:144: エラー: シンボルを見 つけられません
    protected final IProject getProject(IStructuredSelection structuredSelection) {
                                        ^
  シンボル:   クラス IStructuredSelection
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:144: エラー: シンボルを見 つけられません
    protected final IProject getProject(IStructuredSelection structuredSelection) {
                    ^
  シンボル:   クラス IProject
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:167: エラー: シンボルを見 つけられません
    protected void work(IWorkbenchPart part, final IResource resource, final List<WorkItem> resources) {
                        ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:167: エラー: シンボルを見 つけられません
    protected void work(IWorkbenchPart part, final IResource resource, final List<WorkItem> resources) {
                                                   ^
  シンボル:   クラス IResource
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:172: エラー: シンボルを見 つけられません
    protected static void refreshViewer(IWorkbenchPart targetPart, final List<WorkItem> resources) {
                                        ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:201: エラー: シンボルを見 つけられません
    protected static void askUserToSwitch(IWorkbenchPart part, int warningsNumber) {
                                          ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:225: エラー: シンボルを見 つけられません
    protected static IWorkbenchWindow getWindow(IWorkbenchPart part) {
                                                ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:225: エラー: シンボルを見 つけられません
    protected static IWorkbenchWindow getWindow(IWorkbenchPart part) {
                     ^
  シンボル:   クラス IWorkbenchWindow
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\actions\FindBugsAction.java:236: エラー: シンボルを見 つけられません
    protected static void switchPerspective(IWorkbenchPart part) {
                                            ^
  シンボル:   クラス IWorkbenchPart
  場所: クラス FindBugsAction
C:\Users\81804\git\spotbugs\eclipsePlugin\src\de\tobject\findbugs\FindBugsJob.java:24: エラー: パッケージorg.eclipse.core.resourcesは存在しません
import org.eclipse.core.resources.IResource;
                                 ^
ノート:一部の入力ファイルは推奨されないAPIを使用またはオーバーライドしています。
ノート:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。
ノート:入力ファイルの操作のうち、未チェックまたは安全ではないものがあります。
ノート:詳細は、-Xlint:uncheckedオプションを指定して再コンパイルしてください。
エラー100個

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':eclipsePlugin:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
11 actionable tasks: 11 executed

**Comment by hazendaz** [comment]
closing as old, if still an issue please reopen with newer data.
