### ISSUE TITLE
Unsupported api 589824 error with SpotBugs 4.1.4

### ISSUE THREAD

**Issue by victornoel** [spotbugs/spotbugs#1340]
Hi,

Since upgrading to v4.1.4, I'm getting this kind of errors during the execution of spotbugs:
```
     [java]   Unable to get XClass for java/lang/Boolean
     [java]     java.lang.IllegalArgumentException: Unsupported api 589824
     [java]       At org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:76)
     [java]       At org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:57)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM$1.<init>(ClassParserUsingASM.java:552)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:552)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:736)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:79)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:693)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
```

I am using the maven plugin like this with Java 11:
```xml
				<plugin>
					<groupId>com.github.spotbugs</groupId>
					<artifactId>spotbugs-maven-plugin</artifactId>
					<version>4.0.4</version>
					<dependencies>
						<dependency>
							<groupId>com.github.spotbugs</groupId>
							<artifactId>spotbugs</artifactId>
							<version>4.1.4</version>
						</dependency>
					</dependencies>
				</plugin>
```

**Comment by iloveeclipse** [comment]
```
<artifactId>spotbugs-maven-plugin</artifactId>
	<version>4.0.4</version>
```
I'm not a maven user, but that looks suspicious - shouldn't you use higher version of `spotbugs-maven-plugin`

@hazendaz : do we have a 4.1.4 release version for `spotbugs-maven-plugin`? I only see 4.1.3?
https://github.com/spotbugs/spotbugs-maven-plugin/releases

**Comment by cdietrich** [comment]
here is no 4.1.4
https://search.maven.org/artifact/com.github.spotbugs/spotbugs-maven-plugin/4.1.3/maven-plugin

**Comment by victornoel** [comment]
@iloveeclipse @cdietrich indeed, there hasn't been any release of the maven plugin for a long time, but it looks like I missed 4.1.3, let me get back to you about it working or not :)

**Comment by victornoel** [comment]
@iloveeclipse @cdietrich indeed it works with 4.1.3, sorry about that, I got used to the fact there were no release of the maven plugin each time.

Is there any way for the maven plugin to be always automatically released along the rest of the spotbugs artifacts?

**Comment by hazendaz** [comment]
@victornoel It depends on what needs changed in maven line if anything.  Most often it is not changing so overriding the version is all that is needed.  4.1.3 was released a few weeks back and as you discovered it work with override to 4.1.4.  I can push a release on 4.1.4 today.  Its only been a couple of days in this case ;)

**Comment by victornoel** [comment]
@hazendaz yep, actually, it's not really required for me, it's ok as it is now (I will close this issue, should have done it before, sorry :), but I didn't realise they were in separate repository so with potential different versioning.

**Comment by hazendaz** [comment]
@victornoel No worries.  The versioning generally tracks the same, its just released differently.  I am in process of pushing out 4.1.4 though now and it should be available in central in next couple hours.
