### ISSUE TITLE
How to use SpotBugs with SARIF?

### ISSUE THREAD

**Issue by eddynaka** [spotbugs/spotbugs#1349]
Hi All,

I have been trying to compile and run the solution to test the sarif output.

After using the gradlew script, i was able to build the .jar file, but when I double click the .jar, the interface isn't launching.

My questions:
1. should the double click work in Windows?
2. how can I test and generate a sarif locally?

What I did to test:
```
spotbugs\build\libs> java .\spotbugs-4.1.5-SNAPSHOT.jar
Error: Could not find or load main class .\spotbugs-4.1.5-SNAPSHOT.jar

spotbugs\build\libs> java -jar .\spotbugs-4.1.5-SNAPSHOT.jar -gui
no main manifest attribute, in .\spotbugs-4.1.5-SNAPSHOT.jar
```

Followed this tutorial: https://spotbugs.readthedocs.io/en/latest/running.html

Thank you!

**Comment by KengoTODA** [comment]
I recommend you to use the `spotbugs.jar` distributed at [the release page](https://github.com/spotbugs/spotbugs/releases/tag/4.1.4).  
I guess that you use the one in `spotbugs/build/libs`, but this jar file is not ready to run. We also needs to put libraries to necessary places. If you need to build spotbugs from the source, you can unpack archive in `spotbugs/build/distributions` then it has libraries in proper place.

To use SARIF report, add `-sarif` option as [described in the document](https://spotbugs.readthedocs.io/en/stable/running.html#command-line-options). 👍

**Comment by eddynaka** [comment]
Hello @KengoTODA , 

thanks for the answer!

When I changed from VSCode to IntelliJ I was able to compile and debug!

When I use the sarif option, I saw that the physicalLocation wasn't filled correctly. Doing some stepin/stepout, I saw that the `project` has a property called `srcDirList` but that was always empty.

Looking at this (`buildClassPath` method):
```java
List<String> pathNames = new ArrayList<>();
        for (Iterator<? extends ICodeBase> i = classPath.appCodeBaseIterator(); i.hasNext();) {
            ICodeBase appCodeBase = i.next();

            if (appCodeBase.containsSourceFiles()) {
                String pathName = appCodeBase.getPathName();
                if (pathName != null) {
                    pathNames.add(pathName);
                }
            }

            project.addTimestamp(appCodeBase.getLastModifiedTime());
        }
```

The code is passing here, but the condition checking if it contains source code was always false.

Is it a compilation flag that emits the sourcefile with the jar?


Thank you again!

**Comment by KengoTODA** [comment]
> When I use the sarif option, I saw that the physicalLocation wasn't filled correctly. 

Maybe same to #1281? I'll check later.

**Comment by eddynaka** [comment]
> > When I use the sarif option, I saw that the physicalLocation wasn't filled correctly.
> 
> Maybe same to #1281? I'll check later.

I already have a branch with some changes. Would you mind to take a look?
