### ISSUE TITLE
ant task, annotations and test-harness depends on `com.github.spotbugs:findbugs:3.1.0-RC1`

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#135]
It seems that dependency on `project(':findbugs')` generates invalid `pom.xml`.

**Comment by KengoTODA** [comment]
It seems that deployed pom has no problem. http://search.maven.org/#artifactdetails%7Ccom.github.spotbugs%7Ctest-harness%7C3.1.0-RC1%7Cjar

However, `./gradlew clean install` will generate pom file with following `<dependency>`. I tested at commit 9751a22ac.

```xml
    <dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>findbugs</artifactId>
      <version>3.1.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by KengoTODA** [comment]
@jsotuyod Do we have any reason to keep the name of `findbugs` directory? If not, I will try to rename it with `spotbugs`.
https://github.com/spotbugs/spotbugs/blob/75ce07715bff5b5717eeb3e768696d4d653ef781/findbugs/build.gradle#L71

**Comment by jsotuyod** [comment]
@KengoTODA I'm fully in favor of that
