### ISSUE TITLE
How to write project specific script for Spotbugs ?

### ISSUE THREAD

**Issue by ranjdas31** [spotbugs/spotbugs#1357]

**Comment by ThrawnCA** [comment]
I'm not certain what you mean by a project-specific script. Do you mean a custom detector? You can look at the existing detectors for guidance on how to write one; if you can elaborate on what kind of code you want to detect, I might be able to point you toward some relevant examples.

**Comment by ranjdas31** [comment]
Actually the custom Spot bug script will check the code in git lab using CI
pipeline and send the details bug details to the developer.

**Comment by ThrawnCA** [comment]
That sounds like you need a script integrated with your build tool. SpotBugs has plugins for Maven, Gradle, and Eclipse; you can probably work with one of those to do what you want.

**Comment by ranjdas31** [comment]
I have successfully installed the SpotBugs in Eclipse. As per our
requirement we need to automate the task in GitLab. Can you help me to
create the configuration to automate the process through SpotBugs.

**Comment by ThrawnCA** [comment]
Sorry, I don't have expertise in GitLab.

**Comment by KengoTODA** [comment]
I suggest you to visit Gitlab's community to ask. If you're already using build tools like Maven or Gradle, its plugin should be a good entry for you.
