### ISSUE TITLE
Typo in japanese documentation 

### ISSUE THREAD

**Issue by ysknmt** [spotbugs/spotbugs#1364]
`fainal` should be `final`.

https://spotbugs.readthedocs.io/ja/latest/bugDescriptions.html?highlight=fainal#ci-final-protected-ci-confused-inheritance
> このクラスは， final と宣言されていますが，フィールドは protected と宣言されています。 クラスは fainal なので派生できません。protected の使用は紛らわしいです。 フィールドのためのアクセス修飾子は，フィールドの真の用途を表すため， private か public に変更すべきです。

I can't fix this, because I don't have permissions for adding fix on Read the Docs project https://readthedocs.org/projects/spotbugs/.

**Comment by ysknmt** [comment]
Thanks for your reaction @KengoTODA 
I'm interested in fixing this. In my understanding, I need a permission of Read the docs project to fix translation, is this right?  And could you give permission to me?

**Comment by wreulicke** [comment]
@ysknmt 
Thank you for reporting a issue.
That description is generated by this script with message xml.
https://github.com/spotbugs/spotbugs/blob/master/docs/extensions/generate_bug_description.py

So, you can find the message in https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/messages_ja.xml .
Would you like to try to fix this issue?
We can accept changes through pull requests.

**Comment by ysknmt** [comment]
Thanks @wreulicke ! I couldn't find that, because GitHub repository search didn't catch that.

I've created PR #1371, please take a look.
