### ISSUE TITLE
Display findings in the Problems view

### ISSUE THREAD

**Issue by Pontesegger** [spotbugs/spotbugs#1377]
Eclipse provides a default Problems view for warnings and errors. Would be great if SpotBugs could display its warnings there, too.  perfectly fine to keep the Bug Explorer as additional - more specific - view. But if each tool had its separate view, its harder to manage.

**Comment by iloveeclipse** [comment]
@Pontesegger : it is already there, since ever.

**Comment by Pontesegger** [comment]
Sorry, my bad. I used a wrong filter setting on the Problems view, thats why I did not see it,
