### ISSUE TITLE
EC_UNRELATED_TYPES is a non-issue if actual type is integer and expected type is double

### ISSUE THREAD

**Issue by davidmichaelkarr** [spotbugs/spotbugs#1379]
The error code EC_UNRELATED_TYPES refers to "call to equals comparing different types" and appears in the "Scariest" category.

When the actual type of the expression is integer, and the target type is double, this isn't scary at all. In fact, it doesn't cause any problem.

It's a little difficult for me to encourage developers to pay attention to the "Scariest" category when we find "bugs" in this category that shouldn't be there.

I don't know what this should do instead of what it's doing, but the result right now is not optimal.

**Comment by tweimer** [comment]
It is an issue, for example, the following code will return `false`:
```
        Integer i = 3;
        System.out.println(i.equals(3.0));
```

**Comment by davidmichaelkarr** [comment]
Ah, I see what happened.  The assertion this code was within is broken and effectively ignores the result. Never mind.
