### ISSUE TITLE
running with spotbugs.experimental.multiThread=true raises AssertionError

### ISSUE THREAD

**Issue by radopas** [spotbugs/spotbugs#1393]
Hello,
I'm trying to use spotbugs 4.2.0 with multithreading enabled in order to speedup the checks but 
enabling multithreading with -Dspotbugs.experimental.multiThread=true results in error :

```
java.lang.AssertionError: Asked to end timing for class edu.umd.cs.findbugs.detect.FieldItemSummary but top of stack is class edu.umd.cs.findbugs.detect.FindNoSideEffectMethods, remaining stack is [edu.umd.cs.findbugs.log.Profiler$Clock@6e230e78, edu.umd.cs.findbugs.log.Profiler$Clock@6a1c8764, edu.umd.cs.findbugs.log.Profiler$Clock@2f1e0443, edu.umd.cs.findbugs.log.Profiler$Clock@685dc9f8, edu.umd.cs.findbugs.log.Profiler$Clock@1e7b4a45, edu.umd.cs.findbugs.log.Profiler$Clock@10d2d949, edu.umd.cs.findbugs.log.Profiler$Clock@4f31fb0c, edu.umd.cs.findbugs.log.Profiler$Clock@4925f91b, edu.umd.cs.findbugs.log.Profiler$Clock@75c89afe, edu.umd.cs.findbugs.log.Profiler$Clock@75af9303, edu.umd.cs.findbugs.log.Profiler$Clock@7af5dcca, edu.umd.cs.findbugs.log.Profiler$Clock@7691a9a7, edu.umd.cs.findbugs.log.Profiler$Clock@566be221, edu.umd.cs.findbugs.log.Profiler$Clock@2682b459, edu.umd.cs.findbugs.log.Profiler$Clock@72c52fcf]
        at edu.umd.cs.findbugs.log.Profiler.end(Profiler.java:274)
        at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:78)
        at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1108)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Dichotomia** [comment]
I tried this option in 4.2.1 i have this problem:
     [java] [main] WARN edu.umd.cs.findbugs.FindBugs2 - Multi-thread analysis is still experimental!
     [java] Exception in thread "main" edu.umd.cs.findbugs.ba.AnalysisException: Exeption was thrown during analysis
     [java]     at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1125)
     [java]     at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     [java]     at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
     [java] Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Asked to end timing for class edu.umd.cs.findbugs.NonReportingDetectorToDetector2Adapter but top of stack is class edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine, rema
ining stack is [edu.umd.cs.findbugs.log.Profiler$Clock@623b5c46, edu.umd.cs.findbugs.log.Profiler$Clock@2739de65, edu.umd.cs.findbugs.log.Profiler$Clock@56b22733, edu.umd.cs.findbugs.log.Profiler$Clock@1654bf9f, edu.umd.cs.findbugs.log.Profiler$Clock@2e35187f, edu.umd.cs
.findbugs.log.Profiler$Clock@4716212a, edu.umd.cs.findbugs.log.Profiler$Clock@da0d44, edu.umd.cs.findbugs.log.Profiler$Clock@3341f287, edu.umd.cs.findbugs.log.Profiler$Clock@3531f270, edu.umd.cs.findbugs.log.Profiler$Clock@43589a8d, edu.umd.cs.findbugs.log.Profiler$Clock
@13b80f8f, edu.umd.cs.findbugs.log.Profiler$Clock@2fd112b5, edu.umd.cs.findbugs.log.Profiler$Clock@15c9d74d, edu.umd.cs.findbugs.log.Profiler$Clock@12c2ab8b, edu.umd.cs.findbugs.log.Profiler$Clock@41d50a2b, edu.umd.cs.findbugs.log.Profiler$Clock@66b6fc1e, edu.umd.cs.find
bugs.log.Profiler$Clock@3d9e3c3a, edu.umd.cs.findbugs.log.Profiler$Clock@3a8756f1, edu.umd.cs.findbugs.log.Profiler$Clock@53ea97d8, edu.umd.cs.findbugs.log.Profiler$Clock@26dc7b7, edu.umd.cs.findbugs.log.Profiler$Clock@4ede442c, edu.umd.cs.findbugs.log.Profiler$Clock@4e6
ea3d8, edu.umd.cs.findbugs.log.Profiler$Clock@493db99a, edu.umd.cs.findbugs.log.Profiler$Clock@25818f75, edu.umd.cs.findbugs.log.Profiler$Clock@19c250cd, edu.umd.cs.findbugs.log.Profiler$Clock@2209504e, edu.umd.cs.findbugs.log.Profiler$Clock@6dcccfc]
     [java]     at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java]     at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
     [java]     at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1120)
     [java]     ... 5 more
     [java] Caused by: java.lang.AssertionError: Asked to end timing for class edu.umd.cs.findbugs.NonReportingDetectorToDetector2Adapter but top of stack is class edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine, remaining stack is [edu.umd.cs.findbugs.log.P
rofiler$Clock@623b5c46, edu.umd.cs.findbugs.log.Profiler$Clock@2739de65, edu.umd.cs.findbugs.log.Profiler$Clock@56b22733, edu.umd.cs.findbugs.log.Profiler$Clock@1654bf9f, edu.umd.cs.findbugs.log.Profiler$Clock@2e35187f, edu.umd.cs.findbugs.log.Profiler$Clock@4716212a, ed
u.umd.cs.findbugs.log.Profiler$Clock@da0d44, edu.umd.cs.findbugs.log.Profiler$Clock@3341f287, edu.umd.cs.findbugs.log.Profiler$Clock@3531f270, edu.umd.cs.findbugs.log.Profiler$Clock@43589a8d, edu.umd.cs.findbugs.log.Profiler$Clock@13b80f8f, edu.umd.cs.findbugs.log.Profil
er$Clock@2fd112b5, edu.umd.cs.findbugs.log.Profiler$Clock@15c9d74d, edu.umd.cs.findbugs.log.Profiler$Clock@12c2ab8b, edu.umd.cs.findbugs.log.Profiler$Clock@41d50a2b, edu.umd.cs.findbugs.log.Profiler$Clock@66b6fc1e, edu.umd.cs.findbugs.log.Profiler$Clock@3d9e3c3a, edu.umd
.cs.findbugs.log.Profiler$Clock@3a8756f1, edu.umd.cs.findbugs.log.Profiler$Clock@53ea97d8, edu.umd.cs.findbugs.log.Profiler$Clock@26dc7b7, edu.umd.cs.findbugs.log.Profiler$Clock@4ede442c, edu.umd.cs.findbugs.log.Profiler$Clock@4e6ea3d8, edu.umd.cs.findbugs.log.Profiler$C
lock@493db99a, edu.umd.cs.findbugs.log.Profiler$Clock@25818f75, edu.umd.cs.findbugs.log.Profiler$Clock@19c250cd, edu.umd.cs.findbugs.log.Profiler$Clock@2209504e, edu.umd.cs.findbugs.log.Profiler$Clock@6dcccfc]
     [java]     at edu.umd.cs.findbugs.log.Profiler.end(Profiler.java:274)
     [java]     at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1114)
     [java]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     [java]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     [java]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     [java]     at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by KengoTODA** [comment]
It's just experimental and only for spotbugs developers. Many detectors still need update to run properly. Waiting your contribution ლ(´ڡ`ლ)
