### ISSUE TITLE
Add documentation for how visitors map to Bug Detections

### ISSUE THREAD

**Issue by walkerbrianpatrick** [spotbugs/spotbugs#1400]
The spotbugs documentation could be improved by adding a section on which visitor triggers a bugs detection. The only way to figure out this information ATM is to grep for the detection name in spotbugs/src/main/java/edu/umd/cs/findbugs/detect.

This could either be in a table, or added as an additional field for each bug detection on spotbugs.readthedocs.io/en/latest/bugDescriptions.html.

**Comment by KengoTODA** [comment]
Just like [bug description page](https://github.com/spotbugs/spotbugs/blob/b848f9a5bfab0522c349b857ba9d71e691145497/docs/extensions/generate_bug_description.py) we can generate the page based on `findbugs.xml`.

**Comment by andipabst** [comment]
I'd like to work on this as a Hacktoberfest contribution.

**Comment by KengoTODA** [comment]
#1651 added a page https://spotbugs.readthedocs.io/en/latest/detectors.html
it could be a solution for this issue.

**Comment by andipabst** [comment]
Ah yes, this is indeed a solution I guess. Thanks for pointing it out!

**Comment by gayatrib** [comment]
Can this issue be marked closed as the documentation pointed out on Oct 1st seems adequate? Just don't want to get hopes up of first timers like me:)

**Comment by walkerbrianpatrick** [comment]
Sorry, didn't realize it was on me to close it. The new documentation looks good, though I wish there was a link from the bugDetection to the visitor like the visitors have links to the bugs. Small potatoes. Great work!
