### ISSUE TITLE
CE_CLASS_ENVY Method excessively uses methods of another class Java

### ISSUE THREAD

**Issue by panditb** [spotbugs/spotbugs#1407]
Spotbug is giving the violation for the below code

   ```
@SpringBootTest
    @ActiveProfiles("test")
    class LocationServiceTest {
    
    @MockBean
    LocationService locationService;
    
    @Test 
    void shouldFetchAllLocation_whenQueried() {
       when(locationService.findAll(any(),any()).thenReturn(List.of(location("LOC1"), location("LOC2"))
    }
    
   private Location location(String id) {
        return Location.builder()
               .id(id)
               .name("name"+id)
               .postalAddress("PostalAddress")
               .region("region")
               .build();       
}
    }
```

This method(location) makes extensive use of methods from another class over methods of its own, but the method location(String id) calling in the same class only not in any other Test class but still gives this spotbug violation .

Thanks for your help !!

**Comment by KengoTODA** [comment]
`CE_CLASS_ENVY` is not a part of SpotBugs. It is provided by fb-contrib. So please issue your request to https://github.com/mebigfatguy/fb-contrib/issues instead.
