### ISSUE TITLE
Task spotbugsMain FAILED

### ISSUE THREAD

**Issue by javavirys** [spotbugs/spotbugs#1408]
Hello, when running spotbugsMain, I get an error:

 ./gradlew spotbugsMain

> Task :app:spotbugsMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:spotbugsMain'.
> Could not resolve all files for configuration ':app:runtimeClasspath'.
   > Could not resolve androidx.appcompat:appcompat:1.2.0.
     Required by:
         project :app
         project :app > androidx.constraintlayout:constraintlayout:2.0.4
         project :app > com.google.dagger:dagger-android-support:2.30.1
      > No matching variant of androidx.appcompat:appcompat:1.2.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'releaseApiPublication' capability androidx.appcompat:appcompat:1.2.0 declares a library, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component, with the library elements 'aar' and the consumer needed a runtime of a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
          - Variant 'releaseRuntimePublication' capability androidx.appcompat:appcompat:1.2.0 declares a runtime of a library, and its dependencies declared externally:
              - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
          - Variant 'sourcesElements' capability androidx.appcompat:appcompat:1.2.0 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
   > Could not resolve androidx.browser:browser:1.3.0.
     Required by:
         project :app
      > No matching variant of androidx.browser:browser:1.3.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'releaseApiPublication' capability androidx.browser:browser:1.3.0 declares a library, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component, with the library elements 'aar' and the consumer needed a runtime of a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
          - Variant 'releaseRuntimePublication' capability androidx.browser:browser:1.3.0 declares a runtime of a library, and its dependencies declared externally:
              - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
          - Variant 'sourcesElements' capability androidx.browser:browser:1.3.0 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
   > Could not resolve com.google.android.material:material:1.2.1.
     Required by:
         project :app
      > No matching variant of com.google.android.material:material:1.2.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'releaseApiPublication' capability com.google.android.material:material:1.2.1 declares a library, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component, with the library elements 'aar' and the consumer needed a runtime of a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
          - Variant 'releaseRuntimePublication' capability com.google.android.material:material:1.2.1 declares a runtime of a library, and its dependencies declared externally:
              - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
   > Could not resolve androidx.appcompat:appcompat:1.0.0.
     Required by:
         project :app > com.airbnb.android:lottie:3.0.7
      > No matching variant of androidx.appcompat:appcompat:1.2.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'releaseApiPublication' capability androidx.appcompat:appcompat:1.2.0 declares a library, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component, with the library elements 'aar' and the consumer needed a runtime of a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
          - Variant 'releaseRuntimePublication' capability androidx.appcompat:appcompat:1.2.0 declares a runtime of a library, and its dependencies declared externally:
              - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, packaged as a jar
              - Other compatible attribute:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
          - Variant 'sourcesElements' capability androidx.appcompat:appcompat:1.2.0 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)

**Comment by KengoTODA** [comment]
> Could not resolve all files for configuration ':app:runtimeClasspath'.

This problem is not related with SpotBugs itself. Please check your build config.
If you still need support from SpotBugs community, consider to provide a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce.
