### ISSUE TITLE
Schema Target Namespace

### ISSUE THREAD

**Issue by kev22257** [spotbugs/spotbugs#1416]
If you look at https://raw.githubusercontent.com/findbugsproject/findbugs/master/findbugs/etc/findbugsfilter.xsd you'll see the schema target namespace as http://findbugs.sourceforge.net/filter/3.0.0 which is a dead URL.  Any way to update this to a valid value?  This is causing XML validation errors.  I poked around and didn't see any 4.0.0 version either.  Also, this is documented in the filter file documentation so that probably needs to be updated too (https://spotbugs.readthedocs.io/en/latest/filter.html)?

**Comment by KengoTODA** [comment]
It's already replaced with `https://github.com/spotbugs/filter/3.0.0` in this repository:

https://github.com/spotbugs/spotbugs/blob/2367aeea72ca654d2818c6a37578aa1f58db131e/spotbugs/etc/findbugsfilter.xsd#L2-L3

It's still invalid value responding 400.

**Comment by NeetigyaPod** [comment]
Hi, would like to work on this, is this still up for grab?

**Comment by hazendaz** [comment]
@NeetigyaPod Sure take a look into this one.  I presume its still valid and not being worked on.

**Comment by NeetigyaPod** [comment]
How should I go about to find the correct URL and the correct version? I am a bit new to Open-source, will look around in the docs till then.

**Comment by hazendaz** [comment]
Hi, you would want to add this element ```xsi:schemaLocation=https://github.com/spotbugs/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/master/spotbugs/etc/findbugsfilter.xsd ```

No need to call out the version...

**Comment by NeetigyaPod** [comment]
Hi, have created a PR with the solution.
