### ISSUE TITLE
Match Package

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs#1460]
So, there's a pretty prevalent issue (it's actually a bug on here) in one of our packages, and I'd like to ignore that bug for package, unfortunately there doesn't seem to be a way to do that. I'd love a way to ignore by package (be it detected by path or parsing the class "header"), or just by path in general. I suspect it would have to support regex or globbing.

*update*

I see I can do it like this, maybe just an example in the doc?

```xml
        <Class name="~com\.foo\.db\.liquibase\.customchanges\..*"/>
````

still it would be nice to be able to write this instead of a regex.

```xml
<Package name="com.foo.bar"/>
```

**Comment by ThrawnCA** [comment]
You can do that. See https://spotbugs.readthedocs.io/en/stable/filter.html#package

**Comment by xenoterracide** [comment]
How did I miss that, I swear I looked.

**Comment by xenoterracide** [comment]
hmm, maybe reopen, the XSD is not autocompleting <Package> in my IDE, maybe it's missing? also possible it's a local environment issue.
