### ISSUE TITLE
Build fails under JDK 8 (fails to parse specification version number)

### ISSUE THREAD

**Issue by ThrawnCA** [spotbugs/spotbugs#1462]
Line 61 of `spotbugsTestCases/build.gradle` expects "java.specification.version" to be an integer, but mine is "1.8", so it fails.

**Comment by KengoTODA** [comment]
I'll fix this, but currently SpotBugs is expected to build with Java 11 or later, so we'll find other problems even after we solve this issue. For instance, `spotbugs-tests` project contains [tests depending on `../java11` directory](https://github.com/spotbugs/spotbugs/blob/a6f9acb2932b54f5b70ea8bc206afb552321a222/spotbugs-tests/src/test/java/edu/umd/cs/findbugs/ba/Issue408Test.java#L31).

**Comment by ThrawnCA** [comment]
Thanks. I do have java 11 on my system, just haven't been using it because I've been working with code that hasn't migrated to it.
