### ISSUE TITLE
How to check how much time each bug type adds to the build

### ISSUE THREAD

**Issue by lasselindqvist** [spotbugs/spotbugs#1468]
I tried to find how to check how much time each bug type adds to the build, but couldn't find any easy way to do it. Is there such a way either with or without the Maven plugin?

FindbugsProgress (https://github.com/spotbugs/spotbugs/blob/master/spotbugs/src/main/java/edu/umd/cs/findbugs/FindBugsProgress.java#L31) or Reporter that implements it does not seem to have anything related to reporting the analysis times.

And if this does not exist, I might be interesting to make it possible. Any suggestion where to start?

**Comment by gtoison** [comment]
Sorry for the belated answer, SpotBugs has a built-in profiler so it might be a good place to start: https://github.com/spotbugs/spotbugs/blob/master/spotbugs/src/main/java/edu/umd/cs/findbugs/log/Profiler.java
I'll close this as we're trying to reduce the backlog of old issues but please don't hesitate to ask further questions
