### ISSUE TITLE
 False report of Double.valueOf()

### ISSUE THREAD

**Issue by cmCAFEBABE** [spotbugs/spotbugs#1481]
Double.valueOf(a) doesn't have a cache, but when I use new Double(a), spotBugs prompts me to use Double.valueOf(a) instead of new Double(). This is not true. Although it is correct for Integer.

**Comment by ThrawnCA** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#valueOf-double- claims that it _does_ have a cache, or at least it can depending on implementation.

**Comment by hazendaz** [comment]
closing as answered and appropriate way to do.  Most tooling will auto correct to use this way at this point in time.
