### ISSUE TITLE
Implementing a plugin for Workfusion code?

### ISSUE THREAD

**Issue by alexpercont** [spotbugs/spotbugs#1485]
Hello. I posted this question some minutes ago in StackOverflow: 
https://stackoverflow.com/questions/52318021/is-there-any-sast-tool-for-workfusion-code

So I'm reaching you guys here with the same question.

I'm in need to perform static security analysis on code implemented for Workfusion, Workfusion uses Java and groovy code embedded in XML files. I'm actually having troubles in checking how can I include the parsing the xml files to extract the groovy code and pass it through spotbugs + findsecbugs.

Any guidance you could provide?

**Comment by gtoison** [comment]
The StackOverflow question was answered by the author of FindSecurityBugs and that was a while ago, so I think we can close that one
