### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by henrik242** [spotbugs/spotbugs#15]
How do I integrate spotbugs in Gradle?

**Comment by jsotuyod** [comment]
**Right now SpotBugs has no releases**. We plan on making a 3.1.0 release with improved Java 8 support ASAP.

Once released, you will be able to use SpotBugs by using the [Gradle FindBugs plugin](https://docs.gradle.org/current/userguide/findbugs_plugin.html), and simply swapping FindBugs with SpotBugs by adding to your `build.gradle`:

```
configurations {
  findbugs {
    exclude group:'com.google.code.findbugs', module:'findbugs'
  }
}
dependencies {
  findbugs 'com.github.spotbugs:spotbugs:3.1.0'
}
```

Non the less, [we are talking with the Gradle dev team](https://github.com/gradle/gradle/issues/720#issuecomment-258684842) to get official support from them on future Gradle releases.

Once released, we will add these instructions to the website, as stated in #5

**Comment by henrik242** [comment]
Thanks!

**Comment by henrik242** [comment]
With #38 and #39 I guess this can be closed

**Comment by KengoTODA** [comment]
Maybe we can send PR to this package, to add SpotBugs gradle plugin.

* https://github.com/gradle/gradle/tree/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality

**Comment by jsotuyod** [comment]
Maybe, but with findbugs dead they may want to simply rework what they have. 

In the meantime, what I wrote for https://github.com/spotbugs/spotbugs/issues/15#issuecomment-258816606 should work just fine, even for older gradle versions.

**Comment by johnscancella** [comment]
I tried the suggested change in the [#15 (comment)](https://github.com/spotbugs/spotbugs/issues/15#issuecomment-258816606)

but it still will not run correctly, here is the error I am seeing in gradle
```
* What went wrong:
Execution failed for task ':findbugsMain'.
> Unable to infer the version of FindBugs from currently specified FindBugs classpath: [spotbugs-3.1.0-RC1.jar, asm-debug-all-6.0_ALPHA.jar, jcip-annotations-1.0.jar, dom4j-1.6.1.jar, commons-lang-2.6.jar, jaxen-1.1.6.jar, jdepend-2.9.1.jar, jFormatString-3.0.0.jar, spotbugs-annotations-3.1.0-RC1.jar, xml-apis-1.0.b2.jar, jsr305-3.0.1.jar]
```

**Comment by jsotuyod** [comment]
@johnscancella mmm... Gradle seems to be [really hardwired](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/findbugs/FindBugsClasspathValidator.java#L52), I didn't recall them doing this....

It seems we will need a custom plugin until Gradle officially switches after all....

**Comment by johnscancella** [comment]
@jsotuyod I am happy to provide a pull request for a custom plugin

**Comment by KengoTODA** [comment]
@johnscancella When you add a custom plugin, please consider to update this document at the same time.
https://github.com/spotbugs/spotbugs/blob/master/docs/migration.rst#findbugs-gradle-plugin

Then we can host updated migration guide at [ReadTheDocs](http://spotbugs.readthedocs.io/en/latest/migration.html#findbugs-gradle-plugin).

**Comment by jsotuyod** [comment]
@johnscancella can't wait for it! Thanks!

**Comment by johnscancella** [comment]
@jsotuyod see https://github.com/spotbugs/spotbugs/pull/142
not completely done but it is a good first start. You would still need to sign up for an account from gradle so you can upload the plugin to them.

**Comment by jsotuyod** [comment]
@johnscancella yeah, don't worry. I already have one as the author of https://github.com/monits/static-code-analysis-plugin.

Amazing job!
