### ISSUE TITLE
incorrect detection of field not being written to

### ISSUE THREAD

**Issue by ekrisza** [spotbugs/spotbugs#1511]
On the file: https://github.com/eclipse/titan.EclipsePlug-ins/blob/master/org.eclipse.titan.common/src/org/eclipse/titan/common/Activator.java
in line 50: the following bug is detected: "Unwritten field: org.eclipse.titan.common.Activator.usageStatSenderJob"

This looks like a wrong detection as the field can be written in line 43.

**Comment by gtoison** [comment]
Unfortunately there was no answer to this issue and the linked file is now unvailable
I'll close this and please open a new issue if the problem persists
