### ISSUE TITLE
False negatives on RV_01_TO_INT

### ISSUE THREAD

**Issue by gloNelson** [spotbugs/spotbugs#1518]
Hi, 
I found false negatives on `RV_01_TO_INT` when reading the source code of SpotBugs in line 1171 of [DumbMethods.java](https://github.com/spotbugs/spotbugs/blob/f1ee08d5c74cf5fa9a53aae0f5f05dea8e8cd52a/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/DumbMethods.java#L1171)

It seems that SpotBugs only checks for several APIs that generate a random value (`Math.random()` and `nextDouble()`) but omits the `nextFloat()` API that can be used for the same purpose.

However, I think that based on its bug description that "nextFloat()" is not mentioned as an exception, the pattern `RV_01_TO_INT` should provide more support to the method `nextFloat()`.

Here is the demo,
```java
void test(){
    Random random = new Random();
    float f = random.nextFloat() * num; // no warning (false negative)
}
```

**Comment by dejan2609** [comment]
@gloNelson what is your Spotbugs version ?

**Comment by gloNelson** [comment]
@dejan2609 Hi, it is the latest version of Spotbugs. Thank you for your reply.
