### ISSUE TITLE
Generate sarif/html report with maven plugin

### ISSUE THREAD

**Issue by javixeneize** [spotbugs/spotbugs#1543]
Hi

Is there any option to generate a sarif or html report using the maven plugin? 

Thanks

**Comment by h3xstream** [comment]
Just for reference: https://github.com/spotbugs/spotbugs-maven-plugin/pull/339
I am currently working on it.

**Comment by gtoison** [comment]
This was fixed by https://github.com/spotbugs/spotbugs-maven-plugin/pull/339
