### ISSUE TITLE
How can I analyze groovy source files?

### ISSUE THREAD

**Issue by Walterfritz** [spotbugs/spotbugs#1552]
I'd like to use spotbugs to analyze groovy source code files.
My current understandig is that I need to compile the groovy files in a statically form prior running spotbugs.
Am I'm right?
And what are the further needed steps? Are there maybe exist a detailed description - an how to?

Many thanks and best regards

**Comment by ThrawnCA** [comment]
SpotBugs runs on compiled bytecode, yes. The README includes advice on running it via Ant, Maven, Gradle, or Eclipse; whichever tool you prefer should work.

**Comment by gtoison** [comment]
Apparently there was no further question so I'll close this
