### ISSUE TITLE
SpotBugs: findbugs encountered a problem 

### ISSUE THREAD

**Issue by dimpy17agg** [spotbugs/spotbugs#1564]
Can anyone tell me how to fix this problem.

I have installed the spotbugs from eclipse marketplace and then i right clicked on my project and then on spotbugs and then findbugs it display a message box with the message that findbugs encountered a problem .
 Details of the msg -> An internal error occurred during: "Finding bugs in project_name". 'org.eclipse.jdt.internal.compiler.env.IModule org.eclipse.jdt.internal.core.builder.ClasspathJrt.getModule(java.lang.String)'.

eclipse version- (2019-12)
And it shows with all projects in my eclipse.
Please tell me how to fix this problem as it is important to use spotbugs in my project.

**Comment by gtoison** [comment]
Sorry this wasn't answered earlier, I'll close this soon unless the problem persists and there's more information to assist

**Comment by JuditKnoll** [comment]
Since there wasn't any more information provided, I'll close this issue. Feel free to reopen if it is still relevant, and please provide some additional information (e.g. the plugin version).
