### ISSUE TITLE
SpotBugs on Wikipedia is being redirected to Findbugs

### ISSUE THREAD

**Issue by henrik242** [spotbugs/spotbugs#1565]
https://en.wikipedia.org/wiki/SpotBugs is just a redirect to FindBugs. That doesn't seem right :)

**Comment by ThrawnCA** [comment]
Well, SpotBugs does get a mention in the page.

**Comment by KengoTODA** [comment]
I revert the redirect setting, see https://en.wikipedia.org/w/index.php?title=SpotBugs&type=revision&diff=1030127504&oldid=890653997 for detail.

**Comment by KengoTODA** [comment]
Again the [page is redirected to FindBugs](https://en.wikipedia.org/w/index.php?title=SpotBugs&diff=prev&oldid=1030138188). I will use the talk page to discuss.

**Comment by KengoTODA** [comment]
working at https://en.wikipedia.org/wiki/Talk:SpotBugs

**Comment by KengoTODA** [comment]
memo: https://en.wikipedia.org/wiki/Wikipedia:Notability_(software)

**Comment by hazendaz** [comment]
closing as wikipedia isn't part of this project anyways and anyone could be constantly changing it.  is that not the point of wikipedia.  it mentions spotbugs that is good enough and anyone looking at findbugs needs to come into this decade.  Most of the maven plugins for that matter pointed over and even got many archived.  Not sure what other value this serves here.
