### ISSUE TITLE
Snyk reports spotbugs-annotations' license as a warning:

### ISSUE THREAD

**Issue by hestad** [spotbugs/spotbugs#1589]
✗ LGPL-2.1 license (new) [Medium Severity][https://snyk.io/vuln/snyk:lic:maven:com.github.spotbugs:spotbugs-annotations:LGPL-2.1] in com.github.spotbugs:spotbugs-annotations@4.1.2
    introduced by com.opentable.components:otj-pg-embedded@0.13.4 > com.github.spotbugs:spotbugs-annotations@4.1.2

Would it be possible to change it or dual license it as e.g. Apache 2.0 / MIT?

(this is not a real issue in my case, since I can just exclude the spotbugs-annotation. I started an issue with otj-pg-embedded as well.)

**Comment by iloveeclipse** [comment]
I'm not a lawyer, but I believe to change the license an approval from all contributors to the code in question is needed. Since none of original contributors of this code are active anymore, I don't know how that could be done.

**Comment by ThrawnCA** [comment]
I'm pretty sure that using the LGPL is only a problem for projects that can't actually comply with the licence (which would apply to many of Snyk's customers, but I don't see it being an issue for SpotBugs).

**Comment by KengoTODA** [comment]
@hestad One more idea, is that, excluding the annotation artifact from your distribution.
[Java doesn't need annotations in runtime](https://stackoverflow.com/a/3568041), so [you can safely exclude annotation libraries](https://stackoverflow.com/a/26868773) by using `<scope>provided</scope>` for Maven, or [`compileOnly` configuration](https://blog.gradle.org/introducing-compile-only-dependencies) for Gradle.

**Comment by KengoTODA** [comment]
In my understanding, it's nearly impossible to relicensing SpotBugs and relatives, since copyright owner does not respond actively.

**Comment by hestad** [comment]
@KengoTODA Yes, as I can just exclude the artifact this is a none issue in our case. And it sounds like a nightmare contacting all the contributors and get them to approve. Sounds like a "locked" situation. Just for thoughts, is it possible to dual license all commits from a given date? I guess it wouldn't make much difference in this case.

**Comment by KengoTODA** [comment]
> Just for thoughts, is it possible to dual license all commits from a given date? I guess it wouldn't make much difference in this case.

It's impossible in my understanding. :sob:

Not a direct solution, but there is [an activity to create standard Java annotations for static analysis](https://jspecify.dev/) under the [Apache License version 2](https://github.com/jspecify/jspecify/blob/93bda34ee5653830c6f5a21de1f9c5b07bd72258/LICENSE). When it becomes stable in the future, you can safely replace `spotbugs-annotations` with it. Not sure when it comes true, but SpotBugs is also a member of this activity, so we'll try to provide detectors that work with this standard.
