### ISSUE TITLE
what's the meaning of startBytecode & endBytecode in XML file

### ISSUE THREAD

**Issue by zesiar0** [spotbugs/spotbugs#1620]
I find two variables(**startBytecode** and **endBytecode**) in output XML file.

But i don't know the meaning of the two variables, someone can help me. Thanks!

**Comment by KengoTODA** [comment]
It's about the offset of bytecode, you may refer to the code around:

https://github.com/spotbugs/spotbugs/blob/51e586bed98393e53559a38c1f9bd15f54514efa/spotbugs/src/main/java/edu/umd/cs/findbugs/SourceLineAnnotation.java#L138-L141
