### ISSUE TITLE
Feature Request : Allow fail at end of scan

### ISSUE THREAD

**Issue by nayangoel** [spotbugs/spotbugs#1624]
Hi, I am using SpotBugs for SCA as a part of build pipeline. 

It would be great to have a feature where SpotBugs scans and waits for the build to finish before failing it. Rather than failing the build at the first occurrence of the finding. Because if there are more than one findings, developers have to build the code multiple times as issues are flagged one after another. 

It would be nice if SpotBugs had a feature where it would make a note of all the issues and report it at the end of the build and fail it if there were any issues found. That way the developers won't have to build it multiple times only having to find another issue being reported. Could save a ton of time.

I am not sure if this is already possible. I could not find it in the documentation.

Thanks!

**Comment by KengoTODA** [comment]
I think it's SpotBugs' default behavior. SpotBugs analyses all target class files and create a report for all of them.

Could you share your detailed scenario? It's also nice to have a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) then we can reproduce your problem in local.

**Comment by ThrawnCA** [comment]
You can certainly use SpotBugs to create a report. For example, using the Maven plugin, you would simply need to run `spotbugs:spotbugs` (and then possibly `spotbugs:gui`) instead of `spotbugs:check`.

**Comment by iloveeclipse** [comment]
Closing as we are not responsible how the tool is integrated in custom pipelines or workflows.
