### ISSUE TITLE
Consider removing DP_DO_INSIDE_DO_PRIVILEGED in light of Java 17's deprecation of SecurityManager

### ISSUE THREAD

**Issue by vitalyd** [spotbugs/spotbugs#1626]
Java 17 is deprecating (for removal) `SecurityManager` and related types, including `AccessController`.  See the [JEP](https://openjdk.java.net/jeps/411) and Java 17 EA [deprecation list](https://download.java.net/java/early_access/jdk17/docs/api/deprecated-list.html).

It might be a good idea to start thinking about removing this check, or perhaps excluding it when analyzing jdk17-targeted bytecode.

**Comment by ThrawnCA** [comment]
This is a duplicate of #1515

**Comment by vitalyd** [comment]
Thanks @ThrawnCA.  I searched before posting but clearly failed.
