### ISSUE TITLE
The `runFull` / `run_at_full_build` flag doesn't behave correctly.

### ISSUE THREAD

**Issue by nkavian** [spotbugs/spotbugs#1675]
**Context**

The project level settings for `also on full build` are reset to false each time I press alt-f5 and refresh the project

![image](https://user-images.githubusercontent.com/1127421/131550626-f0da6f48-ba87-4595-9684-7663cfd34e93.png)

It's expected that the project level `run_at_full_build` should not reset back to default.

Using Eclipse 4.20.0 with the latest spotbugs eclipse plugin.

**More Details**

Although there is no Eclipse level check box for `run_at_full_build` the setting does exist in the workspace preference file `com.github.spotbugs.plugin.eclipse.prefs`.

If I set the default there to `true`, then the above behavior is reversed. i.e. clear the checkbox in the project, press alt-f5, and observe the project will reset the setting back to true.

**Comment by Hojoe42** [comment]
Alt +F5 updates the Eclipse project settings from the Maven configuration. I assume that the m2e-code-quality Maven plugin is doing the update. @nkavian are you using this plugin?
The code on https://github.com/m2e-code-quality/m2e-code-quality/blob/9f2f2a4d0511574b772e58a197ff6ca9df08b098/com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/EclipseSpotbugsProjectConfigurator.java#L110 performs this update.
I think that is a problem for the m2e-code-quality plugin.

**Comment by hazendaz** [comment]
I believe back around that time the code quality checks were not frequently updated but that is long since not the case.  They are now updated frequently.  If this was related to that I'd say use latest and make sure it's the spotbugs copy not findbugs. If the later still exists.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nkavian** [comment]
Closing since this issue is very old and I can't retest (upgrading everything is prohibitive and time consuming).
