### ISSUE TITLE
spotbugs compatibility issue with NashornEngine with  jdk 11

### ISSUE THREAD

**Issue by kumarjitendra** [spotbugs/spotbugs#1682]
Hi ,

My project was working fine with jdk 1.8 but it has  compileKotlin FAILED when updated with jdk11 .

Details : Error caused due to incompatibility issue with Nashorn Engine . 

'' import jdk.nashorn.internal.objects.**NativeRegExp**.source "

NativeRegExp has become red in my project when I updated to jdk 11.

Termianl  message  :
Symbol is declared in module 'jdk.scripting.nashorn' which does not export package 'jdk.nashorn.internal.objects'

For your reference : Nashrone engine release notes for jdk 11
https://github.com/openjdk/nashorn

Thanks 
Jitendra

**Comment by KengoTODA** [comment]
It seems that this isn't SpotBugs' issue. SpotBugs does not depends on Nashorn.

And the error message means that you should not depend on internal classes that aren't exported by Nashorn. Please consider to stop depending on internal APIs.

**Comment by kumarjitendra** [comment]
I agree with you that I may be wrong and I didn’t understand the root cause of my problem. 

My objective is to set source  of  below  code .
  source(sourceSets.map { it.javaDirectories }.flatten()) 
    above code working fine with jdk 1.8 but when I changed to jdk 11 then   
    Task :quality-tools:compileKotlin FAILED
The `kotlin-dsl` plugin applied to project ':quality-tools' enables experimental Kotlin compiler features.  
My import inside Kotlin file :
“import jdk.nashorn.internal.objects.NativeRegExp.source “

Console error : Symbol is declared in module 'jdk.scripting.nashorn' which does not export package 'jdk.nashorn.internal.objects'


My code inside same Kotlin file:
source(sourceSets.map { it.javaDirectories }.flatten()) 

Console error :Symbol is declared in module 'jdk.scripting.nashorn' which does not export package 'jdk.nashorn.internal.objects'
 
Build  scan for your reference :
https://gradle.com/s/neicp3tzhs3yo  #TODO
-  If symbol is declared in module ‘jdk.scripting.nashorn' then how can I export package jdk.nashorn.internal.objects' in jdk 11 or any alternative to set source as I mentioned above ? 

I found this link when I investigated further .
 https://docs.oracle.com/javase/9/docs/api/jdk.scripting.nashorn-summary.html

 Thanks
