### ISSUE TITLE
BigDecimal is reported as mutable

### ISSUE THREAD

**Issue by GandalfTheWhite80** [spotbugs/spotbugs#1685]
Setting or getting an "BigDecimal" is reported as

```
Rank: Of Concern (18), confidence: Normal
Pattern: EI_EXPOSE_REP 
Type: EI, Category: MALICIOUS_CODE (Malicious code vulnerability)
```

or
```
Rank: Of Concern (18), confidence: Normal
Pattern: EI_EXPOSE_REP2 
Type: EI2, Category: MALICIOUS_CODE (Malicious code vulnerability)
```

BigInteger is in your https://github.com/spotbugs/spotbugs/blob/master/spotbugs/src/main/java/edu/umd/cs/findbugs/util/MutableClasses.java but not BigDecimal? Mistake or is it really mutable?

**Comment by GandalfTheWhite80** [comment]
PS Perhaps a type? Form your class file `"java.math.Decimal"` -> my java.math does not contain java.math.Decimal only BigDecimal.

**Comment by ThrawnCA** [comment]
This should be handled by https://github.com/spotbugs/spotbugs/pull/1677/files

**Comment by GandalfTheWhite80** [comment]
Installed latest Build - works fine after #1677
