### ISSUE TITLE
Support com.google.errorprone.annotations.Immutable

### ISSUE THREAD

**Issue by jimbentler** [spotbugs/spotbugs#1691]
Error Prone is somewhat of a replacement for SpotBugs, except that it doesn't work in Eclipse.  Anyway, its annotations are now used by and required by Guava for (warning-less) builds.

Therefore, it makes sense to add support for the Error Prone annotations that map easily to existing checked annotations, such as net.jcip.annotations.Immutable.  To support it properly, I suppose you'd also have to either check the containerOf field or just ignore when non-empty.

A similar case is com.google.errorprone.annotations.concurrent.GuardedBy, which should map directly to net.jcip.annotations.GuardedBy.

**Comment by KengoTODA** [comment]
Duplicate of #1676
