### ISSUE TITLE
Inconsistency between CLI and Eclipse plugin: JRE should be Discovered.IN_SYSTEM_CLASSPATH

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#171]
Hi,

I am currently writing a FindBugs/SpotBugs detector based on the [WALA static analysis library](http://wala.sourceforge.net/wiki/index.php/Main_Page), as the analysis I envision needs more static analyses power than BCEL + FindBugs can provide out-of-the-box. So far, this has been working surprisingly well; the core of FindBugs/SpotBugs is a lot less tied to BCEL or ASM than I initially feared (`Detector2` 👍 ).

There is one **issue**, however: As WALA explicitly models the Java class loader hierarchy, I need to know which `ICodeBase`s are part of the JRE. When my detector is run via the command-line or the `findbugs-maven-plugin`, I can use `Discovered.IN_SYSTEM_PATH` to accurately determine which `ICodeBase`s should be assigned to the primordial class loader. But the Eclipse plug-in simply claims that all JARs on the class path `Discovered.SPECIFIED`; it does not treat the Eclipse *JRE System Library* container different.

This inconsistency seems like a bug to me. (Admittedly, it’s an inconsistency most analyses don’t care about, but for WALA-based analyses it really makes a difference.)

**Comment by iloveeclipse** [comment]
I have not checked the code yet (where is Discovered.IN_SYSTEM_PATH ???), but in Eclipse we can have multiple target JRE's, and so I guess we specify JRE differently as the CLI version (which probably uses the current one to load classes). Also Eclipse plugin is differently loaded because Eclipse separates plugins by class loaders magic.

**Comment by sewe** [comment]
FYI, `Discovered` is a nested enum in `ICodeBase`.

> Also Eclipse plugin is differently loaded because Eclipse separates plugins by class loaders magic.

I know, but I am not talking about the JRE than my plugin runs with, but about the classpath of the project SpotBugs *analyses*. You know, which JARs are part of the application, which are on the auxiliary classpath, etc. Basically, what Eclipse displays in its *Java Build Path* dialog. I hope this clarifies things.

**Comment by sewe** [comment]
FWIW, there are a few further inconsistencies between the `ICodeBase`s created by the Standalone application (`bin/fb analyze`) and by the (FindBugs 3.0.2) Eclipse plugin.

Dependency | Standalone application | Eclipse plugin
-|-|-
`jre/lib/rt.jar` | `IN_SYSTEM_CLASSPATH` | `SPECIFIED`
`jre/lib/*.jar` (other than `rt.jar`) | `IN_SYSTEM_CLASSPATH` | not in classpath!
`jre/lib/ext/*.jar` | `IN_SYSTEM_CLASSPATH` | not in classpath!
`annotations.jar` | `IN_SYSTEM_CLASSPATH` | `IN_SYSTEM_CLASSPATH`
`jsr305.jar` | `IN_SYSTEM_CLASSPATH` | `IN_SYSTEM_CLASSPATH`

IMHO, the standalone application got things right. In particular, that JARs like `jre/lib/jce.jar` are not on the classpath seems like bug as well.

**Comment by sewe** [comment]
I’ve come to believe that the SpotBugs Eclipse plugins is actually acting according to spec when using `Discovered.SPECIFIED`; like `Discovered.NESTED`, `Discovered.IN_SYSTEM_CLASSPATH` is meant to signify that the codebase has been added implicitly.

In fact, [`ClassPathBuilder`]( https://github.com/spotbugs/spotbugs/blob/fe8a8d66e97d3ae0b830731461aab0f8b39791f6/spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/impl/ClassPathBuilder.java#L314) specifically handles the case that `java.lang.Object` is already contained in the specified codebases and then refrains from adding the system class path.

So, from my point of view, we can close this issue.
