### ISSUE TITLE
Eclipse Spotbugs Marketplace points to dead link 

### ISSUE THREAD

**Issue by vogella** [spotbugs/spotbugs#1721]
https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin/ points to a dead "findbugs" page on  Andreys page.

http://andrei.gmxhome.de/findbugs/index.html 

Can you update or remove the link?

**Comment by vogella** [comment]
cc @iloveeclipse

**Comment by iloveeclipse** [comment]
I've changed the link, my provider simply shut down my site.
