### ISSUE TITLE
Add licence file

### ISSUE THREAD

**Issue by vogella** [spotbugs/spotbugs#174]
I do not see a license file in the root folder of your project. Could you add it?

**Comment by KengoTODA** [comment]
Thanks for issueing, SpotBugs has it at https://github.com/spotbugs/spotbugs/blob/master/spotbugs/licenses/LICENSE.txt

**Comment by iloveeclipse** [comment]
Hi Kendo,
I'm not sure if this is the right way to handle the request.
The license should be referenced on the first project site.
Even as a developer in the project I would not find the linked file.
We should mention the license type in README and probably just copy it into the root of the project.
