### ISSUE TITLE
Signature check fail during Eclipse plugins install with Eclipse Oomph

### ISSUE THREAD

**Issue by nosf3rat** [spotbugs/spotbugs#1754]
Hello!

We use SpotBugs Elipcse plugins
And in latest updates there is a problem during Eclipse plugins install with Eclipse Oomph framework (or Eclipse Installer)
Seems like there may be a problem with plugins signature

Signature verify error is next:
[oomph.txt](https://github.com/spotbugs/spotbugs/files/7339943/oomph.txt)

**Comment by nosf3rat** [comment]
> Are you sure that C:\Users\User\AppData\Local\Temp\signatureFile14644218132261097048.jar is a spotbugs related file?

Yes, I'm sure, it's SpotBugs feature file donwloaded and introspected by Eclipse Oomph
I'm attaching this file here (on another reproduction)

> If possible, share a mcve procedure to help others to reproduce

Sorry, I'm not sure it's possible :( It's inside Eclipse Oomph setup configuration
We use Eclipse Version: 2020-12 (4.18) and Java is:
```
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment (build 11.0.9+12-LTS)
OpenJDK 64-Bit Server VM (build 11.0.9+12-LTS, mixed mode)
```

I debugged problem and seems like it's something wrong with SpotBugs Eclipse plug-ins / features signature..

**Comment by eperret** [comment]
I just ran into the same issue using Eclipse 4.18 on Mac.

**Comment by NickLodewijks** [comment]
Same issue when trying to update to 4.5.2 to mitigate the Log4J issue, with Eclipse 2019-06 + Windows 10.

**Comment by iloveeclipse** [comment]
Looks like there is a fixed Eclipse bug for the first report (that contains stack trace): https://bugs.eclipse.org/bugs/show_bug.cgi?id=572034

All others: please consider to report the error to Eclipse bug tracker *if* you still see it with *latest* Eclipse 4.22.
