### ISSUE TITLE
Clarify backwards compatibility with existing FindBugs integrations

### ISSUE THREAD

**Issue by VsevolodGolovanov** [spotbugs/spotbugs#177]
The website mentions findbugs-maven-plugin, so I assume the goal is to keep compatibility. Maybe this could be stated explicitly?

We rely on Maven and TeamCity integrations and need to know where SpotBugs stands in regards to this.

**Comment by KengoTODA** [comment]
At least, version 3.1.0 will provide the same features as FindBugs.

* https://github.com/spotbugs/spotbugs/milestone/1

**Comment by iloveeclipse** [comment]
Compatibility means here what? Maven, Eclipse and gradle plugins will have different ids, so if you use "findbugs" integration, you will need an update of your toolchain. 

If you have developed your own detectors and want to be sure that FindBugs API will remain stable in SpotBugs, you are welcome to provide test cases. We do not want to break anyone but without tests there is no guarantee. 

If you had Eclipse plugins based on FindBugs API, you should be aware that the plugin id is changed, so you shojld avoid using require-bundle but use import package instead. Same as above applies also here: tests are welcome.

**Comment by VsevolodGolovanov** [comment]
@iloveeclipse, I see. Those integrations should be easily adaptable. But what about TeamCity? It works by parsing the findbugs reports. Will the findbugsXml.xml/findbugs.xml formats stay the same? TeamCity is proprietary software, it can't be easily adapted.

**Comment by iloveeclipse** [comment]
The report structure / xml element names are not changed and we don't plan to change them just because of the project name change. Here same rule applies as for API: if you contribute tests, you will be sure the formats will stay compatible.
