### ISSUE TITLE
False positive for MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR in final class?

### ISSUE THREAD

**Issue by danielnorberg** [spotbugs/spotbugs#1812]
Spotbugs 4.5.0 yields a warning for `MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR` when calling an inherited method from the constructor in a final class. But the method cannot be overridden by a subclass when the class is final. 

See repro: https://github.com/danielnorberg/spotbugs-falsepositives/blob/main/src/main/java/Repro_FalsePositive_MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR.java

I propose that spotbug should **not** yield `MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR` when the class is final, same as when the called method itself is final.

**Comment by danielnorberg** [comment]
Looking at the implementation of this check, there's no need for inheritance to trigger this false positive. Calling any method in a final class from the constructor yields `MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR`.

See repro https://github.com/danielnorberg/spotbugs-falsepositives/blob/main/src/main/java/Repro2_FalsePositive_MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR.java

**Comment by KengoTODA** [comment]
closed by #1813
