### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by DoubleImpetus** [spotbugs/spotbugs#1815]
When I detect the String concat (ex: str1 = str2+str3),the second var,str1,will be to assign value to equel the first var just without "toString" in Local variables of TaintFrame.

**Comment by KengoTODA** [comment]
I do not understand what you mean, consider providing a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the bug you mentioned.

**Comment by gtoison** [comment]
I'll close this stale issue, it's unclear what was the question
