### ISSUE TITLE
Failed to build under windows

### ISSUE THREAD

**Issue by JKing188** [spotbugs/spotbugs#1889]
Failed to build with gradle6.5 in windows, the dependency cannot be down, please help to check it, thank you
![image](https://user-images.githubusercontent.com/83318215/147057583-b3f62772-d8f2-40c6-b62d-8ca6dc2f8410.png)
![image](https://user-images.githubusercontent.com/83318215/147057817-a756e104-389f-4745-912c-93e5ce8bcd0f.png)

**Comment by KengoTODA** [comment]
Could you have a try not with your Gradle 6.5 but with the Gradle wrapper in the project root dir?
For instance `gradlew.bat build`.

This error message seems strange, it says we should give `AbstractArchiveTask` but actually we give `TaskProvider<Zip>` and the [`Zip` task extends `AbstractArchiveTask`](https://docs.gradle.org/6.5/javadoc/org/gradle/api/tasks/bundling/Zip.html).

**Comment by JKing188** [comment]
Thank you for your reply. The gradlew.bat in the execution project can be compiled successfully, but the gradlew.bat build cannot be packaged
![image](https://user-images.githubusercontent.com/83318215/147213443-ecc762c8-6f11-436d-9ef6-b8d2341343a1.png)

**Comment by JKing188** [comment]
Thank you for your reply. The gradlew.bat in the execution project can be compiled successfully, but the gradlew.bat build cannot be packaged

> Could you have a try not with your Gradle 6.5 but with the Gr

**Comment by JKing188** [comment]
The gradlew.bat in the execution project can be compiled successfully, but the gradlew.bat build cannot be packaged
![image](https://user-images.githubusercontent.com/83318215/147215786-4cb6b5c5-3923-4a36-a1e4-7b40230549e1.png)

**Comment by KengoTODA** [comment]
You need Java 17 on `JAVA_HOME` to build SpotBugs.

Or update your branch to the latest commit (24a56b5), then Gradle will download the latest JDK 17 automatically.

**Comment by JKing188** [comment]
![image](https://user-images.githubusercontent.com/83318215/147331861-65b2930d-5d55-41ad-a71d-a89d77d79e4b.png)
When I pack with jdk11 or 17, this error will be reported. When using jdk8 to package, although it will report an error, you can type out a package, but it won’t work. The version of spotbugs I use is 4.3.0. So which jdk version should be used for packaging, I can't understand.

**Comment by KengoTODA** [comment]
> The version of spotbugs I use is 4.3.0.

Let me confirm what you mean. Do you want to build the SpotBugs 4.3.0 (0dfbd8166ebe6c9e66614650d65d06f29fa46e96)? Run `git log` to confirm the commit you checked out.

And what is the reason to build so old version? Basically it is better to build the latest version, which provides more stability and productivity.

**Comment by JKing188** [comment]
Thank you for your reply. It has been successfully compiled and packaged. Previously, it was not possible to package because my friend changed the code to adapt to jdk8. It was not completely changed. Now after switching to jdk11, it can be compiled and packaged normally, which will cause you troubles. Expressed deep apologies.
