### ISSUE TITLE
9.2.1 "all" jar file missing?

### ISSUE THREAD

**Issue by eant60** [spotbugs/spotbugs#1895]
I cannot find the "all" version of the 9.2.1 jar file ( presumably checkstyle-9.2.1-all.jar) in the GitHub releases page or Maven central repository.  Can this be made available?

(I use checkstyle for my tiny/personal projects.  This version of the jar with the dependencies already included is greatly appreciated.)

**Comment by KengoTODA** [comment]
please ask at https://github.com/checkstyle/checkstyle
