### ISSUE TITLE
Run sonar analysis at continuous integration

### ISSUE THREAD

**Issue by kzaikin** [spotbugs/spotbugs#190]
https://sonarqube.com/projects is free for open-source project analysis.
We should run sonar analyzer at CI build to see the project code measures like code coverage and code complexity etc

**Comment by KengoTODA** [comment]
Could you introduce how to register SpotBugs to that page? I've googled but couldn't find related web sites...

**Comment by KengoTODA** [comment]
I'm making a project, but haven't run analysis yet.
https://sonarcloud.io/dashboard?id=com.github.spotbugs.spotbugs

**Comment by KengoTODA** [comment]
`sonarqube` Gradle plugin v2.2 failed with following message:

```
:sonarqube FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> SonarQube is unable to analyze file : '/Users/kengo/Documents/github/spotbugs/spotbugsTestCases/src/java/sfBugs/Bug3460132.java'
```

It might be because of invalid our package name (sfBugs), better to replace with `sf_bugs` or `sfbugs`.

**Comment by kzaikin** [comment]
I was able to analyse spotbugs at my local instance of sonarqube.
I will make a PR with gradle setup necessary for sonar analysis

**Comment by kzaikin** [comment]
Umm. sonarcloud.io is a cool thing, but they have SonarAnalyzer only.
It would be a good thing to analyze spotbugs with any static analyzer but it'd be even better to have it analyze itself.
We have to check for sonarqube instances which are open for plugins installation to have both SonarAnalyzer and Spotbugs analysis results
