### ISSUE TITLE
experimental bug included when extract xml result although excluded in the setting/preferences

### ISSUE THREAD

**Issue by rzlification** [spotbugs/spotbugs#1900]
![image](https://user-images.githubusercontent.com/16426302/148000831-bdef7d7e-ae8c-41c9-9fee-75a04d41ab6d.png)
**spotbug version**

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/16426302/148001417-4e41e985-d2b8-4e60-a508-ee57b3ab3d10.png)
**spotbug setting**

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/16426302/148002807-eb99b454-4c3f-4916-b495-fd3f4f66fe86.png)
**output bug in eclipse with the setting**

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/16426302/148002532-b5946685-9151-418b-8c55-0b89f3041d2b.png)
**output after extract to xml and convert to csv.**

based on the 3rd and 4th screenshot, when extract to xml, it will include the experimental bug eventhough it is excluded in the setting/preferences

**Comment by gtoison** [comment]
I suspect that the Eclipse plugin runs a full analysis ignoring if 'experimental' is enabled or not and then only shows relevant bugs in Eclipse
By the way the version you seem to be using (3.1.13) is quite old
