### ISSUE TITLE
False positive on NM_CLASS_NAMING_CONVENTION

### ISSUE THREAD

**Issue by vipulshah2010** [spotbugs/spotbugs#1947]
Hi,
I found a false positive on NM_CLASS_NAMING_CONVENTION when using SpotBugs to analyze my project.

We do have all our filenames starting with capital letters but still, we do receive this warning

spotbugsToolVersion = "4.2.1"
spotbugsGradlePluginVersion = "4.6.2"

<img width="723" alt="image" src="https://user-images.githubusercontent.com/1704940/152772707-5b4c1805-4540-44ff-b5d1-53a8132ebca5.png">

**Comment by ThrawnCA** [comment]
It's not the filename that it's complaining about, but the class name. What is the class name?

**Comment by KengoTODA** [comment]
no response for a month, then I will close this stale issue.
