### ISSUE TITLE
analyzeFromFile a.jar Code line number shows unknown

### ISSUE THREAD

**Issue by chongbo2013** [spotbugs/spotbugs#1979]
./spotbugs -textui -low -html -output result_x.xml -analyzeFromFile beelottieplayer_dex.jar -pluginList fb-contrib-7.4.7.jar -progress -longBugCodes

Value contained in com.mobile.player.LottieParams.marsRuntimeModel at <Unknown>Known null at <Unknown>

<br class="Apple-interchange-newline">

**Comment by KengoTODA** [comment]
@chongbo2013 could you confirm that the class file `LottieParams.class` in the jar file really has the line number info?
You can share the class file itself, or the result of `javap` command like below:

```command
$ ls com/mobile/player/LottieParams // to confirm that the target class file exists
$ javap -v com.mobile.player.LottieParams
```

**Comment by chongbo2013** [comment]
[classes8-dex2jar.jar.zip](https://github.com/spotbugs/spotbugs/files/8249929/classes8-dex2jar.jar.zip)
![image](https://user-images.githubusercontent.com/3191545/158300887-30280f52-e2b7-4a8b-ba97-ac16eed8c9dd.png)

**Comment by chongbo2013** [comment]
This is an Android project, I will convert the dex in the apk to jar, and then analyze it

**Comment by KengoTODA** [comment]
Confirmed that the class file has no [`LineNumberTable` attribute](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.12). Then SpotBugs is working as expected, but the class file does not provide necessary information. To ensure that the class file has necessary attributes, [you need to compile with a specific compiler option](https://www.baeldung.com/java-unknown-source-stack-trace).

For me [the `pom.xml` of the fastjson project seems OK](https://github.com/alibaba/fastjson/blob/1.2.79/pom.xml). I also confirmed that [their official distribution v1.2.79](https://github.com/alibaba/fastjson/releases/tag/1.2.79) contains debug data as expected.

So I guess that your build tools removed such debug data in class files, to make distributions as small as possible for mobile use? If so you can solve this problem by running SpotBugs with the original fastjson library, that is NOT removed debug data in class files.
