### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#2008]
The certificate used to sign plugin is expired, see screenshot:
![image](https://user-images.githubusercontent.com/964108/162561880-784c046a-5e40-4774-8cce-555e2d7a5289.png)

**Comment by KengoTODA** [comment]
memo: refs #803

**Comment by iloveeclipse** [comment]
Regarding plugin signing with certificate (and expiration issue in 90 days) vs plugin signing, I've asked on platform mailing lists and got following answers /pointers : 

- https://www.eclipse.org/lists/platform-dev/msg03567.html 
- https://www.eclipse.org/lists/p2-dev/msg05946.html
- extension point to ship "trusted" key: https://bugs.eclipse.org/bugs/show_bug.cgi?id=577248
- very nice summary of current pgp state with further pointers: https://gitlab.eclipse.org/eclipse-wg/ide-wg/eclipseide.org/-/issues/11 

So it seems we could try to use pgp signing, but that seem to require tycho : https://www.eclipse.org/tycho/sitedocs/tycho-gpg-plugin/sign-p2-artifacts-mojo.html

**Comment by csanchezub** [comment]
Apparently the certificate has expired again
![image](https://github.com/spotbugs/spotbugs/assets/136069863/ac2e561e-0e14-4121-8b22-885675779ce9)
