### ISSUE TITLE
Can I get warning's column number by SpotBugs?

### ISSUE THREAD

**Issue by HuaienZhang** [spotbugs/spotbugs#2037]
Hi, I find that SpotBugs only provide the line number of each warning (BugInstance). Am I right? Could you tell me whether this tool can provide column numbers of bugs? Thanks.

**Comment by gtoison** [comment]
SpotBugs analyzes the compiled `.class` files. For each instruction they contain the line number but not the column number.
So it isn't possible to get the column from the `.class` file and report it to you

**Comment by HuaienZhang** [comment]
Thanks
