### ISSUE TITLE
NPE after updating to 4.7.0

### ISSUE THREAD

**Issue by gurpreetsingh85** [spotbugs/spotbugs#2041]
After updating to 4.7.0
All kotlin files analysis is failing with error. It is happening pretty much for each file

> using detector edu.umd.cs.findbugs.detect.FindPotentialSecurityCheckBasedOnUntrustedSource
    java.lang.NullPointerException: Cannot invoke "org.apache.bcel.classfile.LocalVariableTable.getLocalVariable(int, int)" because the return value of "org.apache.bcel.classfile.Method.getLocalVariableTable()" is null

**Comment by KengoTODA** [comment]
refs #2017

**Comment by KengoTODA** [comment]
@baloghadamsoftware Check this if you have time. Thanks in advance!

**Comment by baloghadamsoftware** [comment]
I do not know exactly the cause of the problem (actually, I cannot imagine how a local variable table could be missing if there are ALOAD* instructions) but I added a check for the existance of them. I tested it on some Kotlin code now and it seems that the issue is fixed. See #2054.

**Comment by gtoison** [comment]
This seems to be fixed by #2054
