### ISSUE TITLE
Stuck on textui after command, thread stuck

### ISSUE THREAD

**Issue by chongbo2013** [spotbugs/spotbugs#2059]
spotbugs -textui -high -xml:withMessages=report.xml -progress -analyzeFromFile fastjson-build-1.0.0.220415230733.jar -maxHeap 2048
Scanning archives (4553 / 5964)

**Comment by iloveeclipse** [comment]
Please attach jstack output for spotbugs process.

**Comment by chongbo2013** [comment]
what to do thanks

**Comment by KengoTODA** [comment]
You need to pass a text file to the `-analyzeFromFile` option, but you're now pass a jar file instead. Please check [official manual](https://spotbugs.readthedocs.io/en/stable/running.html) for detail.

**Comment by chongbo2013** [comment]
@KengoTODA  thanku, how should i specify the jar option

**Comment by KengoTODA** [comment]
check the [manual](https://spotbugs.readthedocs.io/en/stable/running.html)!
