### ISSUE TITLE
Decide which Eclipse version our eclipsePlugin supports

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#208]
We had related discussion in #205; It would be nice to stop supporting ancient release like Juno.
Maybe we can drop supports for Mars, Luna, Kepler, Juno and older releases?

- [x] Oxygen (release candidate) (4.7)
- [x] Neon (stable) (4.6)
- [ ] Mars (4.5) which starts new directory layout
- [ ] Luna (4.4)
- [ ] Kepler (4.3)
- [ ] Juno (4.2, 3.8)
- [ ] Previous to Juno (<=4.1)

Note that current SpotBugs Eclipse Plugin cannot be built with Neon.
If we update `.travis.yml` to build with supported Eclipse version, we may need to update our code.

```
\spotbugs\eclipsePlugin\src\de\tobject\findbugs\FindbugsPlugin.java:250: error: incompatible types: String cannot be converted to Plugin
        ResourcesPlugin.getWorkspace().addSaveParticipant(PLUGIN_ID, saveParticipant);
```

**Comment by iloveeclipse** [comment]
+1 for supporting 4.6 and later platforms *only*.

I can't see the problem with compilation in Eclipse Oxygen (4.7) for FindBugs (I still can't get SpotBugs setup to work), but the code is still same and neither SpotBugs code nor Eclipse interface (org.eclipse.core.resources.IWorkspace.addSaveParticipant(String, ISaveParticipant)) was changed. This method was *added* in 3.6, so probably you aren't using Neon.

**Comment by KengoTODA** [comment]
> probably you aren't using Neon.

Yes currently 3.6.2 is used for Travis CI. https://github.com/spotbugs/spotbugs/blob/3.1.0_RC2/.travis.yml#L24

**Comment by iloveeclipse** [comment]
Can we close this now?
The link to file would be https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.6.3-201703010400/eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz&r=1

**Comment by KengoTODA** [comment]
Ya, it seems that we got no comment, then let's make progress.
