### ISSUE TITLE
Compatibility with (and update for) existing FindBugs Eclipse plugin

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#209]
I just stumbled over the fact that the `edu.umd.cs.findbugs.plugin.eclipse.findbugsPlugins` extension point got renamed to `com.github.spotbugs.plugin.eclipse` (interestingly, while leaving the `<findbugsPlugin>` element name unchanged).

I hence wonder what compatibility guarantees towards existing FindBugs plugins are given by SpotBugs? Maybe we can use this issue to discuss/document this.

**Comment by kzaikin** [comment]
IMO it should be possible to replace findbugs with spotbugs reusing all existing goodnes like find-sec-bugs, fb-contrib etc. I don't see a reason to change public API for plugins

**Comment by sewe** [comment]
> IMO it should be possible to replace findbugs with spotbugs reusing all existing goodnes like find-sec-bugs, fb-contrib etc. I don't see a reason to change public API for plugins

Agreed. While the codebase could certainly use some clean-up, version 3.1.0 is probably not the time to do it.

In light of this, I think the `edu.umd.cs.findbugs.plugin.eclipse.findbugsPlugins` shouldn't have been renamed. If you agree, I will open a bug.

**Comment by iloveeclipse** [comment]
If we are talking aboud SpotBugs (not Eclipse) plugins, we should stay compatible. For SpotBugs Eclipse plugin, however, we can't stay compatible simply because we can run in Eclipse along with FindBugs Eclipse plugin and then our contributions would be partly overridden or broken by that. 
So in Eclipse plugin we can't keep compatibility because of the fork.
This is sad but this is unavoidable.

**Comment by sewe** [comment]
>  For SpotBugs Eclipse plugin, however, we can't stay compatible simply because we can run in Eclipse along with FindBugs Eclipse plugin and then our contributions would be partly overridden or broken by that.
So in Eclipse plugin we can't keep compatibility because of the fork.
This is sad but this is unavoidable.

Are you sure? It may be possible to [use `p2.inf`](https://dev.eclipse.org/mhonarc/lists/p2-dev/msg05503.html) to declare the `com.github.spotbugs.plugin.eclipse` as an update of both older versions of itself *and* of the `edu.umd.cs.findbugs.plugin.eclipse` feature. WDYT?

**Comment by iloveeclipse** [comment]
At least the extension points will use a namespace of the new plugin id, I do not see how we can make it without re-using the same plugin id for the new plugin, which is not what we want. Having them new but others old doesn't make sense.

The only way to be compatible is to use the old plugin id, but I guess this is not possible to have two marketplace entries with same plugin id, and we want to share the plugin on marketplace.

**Comment by sewe** [comment]
> At least the extension points will use a namespace of the new plugin id, I do not see how we can make it without re-using the same plugin id for the new plugin, which is not what we want. Having them new but others old doesn't make sense.

AFAIK, the extension point ID does not have to be derived from the plugin ID; Eclipse will only prepend the plugin ID if the point ID does not have a dot in it. So it would be possible to re-use the old extension point IDs (`edu.umd.cs.findbugs.plugin.eclipse.findbugsPlugins` and `edu.umd.cs.findbugs.plugin.eclipse.findbugsQuickFixes`).

**Comment by iloveeclipse** [comment]
I've just tried to add full qualified name to the extension point id, the PDE editor creates a warning  that the id should not contain dots and an error at the place where we are using our own extension point.

**Comment by sewe** [comment]
> I've just tried to add full qualified name to the extension point id, the PDE editor creates a warning that the id should not contain dots and an error at the place where we are using our own extension point.

AFAICT, you need to change the ID in *several* places.

First, the [`plugin.xml`](https://github.com/spotbugs/spotbugs/blob/3512a51ab6cb32a5a341cb27cf4572ebb551c467/eclipsePlugin/plugin.xml#L4) needs to reference the fully-qualified extension point ID:

    <extension-point id="edu.umd.cs.findbugs.plugin.eclipse.findbugsPlugins" name="Custom SpotBugs detector plugins" schema="schema/detectorPlugins.exsd"/>
    <extension-point id="edu.umd.cs.findbugs.plugin.eclipse.findbugsQuickFixes" name="Custom SpotBugs quick fixes" schema="schema/findbugsQuickFixes.exsd"/>

Second, the [`.exsd` files](https://github.com/spotbugs/spotbugs/blob/3512a51ab6cb32a5a341cb27cf4572ebb551c467/eclipsePlugin/schema/detectorPlugins.exsd#L6) needs the fully qualified ID as well:

    <meta.schema plugin="com.github.spotbugs.plugin.eclipse" id="edu.umd.cs.findbugs.plugin.eclipse.findbugsPlugins" name="Custom SpotBugs plugins"/>

(If I make *both* these changes, then the PDE (Neon) editor doesn’t show an error for me.)

Finally, you’ll need to pass the correct extension ID to `IExtensionRegistry.getConfigurationElementsFor(String)`, of course.

Should I prepare a pull request?

**Comment by iloveeclipse** [comment]
Yes. Would be nice if you could also check other not qualified contributions.

**Comment by sewe** [comment]
> Yes. Would be nice if you could also check other not qualified contributions.

Will do.

**Comment by sewe** [comment]
The above commit (2bc53be) does **not** seem work. Moreover, under Oxygen I do get a warning in the `plugin.xml` editor:

> Illegal value 'edu.umd.cs.findbugs.plugin.eclipse.findbugsPlugins' for attribute "id".  Legal characters are "a-z", "A-Z", "0-9", and "_"

I also get an error:

> Unknown extension point: 'edu.umd.cs.findbugs.plugin.eclipse.findbugsQuickFixes'

Interestingly, I get neither warning nor error under Neon.

Will need to investigate whether keeping the extension point IDs compatible with FindBugs is possible at all.

**Comment by iloveeclipse** [comment]
Exact same things as I had, and I was also on Oxygen, so it can be a bug or a bugfix in 4.7, depending on what the specs say.

**Comment by sewe** [comment]
> Exact same things as I had, and I was also on Oxygen, so it can be a bug or a bugfix in 4.7, depending on what the specs say.

Apparently, the spec says different things in different versions. When changing the header of the `plugin.xml` from

    <?eclipse version="3.0"?>

to

    <?eclipse version="3.4"?>

the error and warning vanishes.

**Comment by sewe** [comment]
> When changing the header of the plugin.xml from [...]

That did the trick. Interestingly, this `eclipse` processing instruction not only changes the behavior of the `plugin.xml` editor but also affects the runtime behavior. Now the `edu.umd.cs.findbugs.plugin.eclipse.findbugsPlugins` and `edu.umd.cs.findbugs.plugin.eclipse.findbugsQuickFixes` extensions are found just fine.

**Comment by iloveeclipse** [comment]
>  It may be possible to [use `p2.inf`](https://dev.eclipse.org/mhonarc/lists/p2-dev/msg05503.html) to declare the `com.github.spotbugs.plugin.eclipse` as an update of both older versions of itself *and* of the `edu.umd.cs.findbugs.plugin.eclipse` feature. WDYT?

@sewe , can you provide a patch for it? Now that we merged your id PR we will definitly run into troubles if both plugins will co-exist. So we must make sure SpotBugs feature, once installed, obsoletes FindBugs. A bonus point if p2 can somehow offer the SpotBugs as an update to FindBugs, but I have no idea how we can achieve also that.

**Comment by sewe** [comment]
>@sewe , can you provide a patch for it? Now that we merged your id PR we will definitly run into troubles if both plugins will co-exist. So we must make sure SpotBugs feature, once installed, obsoletes FindBugs. A bonus point if p2 can somehow offer the SpotBugs as an update to FindBugs, but I have no idea how we can achieve also that.

@iloveeclipse I know how to achieve this with `p2.inf` and Maven/Tycho, but have need to figure out how to achieve this with the current Gradle build. Will do some digging.

BTW, the “bonus point” is achievable; I’ve done this before with a Tycho-based build.

**Comment by iloveeclipse** [comment]
@sewe : the gradle thing is easy: see https://github.com/iloveeclipse/spotbugs/commit/9d1ccb3c560c4bf4b3649ce1f086cdf2dcb938ea

**Comment by iloveeclipse** [comment]
Would be really cool to have it in 3.1.0 soon, so that everyone using findbugs plugin could simply update to the spotbugs one.

**Comment by sewe** [comment]
> @sewe : the gradle thing is easy: see iloveeclipse/spotbugs@9d1ccb3

@iloveeclipse Slightly less easy than that, as the `p2.inf` file needs to go into the **feature** rather than the **plugin** and the Gradle build has for some reason three tasks (`featureJar`, `featureCandidateJar`, and `featureDailyJar`). But I’ll manage – although I vastly prefer the more convention-over-configuration approach of Maven/Tycho to the build **scripts** of Gradle.

Now I just need to wrap my head around [p2ql expressions](https://dev.eclipse.org/mhonarc/lists/p2-dev/msg05503.html) and test all the different update paths.

**Comment by sewe** [comment]
Change sewe/spotbugs@9f25705 doesn’t quite work yet. It updates FindBugs to SpotBugs automatically (using *Check for Updates*), but doesn’t automatically update older versions of SpotBugs itself. Haven’t figured out why yet. When I install the feature manually again, Eclipse recognizes it as an update. Weird.

**Comment by sewe** [comment]
For the record, I [asked on the p2-dev mailing list](https://dev.eclipse.org/mhonarc/lists/p2-dev/msg05698.html) about this. Maybe they can help me out here.

**Comment by iloveeclipse** [comment]
Andreas, what if the update FB to SB works but then it never updates SB because p2 thinks the update is already done? May be FB needs to be *uninstalled*? Is this possible via advices? Have you tried to update SB to SB without updating FB first (the case where FB was not installed at all)?

**Comment by sewe** [comment]
> Andreas, what if the update FB to SB works but then it never updates SB because p2 thinks the update is already done? May be FB needs to be uninstalled? Is this possible via advices? Have you tried to update SB to SB without updating FB first (the case where FB was not installed at all)?

@iloveeclipse With the fix you suggested (adding `.feature.group`) *Check for Updates* detects both the FindBugs to SpotBugs and SpotBugs to SpotBugs upgrade paths. In the former case, both the FindBugs plugin and feature are removed from the `plugins` and `features` folder of your Eclipse installation.

**Comment by iloveeclipse** [comment]
I think we are done here.
