### ISSUE TITLE
Allow additional keywords to search for SpotBugs preference page

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#210]
The preference page of the SpotBugs Eclipse plugin can now be found under _Java_ > _SpotBugs_. Consequently, users who have upgraded from FindBugs to SpotBugs may not find it that easily.

I suggest that the SpotBugs preference page should also be found using the following keywords:

- bugs
- findbugs

Any prefix like “bug”, “spot”, or “find” would work as well, of course.

FWIW, I’m willing to prepare a pull request.

**Comment by sewe** [comment]
Here’s a screenshot that illustrates the new behavior:

![preferences-searching-for-findbugs](https://user-images.githubusercontent.com/491981/27045822-7eafb76c-4fa2-11e7-8523-4fbcf83a8365.png)

**Comment by KengoTODA** [comment]
#211 closed this issue.
