### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by bullettr** [spotbugs/spotbugs#2263]
How can i fix this bug pls help 
![Screenshot_12](https://user-images.githubusercontent.com/118376420/202236255-6f664ee8-6d1e-4a8f-b306-8ece692f8865.png)

**Comment by vyvy8801** [comment]
you can easy fix this buy using bind 
like this
![Screenshot_14](https://user-images.githubusercontent.com/113319617/202236831-a7ccf12f-cc27-496a-aac9-d2ea66eb6c23.png)
