### ISSUE TITLE
Spotbugs forum/mailing list

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#228]
Hi all, 
There was a mail on the FindBugs mailing list about forum for SpotBugs. 
I think we should not mix issues in code and pollute this bug tracker with questions, so what do you think of we create a new spotbugs/forum repository for discussions only?

See an example:
https://github.com/hapijs/discuss

**Comment by mebigfatguy** [comment]
Seems like a reasonable idea

**Comment by henrik242** [comment]
Wouldn't it be better with a Google group using the spotbugs domain?

**Comment by KengoTODA** [comment]
Personally I prefer GitHub issue than Google Group, because I'm living in China mainland 😭

**Comment by iloveeclipse** [comment]
@sewe : WDYT?

**Comment by sewe** [comment]
I would have gravitated towards a Google Group, but do see the Great Firewall problem.

Maybe a separate “dicussion” label in the issue tracker is enough.

Or we simply continue to use findbugs-discuss@cs.umd.edu for as long as it is available. (Of course, we then may all of a sudden loose the mailing list archive, if the University of Maryland decides to shut the server down.)

**Comment by iloveeclipse** [comment]
> Maybe a separate “dicussion” label in the issue tracker is enough.
I personally like to see issues only in the issue tracker and do not mix them with all possible questions etc things.  

> Or we simply continue to use findbugs-discuss@cs.umd.edu for as long as it is available. 
The benefit of github would be probably easier integration with the project, and also ability to use web interface for communication.

**Comment by henrik242** [comment]
On Sun, 2 Jul 2017 at 13:54, Andrey Loskutov <notifications@github.com>
wrote:

> > Maybe a separate “dicussion” label in the issue tracker is enough.
>
> I personally like to see issues only in the issue tracker and do not mix
> them with all possible questions etc things.
>
>
Strongly agree

> Or we simply continue to use findbugs-discuss@cs.umd.edu for as long as
> it is available.
>
> The benefit of github would be probably easier integration with the
> project, and also ability to use web interface forcommunication.
>
>
Google groups is also available with a web interface. Also, I don't think
using the old mailing list is a god idea.

Henrik

**Comment by h3xstream** [comment]
**I won't be the biggest user..** I am not a big fan of mailing list. I would prefer a convenient web interface.
The main advantage will be the nice references between discussion thread, issue tracker and commits.

**Comment by iloveeclipse** [comment]
OK, let's summarize a bit:
- strong wish not to mix issues with questions
- can't use google groups because of the "great firewall" 
- continue using old list is acceptable but not a good idea
- no strong votes against the original proposal to create an extra "discuss repository"

=> I will create spotbugs/discuss.

It is not to late, so before announcing this on the  findbugs-discuss@cs.umd.edu we still have a chance to    implement a different proposal, but for the upcoming 3.1.0 release I would like to have a decision, so that we go with a release *and* a new discussion room.

**Comment by iloveeclipse** [comment]
Created: https://github.com/spotbugs/discuss/

If this is the way to go, we should link to it on the project entry page and readme in *this* repo.

**Comment by koppor** [comment]
Since the users are more IT friendly guys, they should be used to GitHub. In the context of JabRef, we decided for discourse (http://discourse.jabref.org/). They offer (on request and negotiation) free hosting for open source projects. However, as maintainer of a project, it is difficult to follow discussions there, because they are outside the normal flow.

Still, they offer a kind of mailing lists, too: http://discourse.jabref.org/t/quick-start-guide-for-former-mailing-list-users/31

**Comment by iloveeclipse** [comment]
Thanks everyone for input, looks like we are done here.
