### ISSUE TITLE
Eclipse plugin installation data still uses some FindBugs references

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#232]
License, copyright etc should be changed from University of Maryland to SpotBugs Project, also icon and some texts must be fixed.

**Comment by iloveeclipse** [comment]
The result looks like this:

![installed_spotbugs](https://user-images.githubusercontent.com/964108/27770251-405209b8-5f3b-11e7-8a31-c6c0a021bced.png)

**Comment by KengoTODA** [comment]
I'm not sure but can we change copyright? I think what we can do is just forking based on OSS licence, not changing copyright.

e.g. jenkins's copyright is still Sun, not Oracle nor Cloudbees.

**Comment by iloveeclipse** [comment]
@KengoTODA , you have right, I had to leave existing notice and only add the new one, will push in a minute.

**Comment by AndreasAumayr** [comment]
Not sure if it belongs here, but this is also true for the context menu.
Right click in the package explorer (on a project or file): Spot Bugs > Spot Bugs 
Right click in an editor: Find Bugs > Spot Bugs

**Comment by iloveeclipse** [comment]
I will push the fix in a moment. I think the top most level should be the project label (to *whom* we are talking?), and the action name should impress *what* we do, therefore: "SpotBugs -> Find Bugs".
