### ISSUE TITLE
Minimal Release

### ISSUE THREAD

**Issue by keyvankhademi** [spotbugs/spotbugs#2334]
I am running SpotBugs on a single Java file using the command line interface. However, the entire package size is too large at around 15MB. I believe there are many dependencies that are not needed for running the command line interface with text-based user interface. Is there a way to reduce the package size to only include the necessary dependencies for this purpose?

**Comment by hazendaz** [comment]
closing as I do not believe that to be the case.  spotbugs only has minimal libraries.  The core itself is on 4mb and no info was given here to what exactly you believe shouldn't be here.
