### ISSUE TITLE
java.lang.AssertionError: classname com/ssg/cmp/network/switches/adapter/out/SwitchMapper should be dotted at edu.umd.cs.findbugs.PackageMemberAnnotation.<init>(PackageMemberAnnotation.java:75)

### ISSUE THREAD

**Issue by n8milk** [spotbugs/spotbugs#2353]
Is the classname should be dotted?

like Switch.Mapper?

**Comment by JuditKnoll** [comment]
Can you please give a bit more info? How did you encounter the problem? What version of spotbugs are you using? Are you using spotbugs standalone, via the gradle plugin, via the maven plugin, or integrated into an IDE (IntelliJ or eclipse)? Can you please provide a full stacktrace?

**Comment by hazendaz** [comment]
closing as not part of our build.
