### ISSUE TITLE
Why scan results having multiple source-line tags for a bug instance?

### ISSUE THREAD

**Issue by Lingom-KSR** [spotbugs/spotbugs#2380]
Hi,
I would like to understand from the scan result,  why a bug instance have multiple source-line tags for a same line number. Below is the sample bug instance I got from Spotbugs. It has two source line tags which referring the same line number 21 from the same file "sample.java".

`<BugInstance type="UNSAFE_HASH_EQUALS" priority="2" abbrev="SECUHE" category="SECURITY" instanceHash="c39e6dacd530b3bd8fadecdf10bbf01a" instanceOccurrenceNum="0" instanceOccurrenceMax="0" rank="12" cweid="203">
    ......
    <Class classname="xxxxxx" primary="true">
      ......
    </Class>
    <Method classname="xxxxx" name="login" signature="xxxxxx;" isStatic="false" primary="true">
    .....
    </Method>
    <SourceLine classname="xxxxxx" start="21" end="21" startBytecode="19" endBytecode="19" sourcefile="sample.java" sourcepath="xxxxx" primary="true" contentHash="a61b735021ad6e6b7d4cb710afc978102a9b22e5582b1a1267cc43f1ec60c3a7">
      <Message>At sample.java:[line 21]</Message>
    </SourceLine>
    <String value="java/lang/String.equals(xxx)Z" role="Sink method">
      .....
    </String>
   .....
    <SourceLine classname="xxxxx" start="21" end="21" startBytecode="16" endBytecode="16" sourcefile="sample.java" sourcepath="xxxx" contentHash="a61b735021ad6e6b7d4cb710afc978102a9b22e5582b1a1267cc43f1ec60c3a7">
      <Message>At sample.java:[line 21]</Message>
    </SourceLine>
  </BugInstance>`

Any help would be appreciated.

Thanks!

**Comment by gtoison** [comment]
So what's one line 21? Can you share the code you're analyzing?

**Comment by Lingom-KSR** [comment]
Here is the set of code.. the issue occur in the bold line.

public class LoginController {
...........
  @CrossOrigin(origins = "*")
  @RequestMapping(value = "/login", method = RequestMethod.POST, produces = "application/json", consumes = "application/json")
  LoginResponse login(@RequestBody LoginRequest input) {
    User user = User.fetch(input.username);
    **if (Postgres.md5(input.password).equals(user.hashedPassword))** {
      return new LoginResponse(user.token(secret));
    } else {
      throw new Unauthorized("Access Denied");
    }
  }
}

**Comment by gtoison** [comment]
This is actually reported by the [findsecbugs](https://github.com/find-sec-bugs/find-sec-bugs) plugin which is another project.
That particular detector looks for string comparisons where either side of the `.equals()` call is possibly sensitive information. The detector looks for variables containing `hash`, `md5`, `sha` or `digest`.

In your case both sides are considered sensitive and are flagged.

**Comment by gtoison** [comment]
I'll close this as there does not seem to be further questions, please don't hesitate to comment here or to open an new issue if anything is unclear
