### ISSUE TITLE
XML Output incorrectly escaped in Eclipse Bug Info view

### ISSUE THREAD

**Issue by harbulot** [spotbugs/spotbugs#2389]
When viewing a bug info in Eclipse, the XML output can display invalid XML due to incorrect escaping.

This is particularly the case for bugs that occur in constructors (in which case the method name is `<init>`).

The XML output currently produced is:

```xml
<Method classname="com.example.MyClass" name="<init>" signature="(Ljava/lang/String;[C)V" isStatic="false" role="METHOD_CALLED">
```

However, `<` and `>` in the attribute value (`name="<init>"`) should be escaped:

```xml
<Method classname="com.example.MyClass" name="&lt;init&gt;" signature="(Ljava/lang/String;[C)V" isStatic="false" role="METHOD_CALLED">
```

I think this is probably due to a case missing in [`BugInfoView.toSafeHtml`](https://github.com/spotbugs/spotbugs/blob/b4dae8c9943961d645b9ed2acb4d8df5c125c5ef/eclipsePlugin/src/de/tobject/findbugs/view/BugInfoView.java#L397) called from [`BugInfoView.addXmlOutput`](https://github.com/spotbugs/spotbugs/blob/b4dae8c9943961d645b9ed2acb4d8df5c125c5ef/eclipsePlugin/src/de/tobject/findbugs/view/BugInfoView.java#L324).

`toSafeHtml` currently only escapes `<` and `>`, but doesn't escape `&`:

```java
    private static String toSafeHtml(String s) {
        if (s.indexOf('>') >= 0) {
            s = s.replace(">", "&gt;");
        }
        if (s.indexOf('<') >= 0) {
            s = s.replace("<", "&lt;");
        }
        return s;
    }
```

If you start with this XML

```xml
    <tag name="&lt;init&gt;" />
```

It is then turned into HTML via `toSafeHtml` into:

```
    &lt;tag name="&lt;init&gt;" /&gt;
```

The HTML is then displayed as:

```xml
     <tag name="<init>" />
```

I think this could be solved by escaping the `&` symbol too:

```java
    private static String toSafeHtml(String s) {
        if (s.indexOf('>') >= 0) {
            s = s.replace(">", "&gt;");
        }
        if (s.indexOf('<') >= 0) {
            s = s.replace("<", "&lt;");
        }
        if (s.indexOf('&') >= 0) {
            s = s.replace("&", "&amp;");
        }
        return s;
    }
```

**Comment by hazendaz** [comment]
fixed by https://github.com/spotbugs/spotbugs/issues/2389
