### ISSUE TITLE
How to fetch SpotBugs Report in JSON format?

### ISSUE THREAD

**Issue by SrinjoyPriya** [spotbugs/spotbugs#2392]
I've been using spotBugs plugin in a gradle project that am currently working on. I just wanted to know if i wanted to fetch the report in JSON format instead of XML or HTML, how can I do so?

**Comment by Jeeppler** [comment]
@SrinjoyPriya there is a format called [Static Analysis Results Interchange Format (SARIF)](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html). SARIF is a JSON file. Spotbugs supports writing reports in SARIF.

**Comment by gtoison** [comment]
Thanks for the answer @Jeeppler
This seems to be a valid solution so I'll close the issue, please don't hesitate to revert if this isn't working
