### ISSUE TITLE
Don’t distribute test-only JDepend dependency

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#242]
At the moment, SpotBugs has `jdepend:jdepend:2.9.1` as a *compile*-scoped dependency, even though it is only needed by (a single) unit test. The dependency’s scope should IMHO be reduced to *test* and JDepend should no longer be included in the distribution ZIP (the tests aren’t either).

Note that this potentially affects existing detectors, who may assume that JDepend are on the classpath, but I think this is only a hypothetical issue (I’ve checked `fb-contri` and `findsecbugs`; they do not use JDepend).

**Comment by iloveeclipse** [comment]
I think we are done here now.
