### ISSUE TITLE
java.lang.InterruptedException at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1100)

### ISSUE THREAD

**Issue by JosephWen** [spotbugs/spotbugs#2456]
The error was copied to the clipboard. Press Command+V

**Comment by hazendaz** [comment]
I don't understand.   Why do so many people do this against spotbugs?  The error and data is useless.  Please open proper issues per our template.  This one needs closed.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: JosephWen ***@***.***>
Sent: Tuesday, June 20, 2023 4:03:20 PM
To: spotbugs/spotbugs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotbugs/spotbugs] java.lang.InterruptedException at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1100) (Issue #2456)


The error was copied to the clipboard. Press Command+V

**Comment by JuditKnoll** [comment]
I think these issues come from the [IntelliJ spotbugs plugin](https://github.com/JetBrains/spotbugs-intellij-plugin).

**Comment by hazendaz** [comment]
ok with tickets like these, just close them.  If user doesn't care enough to actually write up an issue, we should not waste time even looking.  Plus last I checked we are not intellij.
