### ISSUE TITLE
CONSTANT_Dynamic tag is not supported

### ISSUE THREAD

**Issue by lbcjbb** [spotbugs/spotbugs#2503]
## Describe the bug

[Bazel] >= **6.2** (using [ASM] **9.4** and [JaCoCo] **0.8.9**) build a Java class file which is not supported by any version of `spotbugs`.

### Build

```shell
$ git clone -b java-coverage-spotbugs https://github.com/leboncoin/bazel-playground test-spotbugs
$ cd test-spotbugs
$ bazel build --collect_code_coverage //:foo
...
```

This command will generate the JAR file `./bazel-bin/libfoo.jar` using Java 17.
[I attach this JAR file to this ticket](https://github.com/spotbugs/spotbugs/files/12269231/libfoo.jar.zip) so that you don't need to install and use Bazel.

The simple Java source file used is as follow:

```java
package foo;

public record Foo (){}
```

### Test

```shell
$ spotbugs -textui ./bazel-bin/libfoo.jar 
The following errors occurred during analysis:
  Invalid class resource foo/Foo.class in .../libfoo.jar:foo/Foo.class
    edu.umd.cs.findbugs.classfile.InvalidClassFileFormatException: Invalid classfile format in .../libfoo.jar:foo/Foo.class
      At edu.umd.cs.findbugs.classfile.engine.ClassParser.readConstant(ClassParser.java:250)
      At edu.umd.cs.findbugs.classfile.engine.ClassParser.parse(ClassParser.java:101)
      At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.parseClassName(ClassPathBuilder.java:732)
      At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.scanCodebase(ClassPathBuilder.java:695)
      At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.processWorkList(ClassPathBuilder.java:634)
      At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:230)
      At edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:708)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:245)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
      At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
  Error scanning foo/Foo for referenced classes
    java.lang.IllegalStateException: Unexpected tag of 17 at offset 905 while parsing foo/Foo from .../libfoo.jar:foo/Foo.class
      At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:723)
      At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:736)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:79)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
      At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
      At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)

Exception in thread "main" edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in .../libfoo.jar *JrtfsCodeBase [file=/usr/lib/jvm/java-18-openjdk-amd64/lib/jrt-fs.jar] 
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:304)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
```

## Expected behavior

No error expected.

## Investigation

It appears that the tag `CONSTANT_Dynamic` introduced in Java 11 is not supported by the class parser of `spotbugs`: 

https://github.com/spotbugs/spotbugs/blob/3cce1f0c8e9599e60c1b35030a084435b3c17a0a/spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/engine/ClassParser.java#L206-L234

See https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.4.10 for more details on this entity.

## Version

 - OS: `Linux` / `amd64`
 - **Java 17** used to build the JAR file.
 - **Java 18.0.2-ea** used to execute `spotbugs`.

[Bazel]: https://bazel.build/
[ASM]: https://asm.ow2.io/
[JaCoCo]: https://www.jacoco.org/jacoco/

**Comment by gtoison** [comment]
This makes me think that it shouldn't happen with bazel 6.3: https://github.com/bazelbuild/bazel/issues/18360
Can you please try?

Regardless, this should probably be supported in Spotbugs down the road

**Comment by lbcjbb** [comment]
No, no. Before the fix of this issue bazelbuild/bazel#18360, Bazel (**>=6.2.0**, including **6.3.0** and **6.3.1**) was not able to correctly build the Jar file with the instuctions returned by the new version used of JaCoCo (**0.8.8**).
This issue has been fixed, but now all these versions of Bazel produces a Jar file containing the new tag `CONSTANT_Dynamic` which is not understood by `spotbugs`.

**Comment by lbcjbb** [comment]
Thank you very much @gtoison. Do you have any idea when your next release will be?

**Comment by lbcjbb** [comment]
Thank you !

**Comment by lbcjbb** [comment]
I have tested the fix  https://github.com/spotbugs/spotbugs/pull/2506 in my repository, but I continue to have any errors, other errors.
The minimal class file I attached to this ticket was too much simple.

I created a PR (https://github.com/spotbugs/spotbugs/pull/2512) to try to completely fix these errors, but I have now some errors from the BCEL library (see the comment of my PR).
