### ISSUE TITLE
Disabling spotbugsIntegrationTest Task in Separate Gradle Configuration File

### ISSUE THREAD

**Issue by CedricNdong** [spotbugs/spotbugs#2505]
**Describe the bug**
When attempting to disable the spotbugsIntegrationTest task in a separate spotbugs.gradle file and then applying this file in the main build.gradle, I encounter a groovy.lang.MissingPropertyException for the task spotbugsIntegrationTest, even though this task exists.

**To Reproduce**
1. Add the SpotBugs plugin with version 5.0.14 in the build.gradle file.
2. Create a new spotbugs.gradle file in the project's root directory with the content:
      `spotbugsIntegrationTest.enabled = false
`
![image](https://github.com/spotbugs/spotbugs/assets/92950547/09e8aabb-75c1-495f-8bde-91d88ecd021f)

3.In the build.gradle file, apply the SpotBugs plugin with `apply from: "$rootDir/spotbugs.gradle"`
4. Execute the Gradle task to see the error:
5. See error

**Expected behavior**
The spotbugsIntegrationTest task should be disabled and not run during the build.

**Actual behavior**
I receive the following error:
`Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'spotbugsIntegrationTest' for root project '...' of type org.gradle.api.Project.`

**Environment**
Gradle version: 7.4.2
SpotBugs plugin version: 5.0.14
Java version: openjdk 17.0.6 2023-01-17
Operating System: Windows 11

**Additional context**
I've attempted to use lazy configuration with tasks.named('spotbugsIntegrationTest').configure, but the issue persists.

**Comment by JuditKnoll** [comment]
I think this could be [spotbugs gradle plugin](https://github.com/spotbugs/spotbugs-gradle-plugin) issue, not spotbugs itself one. Also, there are newer versions of the gradle plugin. Can you please verify that the problem still persists in the latest spotbugs gradle plugin version, 5.1.1?

**Comment by CedricNdong** [comment]
Hi! I tested with  the new version 5.1.1 but the problem still persists.

**Comment by JuditKnoll** [comment]
A new issue was created for this at the [spotbugs gradle plugin](https://github.com/spotbugs/spotbugs-gradle-plugin) repository ( https://github.com/spotbugs/spotbugs-gradle-plugin/issues/951 ).
