### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Jeeppler** [spotbugs/spotbugs#2510]
I contributed some time ago an improved SARIF report with taxonomies #2321. I would love to see a new release, with this feature and the many other contributions which were added since the last release in October 2022.

The reason why I would love to have a release with the SARIF taxonomy feature, is that OWASP Find Security Bugs uses Spotbugs. Therefore, first Spotbugs needs to be released and afterwards Find Security Bugs can be released to include the new SARIF taxonomy report feature.

**Comment by hazendaz** [comment]
Closing for now as we have discussion on it and others can find, trying to keep our issues cleaner so we can find what we need to fix.  This one doesn't really need to be fixed ;)
