### ISSUE TITLE
MethodReturnCheck should detect not-thrown exceptions returned by factory methods

### ISSUE THREAD

**Issue by fiveOO** [spotbugs/spotbugs#2547]
MethodReturnCheck(RV_EXCEPTION_NOT_THROWN) detects not-thrown exceptions created by calling a constructor directly.

It would be helpful to detect not-thrown exceptions returned by a factory method in addition.

```
// is detected
new IllegalArgumentException("x must be nonnegative");
```
```
// should be detected
MyException.someLogicWentWrong("value1", "value2");
```

**Comment by gtoison** [comment]
This is the same kind of feature request as #2449 and would be useful indeed
