### ISSUE TITLE
NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE triggers in strange cases

### ISSUE THREAD

**Issue by IlyaSukhorukov** [spotbugs/spotbugs#2548]
Have a problem with SpotBugs "Possible null pointer dereference due to return value of called method (NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE)" in strange cases.<br>
With Lombok getter:<br>
```
@Generated
public @Nullable Integer getPort() {
    return this.port;
}
```
When i try to get value from object using getPort() and produce it to another method where it can't be null spotbugs shows an error "NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE".<br>
Example 1.<br>
Ok here a value possible null.
```
session.connectAndBind(gateway.getHost(), gateway.getPort()); // <--- Error
```
Example 2.<br>
Get same error on unboxing.
```
int port = gateway.getPort() != null ? gateway.getPort() : 0; // <--- Error
session.connectAndBind(gateway.getHost(), port);
```
Example 3.<br>
Still get error on unboxing.
```
int port = 0;
if (gateway.getPort() != null) { // <--- Error
    port = gateway.getPort();
}
session.connectAndBind(gateway.getHost(), port);
```
So why i getting the error?<br>
Find one case when veryfi pass with no errors. Code below.
```
// Pass
Integer port1 = gateway.getPort();
int port = port1 != null ? port1 : 0;
session.connectAndBind(gateway.getHost(), port);
```

**Comment by gtoison** [comment]
`@Nullable Integer getPort()` means that it is nullable, here SpotBugs is not smart enough to know that it can't be null, because it is not guaranteed that calling `getPort()` twice will yield the same return.
Maybe some class is extending it, maybe there's another thread somewhere modifying the value, etc.

**Comment by IlyaSukhorukov** [comment]
Thanks a lot.

**Comment by IlyaSukhorukov** [comment]
Thanks a lot.
