### ISSUE TITLE
Facing issue Exception in thread "main" edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in

### ISSUE THREAD

**Issue by rupesh1306** [spotbugs/spotbugs#2574]
Hi,
We have recently upgraded JDK 8 to 11,
Currently we are using Findbugs but facing this issue,
"Exception in thread "main" edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in"

Can Spotbugs work with JDK 11 application?

Regards,
Rupesh

**Comment by hazendaz** [comment]
Spotbugs works in jdk 8 through 21 as released if asm overriden.  Please provide more on the stack trace as I don't see how that bit helps.  You can also see more jdks running with it on maven plugin with numerous examples.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rupesh1306** [comment]
HI @hazendaz 
do you mean spotbug will support till JDK version 21?

Here is the detailed stack, you asked for,
`13:56:05  Exception in thread "main" edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in /home/Test/jenkins-slave/jenkins-testcase-build-agent/workspace/FindBug_develop/server/TestUtility/build/libs/TestUtility-V12.jar */home/Test/jenkins-slave/jenkins-testcase-build-agent/workspace/FindBug_develop/Findbug_tool/findbugs-3.0.1/lib/servlet-api.jar */home/Test/jenkins-slave/jenkins-testcase-build-agent/workspace/FindBug_develop/Findbug_tool/findbugs-3.0.1/lib/annotations.jar */home/Test/jenkins-slave/jenkins-testcase-build-agent/workspace/FindBug_develop/Findbug_tool/findbugs-3.0.1/lib/jsr305.jar 
13:56:05  	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:278)
13:56:05  	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
13:56:05  	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)`

**Comment by JuditKnoll** [comment]
It looks like you are using an old version of spotbugs. Can you please update to a newer version?
The latest version, 4.7.3 does support newer JDKs, even JDK 21 if you force update the asm dependency.

**Comment by hazendaz** [comment]
closing as user shown issue using findbugs not spotbugs.  not an issue here.
