### ISSUE TITLE
Date for 4.8.0 release ?

### ISSUE THREAD

**Issue by abishek75** [spotbugs/spotbugs#2594]
We are evaluating SpotBugs, wanted to know when 4.8.0 is planned to be released as it has JDK 8 support.

**Comment by JuditKnoll** [comment]
As far as I can see, you already found the discussion about the next release, where you got an answer from @gtoison (https://github.com/spotbugs/spotbugs/discussions/2417#discussioncomment-7174135) and @hazendaz (https://github.com/spotbugs/spotbugs/discussions/2417#discussioncomment-7174542), so I'm closing this issue.
