### ISSUE TITLE
GHA - Add jdk 11 along with temp drop back on Eclipse to java 11 build

### ISSUE THREAD

**Issue by hazendaz** [spotbugs/spotbugs#2598]
In trying to isolate personal issues on my windows platform, I learned that gradle was using oracles hack to the jvm after one of the installs and ignored my path setup.  After fixing that, I was able to get same results on local as on GHA.  While working on this I got GHA working with jdk 11 and 20 in addition to 17.  There is one test case in this that simply does not work with java 11.  Going to ignore on that for java 11 only, drop eclipse slightly back as well.  Originally I wanted jdk 21 to show case it working due to various user inquires but fact of the matter is gradle doesn't support it yet until 8.4 and still won't with kotlin which means we cannot actually show that.  So that is where jdk 20 comes into place.

Will have this over in next few days to be in 4.8.0

**Comment by soloturn** [comment]
i tried
```
diff --git a/build-logic/build.gradle.kts b/build-logic/build.gradle.kts
index 89af65d3e1c..97d79029ba5 100644
--- a/build-logic/build.gradle.kts
+++ b/build-logic/build.gradle.kts
@@ -46,7 +46,14 @@ dependencies {
     implementation("org.terasology.gestalt:gestalt-module:7.1.0")
 
     // plugins we configure
-    implementation("com.github.spotbugs.snom:spotbugs-gradle-plugin:5.1.3")
+    implementation("com.github.spotbugs.snom:spotbugs-gradle-plugin:5.1.3") {
+        exclude(group = "org.ow2.asm")
+    }
+    //implementation("org.ow2.asm:asm:9.5")
+    //implementation("org.ow2.asm:asm-analysis:9.5")
+    //implementation("org.ow2.asm:asm-commons:9.5")
+    //implementation("org.ow2.asm:asm-tree:9.5")
+    //implementation("org.ow2.asm:asm-util:9.5")
     implementation("org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.3")
 
     api(kotlin("test"))

```

**Comment by perlun** [comment]
> i tried following which still gives the same error. not sure if i am doing it correctly.

@soloturn I tried something similar, but couldn't get it to work either. :thinking: I guess this could have something to do with https://github.com/spotbugs/spotbugs-gradle-plugin#spotbugs-version-mapping and how the plugin loads the Spotbugs version.

@hazendaz - I guess you don't have any obvious idea how to override the asm version being used by the plugin with Gradle?

**Comment by JuditKnoll** [comment]
Kotlin 1.9.20 got released which supports JDK 21. See the `Tools. CLI` part at https://github.com/JetBrains/kotlin/releases/tag/v1.9.20 ([KT-60662](https://youtrack.jetbrains.com/issue/KT-60662)).

**Comment by hazendaz** [comment]
@perlun I don't know gradle enough yet to know how to do so.  However, should be mute now, you can use 4.8.1 / gradle plugin 5.2.3 (soon 6.0.0), or maven (4.8.1.0) which all have latest support.  Do note only the maven plugin can make it to jdk 21 usage most directly.  Others can if no kotlin.  Give it a month we should have jdk 22 working across all the parts.

**Comment by JuditKnoll** [comment]
> Others can if no kotlin.
I think it should work already with Kotlin as well, but I haven't tested it yet.

> Give it a month we should have jdk 22 working across all the parts.
You mean JDK 21 😄 . JDK 22 only will be released in March 2024.

**Comment by hazendaz** [comment]
Early access ;)

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
