### ISSUE TITLE
Support Java 21

### ISSUE THREAD

**Issue by jfurmankiewiczpros** [spotbugs/spotbugs#2621]
We're upgrading to Java 21 and SpotBugs seems to be the only tool that does not support it at all.
We may need to disable Spotbugs in all of our builds, as it blocking the upgrade to 21.

'''
  Unable to get XClass for com/nimbusds/jwt/JWTClaimsSet$Builder
    java.lang.IllegalArgumentException: Unsupported class file major version 65
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35
'''

Hope you can release a new version with 21 support as soon as possible, thank you

**Comment by hazendaz** [comment]
Hi, this has been opened numerous times now.  Please just override ASM to latest release (currently 9.6) and it will work fine.

**Comment by hazendaz** [comment]
@jfurmankiewiczpros We have just released 4.8.0 which doesn't require the override.  Please give that a try.  The grade plugin and maven plugin will be out in next day or two.
