### ISSUE TITLE
4.8.0 RV_EXCEPTION_NOT_THROWN False positive with JUnit 5 assertThrows

### ISSUE THREAD

**Issue by josephearl** [spotbugs/spotbugs#2628]
RV | org.junit.jupiter.api.Assertions.assertThrows(Class, Executable) not thrown in com.my.package.SomeServiceTest$someNestedTest.itShouldDoSomething()

Called method org.junit.jupiter.api.Assertions.assertThrows(Class, Executable)
At SomeServiceTest.java:[line 85]

Where line 85 is:

```
assertThrows(SomeException.class, () -> someService.doSomething("someParam"));
```

**Comment by JuditKnoll** [comment]
Can you please provide the `someService.doSomething("someParam")` function, or at least the header?
I think it got into the code when fixing https://github.com/spotbugs/spotbugs/issues/2547.

**Comment by josephearl** [comment]
The method signature is:

```
public void doSomething(String param)
```

**Comment by bwmeier** [comment]
This is flagging just about all of our JUnit tests for exception behavior.  It shows up with both `org.junit.jupiter.api.Assertions#assertThrows(java.lang.Class<T>, org.junit.jupiter.api.function.Executable)` and `org.junit.Assert#assertThrows(java.lang.Class<T>, org.junit.function.ThrowingRunnable)` invocations, and both Java standard and custom exceptions.

**Comment by bwmeier** [comment]
As an additional note, I changed one of the tests to use the AssertJ method `org.assertj.core.api.Assertions#assertThatExceptionOfType`, and the spotbugs failure went away.

**Comment by bwmeier** [comment]
I think I have a bit more information here.  `assertThrows` returns the exception for further testing by the unit test.  If the unit test does nothing with the returned value, then the error is raised by spotbugs.  If the unit test does further work with the returned exception value, then the error is not raised.  Basically the following code raises the spotbugs error:
```java
Assertions.assertThrows(NullPointerException.class, () -> methodThrowingNpe(null));
```
but the following code does not:
```java
var npe = Assertions.assertThrows(NullPointerException.class, () -> methodThrowingNpe(null));
Assertions.assertTrue(npe.getMessage().contains("something"));
```
