### ISSUE TITLE
Probable false positive detection of PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_CLASS_NAMES

### ISSUE THREAD

**Issue by bwmeier** [spotbugs/spotbugs#2645]
Probable false positive detection of PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_CLASS_NAMES with private records.  It's unclear exactly what's showing up because the message from the detection of the errors is corrupted `Class name ?>?1/1??? in source file ?>?2/1??? shadows the publicly available identifier from the Java Standard Library.`  One error was able to be traced to a private record class named `DocLink` used internally to a documentation generation class.

**Comment by iloveeclipse** [comment]
Duplicates #2627

**Comment by bwmeier** [comment]
@iloveeclipse Thanks!
