### ISSUE TITLE
PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_CLASS_NAMES  message missing substitutions

### ISSUE THREAD

**Issue by pburka** [spotbugs/spotbugs#2646]
I'm seeing messages like the following from Spotbugs 4.8.0:

```M B PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_CLASS_NAMES PI: Class name ?>?1/1??? in source file ?>?2/1??? shadows the publicly available identifier from the Java Standard Library.  In Clock.java```

Presumably this is meant to print an actual class name and file path rather than `?>?1/1???` and `?>?2/1???`

**Comment by iloveeclipse** [comment]
Duplicates https://github.com/spotbugs/spotbugs/issues/2627
