### ISSUE TITLE
DMI_DOH reported on org.junit.Assert.fail

### ISSUE THREAD

**Issue by bwmeier** [spotbugs/spotbugs#2647]
The following error is reported on invocation of `org.junit.Assert.fail(String)`:

> DMI	D'oh! A nonsensical invocation of fail(String) in functionXYZ(String)
> [Bug type DMI_DOH (click for details)](https://github.com/spotbugs/spotbugs/issues/new#DMI_DOH)
> In class Example
> In method functionXYZ(String)
> Called method org.junit.Assert.fail(String)
> Passing String constant as value that should be null checked
> String constant "Element should exist"
> At Example.java:[line 361]

**Comment by JuditKnoll** [comment]
Can you please provide an example code, where you got the error reported?

**Comment by gtoison** [comment]
This seems to be fixed by #2643
