### ISSUE TITLE
Consume ASM 6.0 BETA

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#268]
ASM project just released 6.0 BETA binaries, we schould make sure we use them.

**Comment by sewe** [comment]
I will have a look.

**Comment by iloveeclipse** [comment]
Thanks Andreas. 
P.S. I'm pretty overloaded right now, so I have no time for pending reviews.

**Comment by sewe** [comment]
> Thanks Andreas.

May take a bit here as well; the Maven Central promotion is [still pending](https://mail.ow2.org/wws/arc/asm/2017-07/msg00002.html).

> P.S. I'm pretty overloaded right now, so I have no time for pending reviews.

No problem. I’ll reach out to one of the other committers.

**Comment by iloveeclipse** [comment]
@KengoTODA : I'm not a maven expert/user , I don't know how complicated it is to update the ASM version - but it would be great if this would be in RC4.

**Comment by sewe** [comment]
> I'm not a maven expert/user , I don't know how complicated it is to update the ASM version - but it would be great if this would be in RC4.

@iloveeclipse On our side, Maven would not be involved. (Gradle and `grep` would.)

But apparently the ASM guys are [facing a delay](https://mail.ow2.org/wws/arc/asm/2017-07/msg00002.html) with **their** promotion to Maven Central. I’ll keep an eye on their mailing list.

**Comment by KengoTODA** [comment]
It has not been published to Maven central yet, let's handle it in RC5 or later

**Comment by iloveeclipse** [comment]
Yep. They still have trouble promoting the build via the new infrastructure in ASM.

**Comment by don-vip** [comment]
It seems finally available on Maven Central: http://repo1.maven.org/maven2/org/ow2/asm/asm/6.0_BETA/

**Comment by sewe** [comment]
@don-vip Great. I’ll have a look at doing the update then.

**Comment by sewe** [comment]
Commit 6491753 so far is just a quick search & replace. I haven’t done any in-depth testing; hence, no pull request yet.

**Comment by sewe** [comment]
Pull request is here: #303.

**Comment by iloveeclipse** [comment]
Closed by #303. Thanks all.
