### ISSUE TITLE
Wrong Java VM in Android Studio?

### ISSUE THREAD

**Issue by fmmarzoa** [spotbugs/spotbugs#2697]
Hi,

I just installed the Spot Bugs plugin in Android Studio in my Mac, but when I try to run it I keep getting this error (please note I have omitted java args that aren't relevant to save space):

```
Abnormal build process termination: 
nice -n 10 /Users/fmarzoa/Library/Java/JavaVirtualMachines/liberica-1.8.0_333/bin/java [...]
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Now, I think this is because it's trying to use Java 1.8 but needs Java 11. And then the question for which I have no answer is why it is trying to use that specific Java VM at all?

In the About of Android Studio says this:

```
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

```
In the Gradle Settings the Gradle SDK is 

`jbr-17 JetBrains Runtime version 17.0.6/....`

Also in the terminal:

```
% java -version
openjdk version "20.0.2" 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+10)
OpenJDK 64-Bit Server VM (build 20.0.2+10, mixed mode, sharing)
 % /usr/libexec/java_home 
/Library/Java/JavaVirtualMachines/liberica-jdk-20-full.jdk/Contents/Home
```

So I don't know the reason why Spot Bugs is trying to run with that liberica-1.8.0_333 instead.

**Comment by iloveeclipse** [comment]
Sorry, spotbugs bug tracker is not a tracker for Android Studio / spotbugs plugin problems as we don't ship anything for Android Studio here.

**Comment by fmmarzoa** [comment]
I see, wrong project, sorry about that.
