### ISSUE TITLE
`java -jar /path/to/spotbugs/lib/spotbugs.jar -version` prints nothing

### ISSUE THREAD

**Issue by esabol** [spotbugs/spotbugs#2797]
I'm a newbie trying to use SpotBugs 4.8.3 from the RHEL 8.9 command line and having a fair amount of difficulty. I had to `chmod +x  /path/to/spotbugs/bin/spotbugs` script. Should I have to do that? I would think the script should already be executable when I untar the `spotsbug-4.8.3.tgz` file.

Regardless, I couldn't get the `spotbugs` script to work, so I switched to using java to execute the `spotgsbug.jar` file directly. That at least started the GUI, but I really want to use it from the command line, so I started to investigate the command line options and was surprised to discover `-version` doesn't return anything.
```
> java -jar /path/to/spotbugs/lib/spotbugs.jar -version
> 
```
`java -jar /path/to/spotbugs/lib/spotbugs.jar -help` works though. The `-help` output says `-version` should "print version, check for updates and exit, without running analysis". It doesn't.

**Comment by xuhuisheng** [comment]
I found Version.printVersion() will print version info using info level of log. But the configed default level of log in log4j2.xml is ERROR. So version info won't print to the console.

**Comment by esabol** [comment]
This is still an issue with 4.8.4.

I've also tested with the "spotbugs" and "fb" scripts and with "version" and "-version". Same result. No output.

**Comment by esabol** [comment]
Thanks, @PatrikScully !
