### ISSUE TITLE
Combine `-high` with an include filter

### ISSUE THREAD

**Issue by guillerodriguez** [spotbugs/spotbugs#2817]
I opened [this issue](https://github.com/spotbugs/spotbugs-gradle-plugin/issues/962) in the SpotBugs Gradle Plugin repo but now I realize that this is probably not something specific to the Gradle plugin, and instead it is related to how SpotBugs works.

The problem is as follows:

I want to get all "high priority" bugs (command line option `-high`) but then pick specific a few additional bugs types not included by default when you use `-high`.

I thought I could combine `-high` and an include filter (via `-include`). However this does not work as I expected: as soon as I use an include filter, all the "high priority" bug types are excluded if not mentioned explicitly in the filter.

Is there a way to achieve what I want? i.e. to tell SpotBugs to report all the "high priority" bugs, plus a few additional bug types ?

**Comment by gtoison** [comment]
I _think_ you should be able to combine your criteria in a filter file: https://spotbugs.readthedocs.io/en/stable/filter.html
