### ISSUE TITLE
Nightly builds do not deploy Eclipse plugin anymore

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#2820]
I haven't checked which PR broke that, but since a week or so the latest builds on master do not deploy Eclipse plugin anymore to https://spotbugs.github.io/eclipse-latest/.

This makes it impossible to use latest nightly builds in Eclipse.

**Comment by JuditKnoll** [comment]
Yes, it's my bad, I'm sorry and thank you for bringing it to my attention. I created a PR fixing this: https://github.com/spotbugs/spotbugs/pull/2821

**Comment by iloveeclipse** [comment]
Still nothing deployed ... Reopening.

**Comment by hazendaz** [comment]
Agree seeing the same issue.  I run off snapshots only.  Always expect an update everytime code is merged.  I'll take a look as well.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iloveeclipse** [comment]
See commits pushed to "eclipse-latest" gh-pages repo: https://github.com/spotbugs/eclipse-latest/commits/gh-pages/
Last one was pushed for https://github.com/spotbugs/spotbugs/commit/572b53fade25474faca1f61c95a12bef82e0ea48.

So next commit https://github.com/spotbugs/spotbugs/commit/e05a747ede654f9e41be58c7a851a2179c34be1a on spotbugs didn't produced commit on "eclipse-latest" gh-pages repo...

Here is the link to github actions at this commit: https://github.com/spotbugs/spotbugs/actions/runs/7455816001/job/20285476104
but I don't see any issue reported there.

Looking at the magic number of **800 commits** on the traget repo, and thinking about the repo size (approx. 1.8 GB), I wonder if we have hit some limit on the github repo:

![image](https://github.com/spotbugs/spotbugs/assets/964108/8820bf2f-15f3-45eb-bf80-3b4295d7fa4e)

**Comment by iloveeclipse** [comment]
See https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

But I also see a change in *how* the commits to that repo were created.
Till 172adddd2de954d135dfad5b6977ca2a43de686f the commits never deleted site.xml, but updated it.
After the commit above commits started to alternate and add/delete contents on each commit, and then it stopped to commit anything...

**Comment by iloveeclipse** [comment]
I believe the 
`.github/workflows/release.yml` task isn't executed anymore after https://github.com/spotbugs/spotbugs/commit/d937db75edcae4e53e5d4e650dda34002e987c50.

Looks like syntax is broken...

**Comment by iloveeclipse** [comment]
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
> You must always use the ${{ }} expression syntax or escape with '', "", or () when the expression starts with !, since ! is reserved notation in YAML format. For example:

**Comment by iloveeclipse** [comment]
I've pushed a possible fix to my fork, but github refuses to create a PR saying there are no new changes compared to master branch ???
Here is my commit: https://github.com/spotbugs/spotbugs/commit/1e2b7911c798b27d9f89b88f9fa40d10f29a50c4
How can **that** be?

**Comment by iloveeclipse** [comment]
It becomes really crazy: now I've commited to the **this** repo on this branch: https://github.com/spotbugs/spotbugs/tree/issue_2820 but it still says there are no new changes?!?
Is this because the change is on some "special" github file? How that was done before?

**Comment by iloveeclipse** [comment]
But I see the "Build otherwise" step executed now: https://github.com/spotbugs/spotbugs/actions/runs/7602779837/job/20703718820
and new commit on https://github.com/spotbugs/eclipse-latest/tree/gh-pages repo
and the update site content on https://spotbugs.github.io/eclipse-latest/ is there again!!!

**Comment by iloveeclipse** [comment]
Let see what happens if I change other files in same commit: bingo, I can create PR. OMG. It creates PR but with old commit. I hate github web UI.

**Comment by iloveeclipse** [comment]
> Let see what happens if I change other files in same commit: bingo, I can create PR. OMG. It creates PR but with old commit. I hate github web UI.

I've managed to push directly to master, which is definitely not what I've wanted / expected. Sorry for that.

**Comment by JuditKnoll** [comment]
As far as I can see, this got solved, thanks to @iloveeclipse, so I'm closing it.
