### ISSUE TITLE
java.sql.Statement enquoteIdentifer and enquoteLiteral

### ISSUE THREAD

**Issue by jim-bentler** [spotbugs/spotbugs#2832]
There is no built-in support for java.sql.Statement enquoteIdentifer, enquoteLiteral, or enquoteNCharLiteral.  They should be defined as SQL_INJECTION_SAFE:
```
java/sql/Statement.enquoteLiteral(Ljava/lang/String;)Ljava/lang/String;:0|+SQL_INJECTION_SAFE
java/sql/Statement.enquoteIdentifier(Ljava/lang/String;Z)Ljava/lang/String;:1|+SQL_INJECTION_SAFE
java/sql/Statement.enquoteNCharLiteral(Ljava/lang/String;)Ljava/lang/String;:0|+SQL_INJECTION_SAFE
```

**Comment by gtoison** [comment]
I think you might be referring to the SQL injection taint analysis performed by the [FindSecBugs](https://github.com/find-sec-bugs/find-sec-bugs) project

**Comment by jim-bentler** [comment]
Sorry, yes, I wasn't paying attention and posted to the wrong project.

**Comment by jim-bentler** [comment]
Therefore, closing the issue.
