### ISSUE TITLE
checkstyle requires jdk 11 while sonar9.9.2 requires jdk 17

### ISSUE THREAD

**Issue by Bongani-coder65** [spotbugs/spotbugs#2862]
Hi Team,

We are upgrading SonarQube from 9.5 to 9.9.3.
will the checkstyle plugin work with jdk17 as Sonar 9.9.3 requires jdk17?

Please advise.

Regards,
Bongani

**Comment by JuditKnoll** [comment]
This is the GitHub for SpotBugs, which you can find under SonarQube as the FindBugs plugin, a completely different tool to the two you mentioned. Please ask this question at checkstyle or at SonarQube, as we can't help you in this question.
