### ISSUE TITLE
Crash in Sonarqube analysis

### ISSUE THREAD

**Issue by Jaff** [spotbugs/spotbugs#2863]
Running Java build through Sonarqube in Jenkins pipeline. Sonarqube version is 9.9.2-enterprise, 
Findbugs plugin 4.2.4 installed (with SpotBugs. 4.7.3)
During analysis, we get crash; stack-trace attached
[sonar_findbugs_crash.txt](https://github.com/spotbugs/spotbugs/files/14227205/sonar_findbugs_crash.txt)

,

**Comment by Jaff** [comment]
Ths appears to be an instance of [this issue](https://github.com/find-sec-bugs/find-sec-bugs/issues/705).

**Comment by gtoison** [comment]
This was fixed by https://github.com/find-sec-bugs/find-sec-bugs/pull/680 but unfortunately that is not released yet

**Comment by JuditKnoll** [comment]
[FindSecBugs](https://github.com/find-sec-bugs/find-sec-bugs) just got [released](https://github.com/find-sec-bugs/find-sec-bugs/releases/tag/version-1.13.0) yesterday, and the [sonar-findbugs](https://github.com/spotbugs/sonar-findbugs) plugin containing the new version just got [released](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.2.8) a few hours. So there is a new version with the fix.

**Comment by gtoison** [comment]
The new version of the plugin should be available once SonarSource approves https://github.com/SonarSource/sonar-update-center-properties/pull/510 (they're usually quite fast)
