### ISSUE TITLE
Gradle should update artifacts.xml and content.xml even though eclipsePlugin/build/site already has them

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#287]
It seems that Gradle does not update `artifacts.xml` and `content.xml` if `eclipsePlugin/build/site` directory already has them. `./gradlew clean` can be solution but it's better to solve problem from its root.

refs https://github.com/spotbugs/spotbugs.github.io/pull/28

**Comment by iloveeclipse** [comment]
See pull request #294

**Comment by KengoTODA** [comment]
Closed by #294
