### ISSUE TITLE
Rank value mismatch with the actual reported value

### ISSUE THREAD

**Issue by EhsanMashhadi** [spotbugs/spotbugs#2902]
Hi,

We have done a study to find if SpotBugs can predict bug severity using reported Rank values of SpotBugs. We have observed two scenarios:

1) SpotBugs finds a different possible bug in the studied method (than the actual bug) so it assigns a different rank to it.
2) SpotBugs reports a different Rank value than the actual bug severity value.

For example, [`accumulo-209_397f86f6`](https://github.com/bugs-dot-jar/accumulo/tree/bugs-dot-jar_ACCUMULO-209_397f86f6) project of Bugs.jar dataset has a bug with Major severity while SpotBugs report value 15-20 which means not major.

Do you have any insight on this?

**Comment by gtoison** [comment]
Could you please clarify what's the bug you're referring to?
It would be great if you could add the problematic code snippet, why you think it's a major bug and the result you're getting from SpotBugs

**Comment by gtoison** [comment]
I'm closing this because I have no idea what might the problem and there was no feedback
Please open a new issue or comment here if the problem persists
