### ISSUE TITLE
Gradle plugin prints Findbugs

### ISSUE THREAD

**Issue by kec2** [spotbugs/spotbugs#291]
Using the Gradle plugin spotbugs reports Fingsbugs in list of tasks. That is confusing.

build.gradle
```
plugins {
    id 'com.github.spotbugs' version '1.2'
}
tasks.each {
// print the name of the task
    println it
}
```

result:
```
...
task ':findbugsMain'
task ':findbugsTest'
...
```

**Comment by johnscancella** [comment]
The next time they publish the gradle plugin this should be fixed. They already changed the name with commit https://github.com/spotbugs/spotbugs/commit/63eecbd31eac5b3b7bbfa75795a149faa4698663

**Comment by iloveeclipse** [comment]
I think we are done here. Feel free to reopen if I've missed something.
