### ISSUE TITLE
Bring jFormatString library under the SpotBugs umbrella

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#295]
Currently, SpotBugs depends on `com.google.code.findbugs:jFormatString:3.0.0`, which (like the rest of FindBugs) is sadly no longer maintained.

IMHO, we should move this library over to the SpotBugs project. I don’t think we need a new top-level project, just a new sub-project below [spotbugs/spotbugs](https://github.com/spotbugs/spotbugs).

Does anyone know where the sources of `com.google.code.findbugs:jFormatString:3.0.0` live? I couldn’t find any SVN or Git repository for it. While we could use the [`*-sources.jar` from Maven Central](http://search.maven.org/remotecontent?filepath=com/google/code/findbugs/jFormatString/3.0.0/jFormatString-3.0.0-sources.jar) as a last resort, we would loose any tests that may have existed (at least to me, `jFormatString` seems like a very testable project, so hopefully it had tests).

**Comment by iloveeclipse** [comment]
See links on https://code.google.com/archive/p/j-format-string/source. You can even export it to github.

**Comment by sewe** [comment]
> See links on https://code.google.com/archive/p/j-format-string/source. You can even export it to github.

Thanks. Have been searching for `jformatstring` rather than `j-format-string` on Google Code, which turned up nothing.

Alas, the export to Github tool is [no longer available](https://code.google.com/export-to-github/export?project=j-format-string).

That being said, what do you think about moving this (like `spotbugs-annotations`) below [spotbugs/spotbugs](https://github.com/spotbugs/spotbugs)? I don't think `jFormatString` needs to necessarily share the SpotBugs release cycle, but having another top-level project seems like overkill at the moment.

**Comment by iloveeclipse** [comment]
> That being said, what do you think about moving this (like spotbugs-annotations) below spotbugs/spotbugs? I don't think jFormatString needs to necessarily share the SpotBugs release cycle, but having another top-level project seems like overkill at the moment.

Agree to both, BUT I've just stumbled on the license header in some files: "Copyright 2003-2007 Sun Microsystems, ... GNU GPL". This is incompatible with spotbugs LGPL. OMG.

**Comment by iloveeclipse** [comment]
Can we leave that crap "as is"? Where do we have dependencies to it (have no project code at the moment)?

**Comment by sewe** [comment]
> But maybe we can get rid of it altogether.

I had another look.

At the moment, we call jFormatString’s `Formatter.check(formatString, signatures)` which a list of signature. I think we can instead simply call `java.util.Formatter.format(formatString, dummyValues)` with a list of dummy values with the respective signatures. The `IllegalFormatException` thrown by `format` has a similarly rich subtype hierarchy to the exceptions thrown by `Formatter.check`, so we *may* piece together our `BugInstance` from it. Not 100% sure whether this will ultimately work, but may be worth a try. What do you think?

**Comment by iloveeclipse** [comment]
Checking via "exceptions" could work, but could also have some issues: 
- we will depend on the JRE implementation (anyone with IBM JDK?)
- we could have performance issues because of exceptions created all the time on poor code

**Comment by iloveeclipse** [comment]
Back to this request: the answer to the original question "Bring jFormatString library under the SpotBugs umbrella" is a definitive **NO**. 

Even more, I ask myself if it was a good idea to link FindBugs (LGPL) code directly to the GPL library (in FormatStringChecker) *and* **distribute** that library together with FindBugs.

Later is problematic and may cause legal issues => I've created #725.
