### ISSUE TITLE
Spotbugs 4.8.4 release notes missing in GitHub

### ISSUE THREAD

**Issue by kohlschuetter** [spotbugs/spotbugs#2956]
The current spotbugs 4.8.4 doesn't show up in https://github.com/spotbugs/spotbugs/releases.

It would be great to know what's changed.

**Comment by hazendaz** [comment]
Hi @kohlschuetter We had issues there which we are tracking elsewhere. A draft of 4.8.4 is up now.  Its missing only the eclipse zip and a sources zip.  For eclipse, if you must get it manually you can just check out this branch https://github.com/spotbugs/eclipse/tree/gh-pages to pick up 4.8.4 there manually for now.

**Comment by hazendaz** [comment]
Sorry we have it in draft so you cannot see it.  Hopefully we will have it fixed this weekend.

**Comment by hazendaz** [comment]
However, if you are just looking for changes, they are in the change log https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md

**Comment by JuditKnoll** [comment]
Unfortunately there were some issues during the automated parts of the release process, so the GitHub Release needed to be done manually (the other parts were running smoothly). We wanted to check it once more before publishing, this is why it took a bit longer, than usual. Now, it's available in the GitHub releases as well: https://github.com/spotbugs/spotbugs/releases/tag/4.8.4
