### ISSUE TITLE
Test classes for issue 574 are in the wrong package

### ISSUE THREAD

**Issue by kohlschuetter** [spotbugs/spotbugs#2958]
The four classes for issue https://github.com/spotbugs/spotbugs/issues/574 appear to be in the wrong java package.

This makes it unnecessarily difficult to develop in IDEs like Eclipse (we can ignore the error, but at what cost?)

All classes under [spotbugsTestCases/src/java/ghIssues/issue574](https://github.com/spotbugs/spotbugs/tree/4.8.4/spotbugsTestCases/src/java/ghIssues/issue574) are declared to be in `package ghIssues` instead of `package ghIssues.issue574`

Moreover, at least when importing the project into Eclipse, the `javax.xml.bind` annotations in [Issue574XmlElement.java](https://github.com/spotbugs/spotbugs/blob/4.8.4/spotbugsTestCases/src/java/ghIssues/issue574/Issue574XmlElement.java) cannot be resolved.

**Comment by hazendaz** [comment]
thanks for reporting, sending PR to fix now.
