### ISSUE TITLE
Filter: empty and ignores all

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs#296]
I have not confirmed this issue in spotbugs, I went to report in findbugs and saw the pointer. Since I assume this is a fork... if this is no longer valid with this fork, new thing feel free to close. I'll be investigating spotbugs more later.

the following was accidentally to our findbugs exclude configuration, turns out this ignores all bugs. I believe this configuration should throw some kind of invalid configuration error, or match nothing.

```
        <Match>
                <And>
                </And>
        </Match>
```

p.s. if there is an easy file I could add this test too, or test stub... I can try submitting a patch, not sure how your tests are laid out at this time.

**Comment by xenoterracide** [comment]
PR fixes the XSD to not allow that, but XML may not currently validate the XSD used, or require that one is used, both should be done. Since that's backwards incompatible can it be done in the upcoming 3.1.0? or maybe we add this schema to 3.1.0 and require it in 3.2.0?

**Comment by RahulNagekar** [comment]
These suggested changes to xsd were merged in the repository, I think we can close?

**Comment by gtoison** [comment]
I'll close that one since the xsd was modified to address the problem
