### ISSUE TITLE
supply an xsd

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs#297]
XSD's allow validation of  xml files but also allow smart editors to provide tag/property suggestions when your typing, or tell you if your xml is incorrect. I would love for an xsd for spotbugs, the lack of one has been the biggest pain point with findbugs. This could also solve #296 since you could mark an empty `<And>` as not valid with an xsd.

**Comment by iloveeclipse** [comment]
Have you seen this: https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/findbugsfilter.xsd? 

There are also other xsd files in same directory. Not sure what you are lookimg for.

**Comment by xenoterracide** [comment]
no, but I don't see it in the docs either? http://spotbugs.readthedocs.io/en/latest/filter.html#complete-example

**Comment by xenoterracide** [comment]
added a pull request to add it to the docs, though I'm not sure that's quite right, and doesn't resolve #296 as is because it thinks that an empty <And> is valid.

**Comment by iloveeclipse** [comment]
So can you fix the xsd that and/or rtc elements should have at least one child?

**Comment by xenoterracide** [comment]
possibly, I will look into that later, I have to read up on xsd again to do that.

**Comment by xenoterracide** [comment]
so, this is what it currently should be, however being that this is going into a new release should it be updated for that release? or would you rather I leave as is, looking into the element validation in the other ticket

```
<FindBugsFilter
		xmlns="http://findbugs.sourceforge.net/filter/3.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://findbugs.sourceforge.net/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/3.0.1/findbugs/etc/findbugsfilter.xsd">```

**Comment by xenoterracide** [comment]
^ fix for xsd, but let me know what you'd like me to do for this one

**Comment by JuditKnoll** [comment]
It seems like it was solved by https://github.com/spotbugs/spotbugs/pull/298 and https://github.com/spotbugs/spotbugs/pull/307.
