### ISSUE TITLE
Index out of bounds for empty switch

### ISSUE THREAD

**Issue by zbynek** [spotbugs/spotbugs#2995]
Since update to 4.8.4 I'm getting this
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
      At edu.umd.cs.findbugs.SwitchHandler.enterSwitch(SwitchHandler.java:90)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.analyzeMethod(FindDeadLocalStores.java:283)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.visitClassContext(FindDeadLocalStores.java:198)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1108)
      At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
      At java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
      At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
 ```
 when analyzing a generaated class that contains
 ```
 switch(jjstateSet[--i]) {
   default : break;
}
```
and
```
switch(jjmatchedKind) {
      default :
         break;
   }
```
It could make sense to optimize the code generator, but I think it's still worth fixing the OutOfBounds problem in SpotBugs.

Possibly related to https://github.com/spotbugs/spotbugs/pull/2828

**Comment by gtoison** [comment]
Thanks for reporting the issue, I tried reproducing it but it does not seem to crash for me with javac (OpenJDK21U-jdk_x64_windows_hotspot_21_35)
What compiler are you using?

**Comment by zbynek** [comment]
Java 11. I also checked with a minimal class that has just one empty switch and couldn't reproduce it. I'll try to create a minimal testcase (currently the problematic class has 450 lines).

**Comment by zbynek** [comment]
@gtoison I opened a [PR](https://github.com/spotbugs/spotbugs/pull/2996) for this. Maybe you can have a look and check if you can reproduce this issue with the sample code from that PR?
