### ISSUE TITLE
Travis: deploy SNAPSHOT artifact to Maven repository

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#30]
I'm working on my FindBugs plugin to build with latest SpotBugs, but currently no Maven repository provides `com.github.spotbugs:spotbugs:3.1.0-SNAPSHOT` so I need to install it by own like below:

```sh
$ cd findbugs && ant build srcJar && mvn install:install-file \
  -Dfile=lib/spotbugs.jar \
  -DpomFile=pom.xml \
  -Dsources=spotbugs-src.jar
```

It's not convenient, so I wish Travis CI deploys SNAPSHOT artifact to [Sonatype Maven repository](https://oss.sonatype.org/content/repositories/snapshots/) automatically. Maybe it's not so hard:

1. Create a script file which executes [`deploy:deploy-file`](http://maven.apache.org/plugins/maven-install-plugin/install-file-mojo.html)
2. Kick it at [after_success](https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle) only when Travis build SNAPSHOT version in `master` branch

Maybe we can refer https://github.com/JakeWharton/butterknife/commit/bac2342500971a3c6664629c3a63ca74d6e4819c as example.

How do you think? If it's OK, I will propose a PR.

**Comment by jsotuyod** [comment]
I think this is great, but first we would have to apply to the central repository, which we haven't done already.

I'll try to get this underway ASAP.

**Comment by henrik242** [comment]
@jsotuyod Did you get a reply from the central repository yet?

**Comment by jsotuyod** [comment]
Haven't applied yet, need to collect everyone's users.
