### ISSUE TITLE
Upgrade DOM4J from 1.6.1 to 2.1.0

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#300]
We are currently using [DOM4J](https://dom4j.github.io/) 1.6.1, which was [released in 2006](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22dom4j%22%20AND%20a%3A%22dom4j%22) and seems to have been the last member of the 1.x branch. I think it’s time for us to upgrade to version 2.0.1, which was [released in June 2017](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.dom4j%22%20AND%20a%3A%22dom4j%22).

AFAICT, the APIs of DOM4J 1.x and 2.x are almost identical, except for the latter’s use of generics (DOM4J 1.6.1 still runs on Java 1.4). As I don’t expect our users to use DOM4J directly in their detectors, I think its safe to perform this upgrade even for SpotBugs 3.1.0 (with a mention in the release notes, of course). What do you think?

**Comment by iloveeclipse** [comment]
The new version can always introduce regressions, I would prefer to release 3.1.0 with the old one and switch the dom4j version afterwards. We schould really get 3.1.0 out of the door as soon as possible, any possible regression would be conter-productive now.

**Comment by sewe** [comment]
@iloveeclipse Fair enough. Any ETA for 3.1.0? What’s still missing?

**Comment by iloveeclipse** [comment]
See #111

**Comment by iloveeclipse** [comment]
Will be in 3.1.2. The Dom4j API compatibility report is about~80%, but we don't expose it that much and it is not mission critical for 3rd party plugins, so far I can see. It doesn't make sense to wait years for 4.0 whatever release just to update a library.
