### ISSUE TITLE
Asked to end timing for class X but top of stack is class Y remaining stack is [edu.umd.cs.findbugs.log.Profiler

### ISSUE THREAD

**Issue by nongtingchao** [spotbugs/spotbugs#3039]
I didnt use Spotbugs as an plugin. I add it as a maven dependency and use its API(like the class FindBus2' main method).

`    private List<SpotbugsBugInstance> doAnalyze(String projectName, List<String> codes, String reportFile, Properties parameters) {
        try (FindBugs2 findBugs = new FindBugs2()) {
            TextUICommandLine commandLine = new TextUICommandLine();
            Project project = Optional.of(commandLine.getProject()).orElse(new Project());
            this.initProject(project, projectName, codes, parameters);
            String[] args = this.generateArgs(parameters, reportFile);
            findBugs.setProject(project);
            FindBugs.processCommandLine(commandLine, args, findBugs);
            boolean justPrintConfiguration = commandLine.justPrintConfiguration();
            if (justPrintConfiguration || commandLine.justPrintVersion()) {
                Version.printVersion(justPrintConfiguration);
                return null;
            }
            FindBugs.runMain(findBugs, commandLine);
            return this.getReportResult();
        } catch (Throwable th) {
            log.error("error ", th);
            throw new RuntimeException(th);
        }
    }`

It works with new  FindBugs2(), bug when I run with FindBugs2(new ThreadPoolExecutor(4, 8, 0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>()))) and excption occured:

`Caused by: java.lang.AssertionError: Asked to end timing for class edu.umd.cs.findbugs.NonReportingDetectorToDetector2Adapter but top of stack is class edu.umd.cs.findbugs.DetectorToDetector2Adapter, remaining stack is [edu.umd.cs.findbugs.log.Profiler$Clock@53fd01ea, edu.umd.cs.findbugs.log.Profiler$Clock@5d3af5e5, edu.umd.cs.findbugs.log.Profiler$Clock@59056a9a, edu.umd.cs.findbugs.log.Profiler$Clock@1c07ffde, edu.umd.cs.findbugs.log.Profiler$Clock@274e4fe5, edu.umd.cs.findbugs.log.Profiler$Clock@2dd10334, edu.umd.cs.findbugs.log.Profiler$Clock@5f72edae, edu.umd.cs.findbugs.log.Profiler$Clock@7c280091]
	at edu.umd.cs.findbugs.log.Profiler.end(Profiler.java:274)
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1114)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	... 3 common frames omitted`

What went wrong with multi thread ？

environment: JDK 8, Spotbugs: 4.7, IDE: IntelliJ IDEA 2024

**Comment by gtoison** [comment]
The SpotBugs internal API is not thread safe. I'm not quite sure what might be the problem (or what you're doing) but you shouldn't run it in an ExecutorService

**Comment by nongtingchao** [comment]
@gtoison I see, Thank you. It has ExecutorService initlizer in constructor so I thought It can run with ExecutorService, my bad.
