### ISSUE TITLE
Here's a sample code snippet to check if a given string matches a date format

### ISSUE THREAD

**Issue by Gokul-2004** [spotbugs/spotbugs#3067]
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class DateValidator {
    public static boolean isValidDate(String dateStr, String format) {
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        sdf.setLenient(false);
        try {
            Date date = sdf.parse(dateStr);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    public static void main(String[] args) {
        String dateStr = "2024-08-05";
        String format = "yyyy-MM-dd";

        if (isValidDate(dateStr, format)) {
            System.out.println(dateStr + " is a valid date.");
        } else {
            System.out.println(dateStr + " is not a valid date.");
        }
    }
}

**Comment by JuditKnoll** [comment]
Can you please elaborate? Did you encounter a FP or an NP in this code snippet? In connection with which bug? Which SpotBugs version are you using?

**Comment by JuditKnoll** [comment]
Closing this issue as there was no info provided about the problem, and haven't received an answer. Please reopen it or comment here with some clarification if you don't agree.
