### ISSUE TITLE
findbugs/bin not committed?

### ISSUE THREAD

**Issue by mebigfatguy** [spotbugs/spotbugs#31]
i see that there's a .gitignore entry for findbugs/bin. Curious how this is being populated, i must have missed something. For instance git log findbugs/bin/findbugs.ico shows nothing... how does this work?

**Comment by jsotuyod** [comment]
The folder is ignored and doesn't exists on the repo. They were removed back in 2009 (`git log findbugs/bin/`). It's being created and populated as part of the build process (of couse it generates multiple output folders, the build chaos is already mentioned in #4 )

Currently, those files are generated by the `scripts` task on `findbugs/build.xml`, which just copies them from `src/scripts/*/`. You can get the history for those source files directly, for instance `git log findbugs/src/scripts/windows/findbugs.ico`
