### ISSUE TITLE
The documation on the annotations should state which depdency is required

### ISSUE THREAD

**Issue by obfischer** [spotbugs/spotbugs#3110]
As user of Spotbugs, who would like to use the annotation of Spotbugs,
I would like to know the artifact coordinates of the jar containing the annotations,
so that I can include them in my project quite easily.

*Acceptance Criterias*
- The artifact coordinates are easy to find on or via the page [_Annotations_](https://spotbugs.readthedocs.io/en/latest/annotations.html) in the documentation.

**Comment by hazendaz** [comment]
@obfischer Feel free to contribute to the documentation.  I think that location you called out seems appropriate.  If not aware, the GAV is: com.github.spotbugs:spotbugs-annotations.  It does pull in the old jsr305 jar.

**Comment by gtoison** [comment]
@obfischer here's a proposed update to the documentation (see #3137): https://spotbugs--3137.org.readthedocs.build/en/3137/annotations.html
