### ISSUE TITLE
FI_NULLIFY_SUPER mapped to CWE 586, but should be 568

### ISSUE THREAD

**Issue by davewichers** [spotbugs/spotbugs#3123]
This rule flags: "Finalizer nullifies superclass finalizer", i.e., doesn't call super.finalize().

But it is mapped to: CWE-586: Explicit Call to Finalize().

However, I think this is the correct mapping: CWE-568: finalize() Method Without super.finalize()

UPDATE: The rule: FI_MISSING_SUPER_CALL, which says: "Finalizer does not call superclass finalizer" should be mapped to 568 as well.

They both talk about finalizers but I think its mapped to the wrong one.

Also, where are these rules defined in the codebase and/or the CWE mappings defined? I am aware of some other rules that I don't think are properly mapped as well.  If there is a single mapping file, I could provide feedback on multiple rules that are either missing CWE mappings, but should have them, or are mapped to CWEs MITRE has marked as DEPRECATED/PROHIBITED, like this one as an example: https://cwe.mitre.org/data/definitions/218.html. There is a spotbugs rule that is mapped to CWE 218. 218 says: it is a duplicate of CWE-493, so that rule should be mapped to CWE 493 instead. This rule is MS_PKGPROTECT.

Ideally, someone would go through all the CWE mappings and move them to non-deprected, non-prohibited CWEs.

**Comment by JuditKnoll** [comment]
The rules are defined as Bug Patterns in the [findbugs.xml](https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/findbugs.xml#L722) file. The CWE can be given by `cweid`. The CWE can also be given at the Bug Codes [in the same file](https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/findbugs.xml#L692), which seems to be the case in the examples you mentioned, as there is [no CWE given to FI_NULLIFY_SUPER](https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/findbugs.xml#L861) or to [MS_PKGPROTECT](https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/findbugs.xml#L947), but there are to their bug codes.
The description of the Bug Patterns are in the [messages.xml](https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/messages.xml#L1842) file.
Feel free to contribute to the project 😄

**Comment by gtoison** [comment]
@davewichers I've submitted PR #3124 to show what the fixes would look like

**Comment by gtoison** [comment]
This was fixed by #3124 in the upcoming release of SpotBugs
