### ISSUE TITLE
Some rule abbrev values are identical for different rules

### ISSUE THREAD

**Issue by davewichers** [spotbugs/spotbugs#3125]
I notice that rules have both 'abbrev' values and 'type' values. If it is intended that the 'abbrev' be a unique/shorter version of the type, then I would expect that rules should NOT have the same 'abbrev' when they are of different types, unless I'm misunderstanding the purpose of abbrev.

For example, there is the rule: CORRECTNESS:INT_BAD_COMPARISION_WITH_INT_VALUE with abbrev INT, but there is also: STYLE:INT_VACUOUS_COMPARISON with the same abbrev INT. And I believe there are others with duplicate abbrevs too.

Another example is: I18N:DM_DEFAULT_ENCODING with abbrev 'Dm' and there are actually multiple other rules in different categories with the same abbrev, like: BAD_PRACTICE:DM_EXIT and I18N:DM_CONVERT_CASE (which is in the SAME category).

Is the intent that the abbrev be unique across all rules, or only within a category? Seems like it should be unique across all rules, otherwise this is confusing.

**Comment by gtoison** [comment]
I'm not sure how we ended up with 'abbrev' (it is indeed confusing) but you can think of it as a 'bug category'

**Comment by davewichers** [comment]
OK. Thanks for clarifying.
