### ISSUE TITLE
Add alternative permissive license to `spotbugs-annotations` only

### ISSUE THREAD

**Issue by ppkarwasz** [spotbugs/spotbugs#3144]
While I understand why the Spotbugs project as a whole uses [LGPL-2.1](https://opensource.org/license/LGPL-2.1), would it be possible to make the [`spotbugs-annotations`](https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs-annotations) artifact available under multiple licenses? For example LGPL-2.1 and [Apache-2.0](https://opensource.org/license/apache-2-0) would be a nice combination.

In the [Apache Log4j project](https://logging.apache.org/log4j/2.x/) we have annotated our code extensively with SpotBugs annotations. It was brought to our attention that LGPL-2.1 falls under [Category X of the Apache 3rd Party License Policy](https://www.apache.org/legal/resolved#category-x), which prevents `spotbugs-annotations` from being distributed with any Apache binary distribution. This is not a problem for us, since we are a library and we don't distribute our dependencies, but it could be a problem for our users.

Disclaimer: I am not a lawyer and I don't have the competence to interpret the Apache Software Foundation policy. If you believe the policy is wrong and `spotbugs-annotations` can be distributed in any product (even commercial ones) without placing any restriction on the work itself, I can open a ticket with the ASF legal team.

**Comment by gtoison** [comment]
The project was originally called FindBugs and some of its original authors are no longer associated with it, or at least not contributing actively.
As far as I know relicensing even a small portion of the project would require at the very least permission from the authors. I know that Hibernate is attempting to dual license LGPL/Apache (from currently LGPL) and they are asking permission to contributors. Even though I only contributed some unit tests they have asked my permission, so most probably they are asking everybody who committed something.
Realistically we're not going to get permission from all authors (and from the University of Maryland) to relicense.

**Comment by ppkarwasz** [comment]
@gtoison, thanks for the explanation.

Feel free to close the issue.

**Comment by ThrawnCA** [comment]
> This is not a problem for us, since we are a library and we don't distribute our dependencies, but it could be a problem for our users.

I'm not a lawyer either, but...to the best of my knowledge, end users should be able to include the SpotBugs Annotations library in an application that's licensed differently, even a proprietary application, provided that they aren't dealing with SpotBugs itself in a way that would violate the licence.

Eg if they modify `spotbugs-annotations` then they need to release their modified version under LGPL. But that doesn't seem related to their use of Log4J, so it shouldn't be something Log4J licensing needs to address.
