### ISSUE TITLE
Cannot convert the provided notation to a File or URI: classesDirs

### ISSUE THREAD

**Issue by boris-petrov** [spotbugs/spotbugs#320]
The full error is:

```
Cannot convert the provided notation to a File or URI: classesDirs.            
The following types/formats are supported:                                     
  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.                                                                             
  - A String or CharSequence URI, for example 'file:/usr/include'.             
  - A File instance.                   
  - A Path instance.                   
  - A URI or URL instance.
```

This appears when using Gradle plugin version 1.3. Probably this commit broke it:

https://github.com/spotbugs/spotbugs/commit/850dc13c1d7d0727024f13814b6e26d1b2ff6371

**Comment by boris-petrov** [comment]
Well, I updated the plugin:

```diff
-id 'com.github.spotbugs' version '1.2'
+id 'com.github.spotbugs' version '1.3'
```

And the plugins I use:

```diff
-findbugs "com.github.spotbugs:spotbugs:$spotBugsVersion"
-findbugs configurations.findbugsPlugins.dependencies
-findbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.7.1'
-findbugsPlugins 'com.mebigfatguy.fb-contrib:fb-contrib:7.0.3.sb'
-findbugsPlugins 'jp.skypencil.findbugs.slf4j:bug-pattern:1.3.0@jar'
-findbugsPlugins 'com.monits:findbugs-plugin:0.2.0@jar'
+spotbugs "com.github.spotbugs:spotbugs:$spotBugsVersion"
+spotbugs configurations.spotbugsPlugins.dependencies
+spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.7.1'
+spotbugsPlugins 'com.mebigfatguy.fb-contrib:fb-contrib:7.0.3.sb'
+spotbugsPlugins 'jp.skypencil.findbugs.slf4j:bug-pattern:1.3.0@jar'
+spotbugsPlugins 'com.monits:findbugs-plugin:0.2.0@jar'
```

And then when I run `gradle spotbugsSourceSet` it fails with the above error. Am I missing something? spotBugsVersion is '3.1.0-RC5'.

**Comment by iloveeclipse** [comment]
> And then when I run gradle spotbugsSourceSet it fails with the above error.

Is this your own project build, or where `spotbugsSourceSet` is coming from?
Please provide *full* steps to reproduce.

**Comment by boris-petrov** [comment]
```gradle
buildscript {
	repositories {
		mavenCentral()
	}
}

plugins {
	id 'com.github.spotbugs' version '1.3'
}

apply plugin: 'java'

sourceSets {
	foo
}

dependencies {
	spotbugs 'com.github.spotbugs:spotbugs:3.1.0-RC5'
}
```

Put this in a `build.gradle` file. Execute `gradle spotbugsFoo`.

**Comment by MartyIX** [comment]
After upgrading from RC4 to RC5, as Boris did, I've been experiencing the same error. Just to let you know that he is not alone. Unfortunately, my project is fairly large to strip it down to core issue.

**Comment by iloveeclipse** [comment]
Strange. Gradle 4 says it knows `output.classesDirs` : -
- https://docs.gradle.org/current/userguide/userguide_single.html#sec:working_with_java_source_sets
- https://docs.gradle.org/current/userguide/userguide_single.html#sec:source_set_properties

@KengoTODA : Should we use `java.outputDir`?

**Comment by iloveeclipse** [comment]
Should we revert 850dc13 and reopen #292?

**Comment by cdietrich** [comment]
`classesDirs` is a list (in gradle 4 you can have different output dirs e.g. for java and scala)

**Comment by iloveeclipse** [comment]
Wait a moment: 850dc13 and `classesDirs` affect **only** jacocoTestReport task of eclipsePlugin-junit and eclipsePlugin-test projects, the problem is probably coming from 7141ab8 and 313ea5b / #299.

**Comment by cdietrich** [comment]
yes @iloveeclipse

**Comment by iloveeclipse** [comment]
@boris-petrov : can you please build from HEAD and verify that the error is solved? Thanks.

**Comment by KengoTODA** [comment]
And if you have idea to introduce smoketest or e2e test to this gradle plugin, please try to propose MR. Currently we have [test cases](https://github.com/spotbugs/spotbugs/blob/master/gradlePlugin/src/test/java/com/github/spotbugs/SpotBugsPluginTest.java) but it cannot help us to find problem like this.

**Comment by boris-petrov** [comment]
@iloveeclipse - I'm not sure if I'm doing everything right, but I'm getting a:

```
Caused by: java.lang.NoClassDefFoundError: com/google/common/io/Resources
       at com.github.spotbugs.SpotBugsPlugin.loadToolVersion(SpotBugsPlugin.java:76)
       at com.github.spotbugs.SpotBugsPlugin.createExtension(SpotBugsPlugin.java:70)
```

Could you provide me the steps to do after cloning the repo? I did a `gradle build`, saw the resulting `jar` in the `gradlePlugin/build/libs` dir, and then put in my build gradle:

```gradle
buildscript {
	repositories {
		maven {
			url '/home/boris/code/spotbugs/gradlePlugin/build/libs'
		}
	}

	dependencies {
		classpath 'com.github.spotbugs:gradlePlugin:1.4-SNAPSHOT'
	}
}

apply plugin: 'com.github.spotbugs'
```

If I've done it right, that's the error I receive.

@KengoTODA - unfortunately I'm absolutely not aware of how Gradle plugins are tested, I'm sorry.

**Comment by KengoTODA** [comment]
Thanks @boris-petrov , I'm trying to test in #320.
