### ISSUE TITLE
Sonar scanner raises IllegalArgumentExceptions for 20 findbug detectors on one class

### ISSUE THREAD

**Issue by camproto** [spotbugs/spotbugs#3208]
## Issue Description

Sonar scanner raises IllegalArgumentException for 20 findbugs detectors for one class. The error message "can't push void" does not help me to see the reason. Therefore I cannot fix the class source code.

See log extract.
[sonar-scanner-java-findbugs-exception-log.txt](https://github.com/user-attachments/files/17916506/sonar-scanner-java-findbugs-exception-log.txt)

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | Community Edition - Version 9.9.3 (build 79811)  |
| sonar scanner     | 5.0.0.4389 |
| Sonar-FindBugs     | findbugs 4.2.9   |
| Maven              | mvnw 3.9.9   |
| Java               | RedHat_JDK17.0.5.0.8   |

**Comment by gtoison** [comment]
So this should be fixed in the upcoming release of SpotBugs

**Comment by camproto** [comment]
Thank you very much for your fast fix! Great effort :-)

**Comment by gtoison** [comment]
And I forgot to say that once SpotBugs is released, the SonarQube plugin will also need to upgrade and release a new version
