### ISSUE TITLE
All command line scripts are broken

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#323]
After commit 8b518ec0 all command line scripts do not forward arguments, so all command line tasks work now without any arguments. This is a blocker.

They all should append `$@` at the end of the new command line to forward arguments to `fbwrap` script.

**Comment by sewe** [comment]
Sorry about that. I’ll fix this ASAP.

**Comment by iloveeclipse** [comment]
Closed via #324.
