### ISSUE TITLE
spotbugs.jar and eclipse-plugin.jar contain unexpected 3rd party classes

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#326]
Don't know how this happened, but Eclipse plugin main jar `eclipse-plugin.jar` contains not only spotbugs classes, but all the other libraries dumped in one jar. I've stumbled over it as I've searched `org.w3c.dom.Node` class in Eclipse where spotbugs was installed.

Same for `spotbugs.jar`, which seem to contain a copy of the BCEL jar.

This is clearly not what we want. Gradle build seem to re-package all dependent jars into the single one. I would prefer we would clean this up for 3.1.0, it looks messy and probably could cause some unexpected side effects.

**Comment by KengoTODA** [comment]
> Same for spotbugs.jar, which seem to contain a copy of the BCEL jar.

This is necessary because bcel is not published to Maven central. Refs #89

**Comment by iloveeclipse** [comment]
A-ha. So the proposal would be to fix the **maven** distribution, so that only this is affected.

**Comment by iloveeclipse** [comment]
@KengoTODA : is this a big problem if we would publish to maven released BCEL jar with **our** coordinates and refer to this one, instead of putting all BCEL classes inside our `spotbugs.jar`?

Additionally, `spotbugs.jar` contained `spotbugs-annotations.jar`. Is this one also not available on maven?

**Comment by iloveeclipse** [comment]
OK, I will change the patch to fix Eclipse plugin only, and for `spotbugs.jar` I've created #327.

**Comment by sewe** [comment]
> Additionally, `spotbugs.jar` contained `spotbugs-annotations.jar`. Is this one also not available on maven?

It is available on Maven Central. We build it and put it there. ;-)

Also, the `spotbugs` POM has a correct `compile`-scoped dependency on `spotbugs-annotations`, so Maven will pick the annotations up from Maven Central. IMHO, there’s no need to include them in the `spotbugs` JAR again.

**Comment by iloveeclipse** [comment]
Jep. I will also update the patch to fix eclipse plugin and remove annotations from spotbugs main jar. The BCEL hack is then for  #327 .

**Comment by sewe** [comment]
> Jep. I will also update the patch to fix eclipse plugin and remove annotations from spotbugs main jar.

Done and merged.
