### ISSUE TITLE
Add LICENSE file to the project

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#332]
This would show "LGPL" badge in the header of the "code" section.

**Comment by KengoTODA** [comment]
License of what? SpotBugs? If so, this is duplicated with #174.

**Comment by iloveeclipse** [comment]
Not quite same. This is for github, so that it can pick up the license file automatically and show the license abbreviation on the first project page in the top right corner.

**Comment by KengoTODA** [comment]
Really? https://github.com/spotbugs/spotbugs-archetype has LICENSE in top directory but GitHub doesn't display license in its page. I will search the detailed condition...

**Comment by KengoTODA** [comment]
Confirmed that the commit in #174 should be enough.
https://help.github.com/articles/licensing-a-repository/

I also confirmed that new LICENSE file format is same with the generated one by GitHub license template.
https://help.github.com/articles/adding-a-license-to-a-repository/
