### ISSUE TITLE
Problem dealing with lambda

### ISSUE THREAD

**Issue by testn** [spotbugs/spotbugs#338]
> [INFO] Fork Value is true
>      [java] The following classes needed for analysis were missing:
>      [java]   call
>      [java]   apply
>      [java]   handle
>      [java]   iterator
>      [java]   as
>      [java]   test
>      [java]   get
>      [java] Missing classes: 7

**Comment by KengoTODA** [comment]
Thanks for your report, please check [CONTRIBUTING.md](https://github.com/spotbugs/spotbugs/blob/master/CONTRIBUTING.md) and try to share test case to reproduce.

**Comment by kenzierocks** [comment]
I've written a failing test case: https://github.com/kenzierocks/spotbugs/commit/046dc7bc4ae2b5518fac37097a0a96b973055f2e

**Comment by kenzierocks** [comment]
I have a potential fix for this, which is to just bail if we try to check `invokedynamic` instructions. `indy` is currently only used for internal calls, not user-defined methods, so this shouldn't hurt bug finding.  https://github.com/kenzierocks/spotbugs/commit/2fa8b5839b0a330aecfb108070d3659d39d124a6

**Comment by iloveeclipse** [comment]
Looks good. Can you please set a PR?

**Comment by testn** [comment]
thanks @kenzierocks
