### ISSUE TITLE
Many warnings during Travis build

### ISSUE THREAD

**Issue by javabeanz** [spotbugs/spotbugs#340]
many warnings, mainly for missing javasoc. maybe treat them as failing ?

**Comment by iloveeclipse** [comment]
Feel free to provide a PR with fixed javadoc :)

**Comment by iloveeclipse** [comment]
I think we can't fix **all** Javadoc warnings for the spotbugs main and annotations libraries, because the Javadoc isn't in a good shape and there are too many missing parameters etc.

I've fixed all smaller subprojects and plan to set a PR in a moment.
