### ISSUE TITLE
[docs][suggestion] Explain how to run gradle plugin

### ISSUE THREAD

**Issue by MartyIX** [spotbugs/spotbugs#342]
Hi,

I was trying to run Spotbugs as a complete newbie and one fundamental problem after adding Spotbugs configuration to my build.gradle was "how to actually run the gradle plugin". 

Maybe it would be worth adding a sentence explaining this to http://spotbugs.readthedocs.io/en/latest/migration.html or any other page of the documentation.

Best regards,
Martin

**Comment by KengoTODA** [comment]
Could you tell us why [current code snippet](http://spotbugs.readthedocs.io/en/latest/migration.html#findbugs-gradle-plugin) is not enough for you?

**Comment by MartyIX** [comment]
@KengoTODA  I miss information about: `./gradlew check` as this is the way to run the plugin, isn't it?

**Comment by KengoTODA** [comment]
What I know is `./gradlew spotbugsMain`

https://github.com/spotbugs/spotbugs/blob/e641584/gradlePlugin/src/test/java/com/github/spotbugs/SpotBugsPluginTest.java#L43

**Comment by MartyIX** [comment]
Ah. I didn't know that. It is your decision if you want to expand the documentation a bit.

**Comment by KengoTODA** [comment]
@johnscancella Does SpotBugs Gradle plugin runs `spotbugsMain` and `spotbugsTest` at `check`?
I found that FindBugs Gradle plugin adds dependency from `check` to both of `findbugsMain` and `findbugsTest`.

https://docs.gradle.org/3.4/userguide/findbugs_plugin.html#sec:findbugs_tasks

To keep compatibility, I think it is better to add task dependency like them. If we don't add, I will improve document for gradle plugin.

**Comment by johnscancella** [comment]
@KengoTODA to answer your question: yes, it includes `spotbugsTest` and `spotbugsMain` in the `check` task just like `findbugs` does. 

I directly copied gradle's `findbugs` plugin so I am not sure exactly how it goes about adding it to the `check` task. I can dig into it more if we need to figure out how it adds it to the `check` task

**Comment by KengoTODA** [comment]
Thanks @johnscancella, I also confirmed that `check` triggers them.

@MartyIX I will create an isolated page to explain about this plugin, and link it from migration page.
