### ISSUE TITLE
Minimum Eclipse version confusion

### ISSUE THREAD

**Issue by Bananeweizen** [spotbugs/spotbugs#354]
The Eclipse plugin is a bit confusing regarding which versions of Eclipse are intended to be supported. The build instructions say to build against an Eclipse 4.6 target platform. The manifest.template however declares org.eclipse.ui 3.6 as the only dependency with a version number.

If people really build against a 4.6 target platform, they will start using API that is not available in older versions. That in turn will lead to the Eclipse plugin binary being runtime incompatible with older Eclipse versions, although its manifest allows installation with Eclipse 3.6 or better.

Therefore both the instructions as well as the manifest.template should refer to the same version. And that version number should be declared by some committer, probably @iloveeclipse.

**Comment by iloveeclipse** [comment]
Right, 4.6 should be minimum. Please feel free to patch any places where we still refer to something different. Thanks for reporting/patching. 
**NB** please note that Eclipse platform version differs from versions of single bundles, so org.eclipse.ui 3.6 != Eclipse 3.6. So be careful.

**Comment by iloveeclipse** [comment]
@Bananeweizen : see PR #359. If you have seen other places, please point us to them.
