### ISSUE TITLE
"Resource not found" error if running with old Gradle < 1.4

### ISSUE THREAD

**Issue by milesgould** [spotbugs/spotbugs#357]
With a `build.gradle` containing only the following:

```
plugins {
  id "com.github.spotbugs" version "1.3"
}
```

(i.e., the build-script snippet from https://plugins.gradle.org/plugin/com.github.spotbugs), I get the following output from `gradlew.bat --info`:

```
Starting Build
Settings evaluated using settings file 'C:\Users\m.gould\Documents\GitHub\ilab-ww\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\m.gould\Documents\GitHub\ilab-ww\build.gradle'.
Included projects: [root project 'ai']
Evaluating root project 'ai' using build file 'C:\Users\m.gould\Documents\GitHub\ilab-ww\build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\m.gould\Documents\GitHub\ilab-ww\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.spotbugs', version: '1.3']
> Failed to apply plugin [id 'com.github.spotbugs']
   > resource spotbugs-gradle-plugin.properties not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
```

The output of `gradlew.bat --version` is as follows:

```
------------------------------------------------------------
Gradle 2.9
------------------------------------------------------------

Build time:   2015-11-17 07:02:17 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Windows 10 10.0 amd64
```

Things I have tried:

 - Installing version 1.2 instead (same error)
 - Creating files called `spotbugs-gradle-plugin.properties` in my project's root directory, and under every `resources` directory I could find (same error)
 - Using the pre-2.1 build-script syntax given on that page (different error! "Could not generate a proxy class for class com.github.spotbugs.SpotBugsTask.")
 - Running `jar tf` on the downloaded `gradlePlugin.jar` - the file `spotbugs-gradle-plugin.properties` is indeed present, at the root.

What am I doing wrong?

**Comment by milesgould** [comment]
I have also tried deleting `$HOME/.gradle` and `$PROJECT_ROOT/.gradle` - same error.

**Comment by milesgould** [comment]
Update! I updated my Gradle version to 4.1, and the plugin is now loading! `gradlew spotbugsMain` still fails, but for a totally different reason. I'm closing this issue.

**Comment by iloveeclipse** [comment]
I'm not Gradle expert, but you are really using Gradle 2.9? May be you could try with 4.1?

**Comment by iloveeclipse** [comment]
Damn, I was 12 seconds too late :)

**Comment by milesgould** [comment]
:-)

**Comment by milesgould** [comment]
Though if the plugin requires a recent Gradle version, you should probably stop providing installation instructions for Gradle versions below 2.1...

**Comment by iloveeclipse** [comment]
Can you please point us at the place where we are doing that? Thanks. BTW patches are welcome.

**Comment by milesgould** [comment]
The instructions I found were at https://plugins.gradle.org/plugin/com.github.spotbugs, though I don't know if that page is under your control. Another possibility would be to document the minimum Gradle version at http://spotbugs.readthedocs.io/en/latest/gradle.html. I'd be happy to make the change, but I'm not sure how to work out what the minimum Gradle version is - does it have to match the version specified at https://github.com/spotbugs/spotbugs/blob/master/build.gradle#L36 ?

**Comment by milesgould** [comment]
[About to go home for the weekend, will be unable to respond before Monday.]

**Comment by KengoTODA** [comment]
> The instructions I found were at https://plugins.gradle.org/plugin/com.github.spotbugs, though I don't know if that page is under your control. 

Its content is not under our control. What we provide for this page is just a version.

> I'm not sure how to work out what the minimum Gradle version is - does it have to match the version specified at https://github.com/spotbugs/spotbugs/blob/master/build.gradle#L36 ?

No. It is version to build SpotBugs itself.

**Comment by KengoTODA** [comment]
I cannot find the way to declare supported Gradle version in custom Gradle plugin. Maybe we need to check its version in our plugin manually, and throw exception if it runs on too old Gradle.

**Comment by KengoTODA** [comment]
I confirmed that current plugin supports 4.x only. It cannot work with 2.x nor 3.x. 

Here is test code: https://github.com/KengoTODA/spotbugs/commit/e2e35be3cb6b98c7db26ad695a1dfad4ff154e9f

**Comment by KengoTODA** [comment]
Can we close this issue?

**Comment by iloveeclipse** [comment]
Is there any way we can detect too old Gradle version and print some useful message?

**Comment by KengoTODA** [comment]
@iloveeclipse I've proposed #422, please check
