### ISSUE TITLE
Logo idea(s)

### ISSUE THREAD

**Issue by h3xstream** [spotbugs/spotbugs#36]
This is not an urgent issue. Here is a proposal for a logo.

![v4](https://cloud.githubusercontent.com/assets/593130/20687960/9ced065e-b58c-11e6-9c04-062443ca95c5.png)

Public domain icons used: [Magnifying glass](https://pixabay.com/en/magnifying-glass-eyeglass-hand-glass-311511/) and [Bug](http://fontawesome.io/icon/bug/)
The font used is [Patua One](https://fonts.google.com/specimen/Patua+One)

This thread is slightly related to the website (re)branding #5.

------

Initial sketch:

![spotbug](https://cloud.githubusercontent.com/assets/593130/20544543/88b05050-b0d8-11e6-9e48-575a80f97d5b.png)

**Comment by jsotuyod** [comment]
I like it! 

I'd probably keep the red on the bug to make it a little more lively / call attention. 

The magnifying glass looks a little pixelated on my phone, which ia weird since the original is an svg... Do you see it well on your machine?

**Comment by h3xstream** [comment]
Yes this is a compressed and rendered PNG.. It would need to be scaled properly.

**Comment by jsotuyod** [comment]
Feel free to push this forward and submit a PR changing it. I know I don't feel attached to the current logo, which I just put together in a few minutes; and doubt the other guys feel any different.

One thing 'though, when you submit the PR I think it would be great to include not only the exported pngs for different sizes used, but to include the raw files (Gimp's xcf, Photoshops' PSD or whatever it is you are using), so it's easy to work on in the future as needed.

**Comment by mebigfatguy** [comment]
like it

**Comment by h3xstream** [comment]
Where should I place the logo and its project files? (The first version was made in Paint.Net `.pdn`)

I would assume the **spotbugs.github.io** or a new repo..

**Comment by mebigfatguy** [comment]
if you expect to do a bunch of edits, or hope to increase the amount of artwork, then a new repo is fine, otherwise spotbugs.github.io is fine to. really whatever you like is ok with me.

**Comment by KengoTODA** [comment]
I will close this issue, because following two should be enough to close.

* https://github.com/spotbugs/spotbugs/pull/126
* https://github.com/spotbugs/spotbugs.github.io/pull/11

**Comment by h3xstream** [comment]
For reference:
I generated the logo in few size and I have attached the Paint.Net project file. https://github.com/spotbugs/spotbugs.github.io/tree/master/images/logos

If in the future, a high resolution version is needed. I would advised to restarted from scratch and reused the same font and the clipart reference above.

@KengoTODA This image could be use for the Github Icon of the project:
https://github.com/spotbugs/spotbugs.github.io/blob/master/images/logos/spotbugs_icon_only_zoom_256px.png

**Comment by KengoTODA** [comment]
@h3xstream 
Really nice, maybe we should ask @jsotuyod to use this icon.

**Comment by jsotuyod** [comment]
@KengoTODA @h3xstream done!! it may need to invalidate cache to see it 'though.
