### ISSUE TITLE
Support for registering multiple instances of BugReporter

### ISSUE THREAD

**Issue by osiegmar** [spotbugs/spotbugs#366]
Currently, `edu.umd.cs.findbugs.FindBugs2#setBugReporter` only supports registering a single BugReporter instance. Sometimes it would be very comfortable to register multiple bug reporters (e.g. Console/Log & HTML & XML Reporter).

I tried to work around this shortcoming by creating a custom BugReporter instance that delegates (multiplexes) to a series of other bug reporters. Basically that works, but the metric section of the reports is empty (e.g. "0 lines of code analyzed" in HTML report, missing PackageStats and FindBugsProfile in XML report). This is because FindBugs expects a single instance of `edu.umd.cs.findbugs.ProjectStats` and `edu.umd.cs.findbugs.BugCollection`. And those currently cannot be shared between BugReport instances.

**Comment by KengoTODA** [comment]
Closed by #1776, so the next release v4.5.0 will support this behavior.

Instead of setting multiple `BugReporter` instances, wrap them all by a `BugReportDispatcher` instance, and set to the `IFindBugsEngine` instance.
