### ISSUE TITLE
FindNullDeref fails with "DataflowAnalysisException: can't get position -1 of stack" on methods with lambda

### ISSUE THREAD

**Issue by nimbals1** [spotbugs/spotbugs#371]
Getting Error generating derefs for xx.yyyy.zzzzzzzz
    edu.umd.cs.findbugs.ba.DataflowAnalysisException: can't get position -1 of stack

**Comment by nimbals1** [comment]
edu.umd.cs.findbugs.ba.DataflowAnalysisException: can't get position -1 of stack
      At edu.umd.cs.findbugs.ba.Frame.getStackValue(Frame.java:250)
      At edu.umd.cs.findbugs.ba.Hierarchy.resolveMethodCallTargets(Hierarchy.java:743)
      At edu.umd.cs.findbugs.ba.npe.DerefFinder.getAnalysis(DerefFinder.java:141)
      At edu.umd.cs.findbugs.classfile.engine.bcel.UsagesRequiringNonNullValuesFactory.analyze(UsagesRequiringNonNullValuesFactory.java:50)
      At edu.umd.cs.findbugs.classfile.engine.bcel.UsagesRequiringNonNullValuesFactory.analyze(UsagesRequiringNonNullValuesFactory.java:31)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
      At edu.umd.cs.findbugs.ba.ClassContext.getMethodAnalysis(ClassContext.java:1005)
      At edu.umd.cs.findbugs.ba.ClassContext.getUsagesRequiringNonNullValues(ClassContext.java:325)
      At edu.umd.cs.findbugs.detect.FindNullDeref.foundGuaranteedNullDeref(FindNullDeref.java:1510)
      At edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.reportBugs(NullDerefAndRedundantComparisonFinder.java:361)
      At edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.examineNullValues(NullDerefAndRedundantComparisonFinder.java:266)
      At edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.execute(NullDerefAndRedundantComparisonFinder.java:164)
      At edu.umd.cs.findbugs.detect.FindNullDeref.analyzeMethod(FindNullDeref.java:278)
      At edu.umd.cs.findbugs.detect.FindNullDeref.visitClassContext(FindNullDeref.java:209)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:216)
      At java.util.concurrent.FutureTask.run(FutureTask.java:266)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At java.lang.Thread.run(Thread.java:748)

**Comment by iloveeclipse** [comment]
Please provide more context (version etc) and steps to reproduce. Otherwise this bug report is simply useless.

**Comment by nimbals1** [comment]
Sonarqube -- 6.4.0.25310
Findbugs -- 3.5
MySQL -- 5.6.36
Travis CI
JDK - oraclejdk8 
Language -- JAVA.

Sonarqube is integrated from quiet some time now. Today my build failed at PR level while generating preview report with mentioned error message.

**Comment by KengoTODA** [comment]
@nimbals1 It is nice if you propose unit test case to reproduce, please check https://github.com/spotbugs/spotbugs/blob/master/CONTRIBUTING.md#before-reporting-a-problem-with-detectors

**Comment by iloveeclipse** [comment]
Please try to understand *which* code or configuration change caused the error. Then try to isolate it to a small example which can be analysed by us. Additonally, you should try to run SpotBugs latest build to see if the problem was already fixed. Your FindBugs version is probably too old anyway (I guess 3.0.1?).

**Comment by KengoTODA** [comment]
note: sonar-findbugs v3.5 uses SpotBugs 3.1.0 RC1.

https://github.com/SonarQubeCommunity/sonar-findbugs/blob/3.5.0/README.md#compatibility

**Comment by nimbals1** [comment]
yes Findbug 3.0.1 i am using

**Comment by KengoTODA** [comment]
@nimbals1 If you're using FindBugs now, please have a try with SpotBugs 3.1.0 RC5. We've solved many known issues.

**Comment by pmayweg** [comment]
I see the same problem with HEAD of master today. It is related to lambdas and INVOKEDYNAMIC. I will try to isolate a simple class to reproduce.

**Comment by pmayweg** [comment]
This small class will reproduce the problem.

import java.util.stream.Stream;
import javax.annotation.CheckForNull;


public class Issue371
{
    @CheckForNull
    private String returnsNull()
    {
        return null;
    }

    public Stream<Integer> getLengthOfStrings(Stream<String> input)
    {
        int length = returnsNull().length();

        return input.map(String::length);
    }

}

**Comment by iloveeclipse** [comment]
Thanks for the test case, I see it still failing with SpotBugs:
```
edu.umd.cs.findbugs.ba.DataflowAnalysisException: can't get position -1 of stack
	at edu.umd.cs.findbugs.ba.Frame.getStackValue(Frame.java:250)
	at edu.umd.cs.findbugs.ba.Hierarchy.resolveMethodCallTargets(Hierarchy.java:743)
	at edu.umd.cs.findbugs.ba.npe.DerefFinder.getAnalysis(DerefFinder.java:141)
	at edu.umd.cs.findbugs.classfile.engine.bcel.UsagesRequiringNonNullValuesFactory.analyze(UsagesRequiringNonNullValuesFactory.java:50)
	at edu.umd.cs.findbugs.classfile.engine.bcel.UsagesRequiringNonNullValuesFactory.analyze(UsagesRequiringNonNullValuesFactory.java:31)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
	at edu.umd.cs.findbugs.ba.ClassContext.getMethodAnalysis(ClassContext.java:1005)
	at edu.umd.cs.findbugs.ba.ClassContext.getUsagesRequiringNonNullValues(ClassContext.java:325)
	at edu.umd.cs.findbugs.detect.FindNullDeref.foundGuaranteedNullDeref(FindNullDeref.java:1510)
	at edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.reportBugs(NullDerefAndRedundantComparisonFinder.java:361)
	at edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.examineNullValues(NullDerefAndRedundantComparisonFinder.java:266)
	at edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.execute(NullDerefAndRedundantComparisonFinder.java:164)
	at edu.umd.cs.findbugs.detect.FindNullDeref.analyzeMethod(FindNullDeref.java:278)
	at edu.umd.cs.findbugs.detect.FindNullDeref.visitClassContext(FindNullDeref.java:209)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1083)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
```

**Comment by iloveeclipse** [comment]
The FindNullDeref code fails on any lambda expression in the method with NP dereference, also this too:
```
import javax.annotation.CheckForNull;

public class Issue371 {
	
	@CheckForNull
	private String returnsNull() {
		return null;
	}

	public void dereferenceWithLambda() {
		returnsNull().chars().map(x -> 42);
	}
}
```

**Comment by FkWbCn** [comment]
Did it have been fixed, if yes but how?
