### ISSUE TITLE
@ParametersAreNonnullByDefault ignored for private methods if set on package or class level.

### ISSUE THREAD

**Issue by adimaret** [spotbugs/spotbugs#374]
We have a problem here where spotbugs does not apply the "@ParametersAreNonnullByDefault" annotation to private methods if the annotation has been set on package or class level. If you annotate the private method directly however it works.

How to reproduce:
1) Unzip the attached maven project.
2) Run "mvn clean verify"

Expected Behavior:
Spotbugs should find the same bug in all three example classes, as all classes have the same code, but simply get their @ParametersAreNonnullByDefault annotation from a different level (package/class/method).

Actual Behavior:
Spotbugs only finds the bug in "TestNonnullByDefaultFromMethodAnnotation.java"

Workaround:
Change all private methods to protected or public and spotbugs will correctly complain about all three classes.

[spotbugs.zip](https://github.com/spotbugs/spotbugs/files/1298881/spotbugs.zip)

**Comment by KengoTODA** [comment]
Hi @adimaret,
Could you try to reproduce this problem with latest SpotBugs 3.1.3? It includes fix for annotations in package-info.java.

**Comment by adimaret** [comment]
@KengoTODA 
Awesome! I'm on a business trip right now, but I will try as soon as I'm back.

**Comment by adimaret** [comment]
@KengoTODA 
I couldn't wait :-)

Unfortunately the bug has not fixed yet. I updated my example project to spotbugs 3.1.3 but still the bug is only reported for TestNonnullByDefaultFromMethodAnnotation.java

[spotbugs-3.1.3.zip](https://github.com/spotbugs/spotbugs/files/1957891/spotbugs-3.1.3.zip)

**Comment by mehwhatever** [comment]
This doesn't seem to fixed yet.

**Comment by cwbriones** [comment]
I tracked down the failure to what appears to be an intentional choice to omit private methods ([code ref](https://github.com/spotbugs/spotbugs/pull/1222/commits/1ea1b314ce22ed07bcd6c0b1bd1cb758f9b67eb6)), but nonetheless I went ahead and opened a PR.

Happy to keep discussion here if that was premature on my part.
