### ISSUE TITLE
Make a package for homebrew

### ISSUE THREAD

**Issue by dguido** [spotbugs/spotbugs#383]
* https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md
* https://github.com/Homebrew/homebrew-core/blob/master/Formula/findbugs.rb

This would be convenient. Thanks!

**Comment by stephengroat** [comment]
https://gist.github.com/stephengroat/005ab64f9ae92e1a97c09d136de43aad

**Comment by stephengroat** [comment]
i'm monitoring this for when `3.10` comes out and i'll push it to homebrew

**Comment by dguido** [comment]
Thank you! I just checked and it looks like you got 3.1.1 too. 💯
