### ISSUE TITLE
Show warning for assertTrue(xxx instanceof SomeClass) in junit tests

### ISSUE THREAD

**Issue by trancexpress** [spotbugs/spotbugs#390]
I run into numerous tests which make assumptions for specific types of objects by casting to that type. Before a lot of those casts, an `assertTrue` is used to validate that the assumption is correct.

This assertion however is far less verbose than the class cast exception _that would occur without the assertion_. Namely, when the assertion fails it will state that _false is not true_. As opposed to _class XXX cannot be casted to ZZZ_, without the assertion. In some cases, such as very sporadic test failures, the actual type of the object can give vital clues for the nature of the fail.

It would be great if a warning issue is shown on the line, explaining why such assertions are not a good practice in tests.

**Comment by trancexpress** [comment]
Please add enhancement label as I'm not able to do so.

**Comment by WarpspeedSCP** [comment]
I'd like to implement a detector for this.

@KengoTODA, should I do a pr to fb-contrib or to spotbugs for this?

**Comment by KengoTODA** [comment]
Both of them are OK. If you want to run your detector with FindBugs or old SpotBugs, fb-contrib will be a good choice.
