### ISSUE TITLE
RC6 spotbugs.jar manifest is incorrect

### ISSUE THREAD

**Issue by richardfearn** [spotbugs/spotbugs#405]
In the RC6 download, `lib` contains:

* `asm-6.0.jar`
* `asm-analysis-6.0.jar`
* `asm-commons-6.0.jar`
* `asm-tree-6.0.jar`
* `asm-util-6.0.jar`
* `asm-xml-6.0.jar`
* `bcel-6.1.jar`

but the `spotbugs.jar` manifest contains:

    Class-Path: spotbugs-annotations.jar dom4j-1.6.1.jar jaxen-1.1.6.jar asm-debug-all-6.0_BETA.jar jsr305-3.0.1.jar jFormatString-3.0.0.jar commons-lang-2.6.jar

i.e. no entry for BCEL, and an incorrect (single) entry for ASM.

This results in the following error:

    $ bin/spotbugs
    One or more required BCEL classes were missing. Ensure that bcel.jar is placed at the same directory with spotbugs.jar

**Comment by richardfearn** [comment]
I think the `Class-Path` comes from [this line in `spotbugs/build.gradle`](https://github.com/spotbugs/spotbugs/blob/e7c8920e8db3e687639ea0f690c3f3a5333575ad/spotbugs/build.gradle#L136).

**Comment by richardfearn** [comment]
Seems to work fine if it's changed to

    Class-Path: spotbugs-annotations.jar dom4j-1.6.1.jar jaxen-1.1.6.jar jsr305-3.0.1.jar jFormatString-3.0.0.jar commons-lang-2.6.jar bcel-6.1.jar asm-6.0.jar asm-analysis-6.0.jar asm-commons-6.0.jar asm-tree-6.0.jar asm-util-6.0.jar asm-xml-6.0.jar

**Comment by jyn514** [comment]
This is still broken for me on `release-3.1`

**Comment by KengoTODA** [comment]
@jyn514 please create a different issue, with clear explanation about your problem.
