### ISSUE TITLE
Test command line scripts on both of Win and Linux

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#415]
We have [many scripts](https://github.com/spotbugs/spotbugs/tree/master/spotbugs/src/scripts) but it seems that some of them still use "FindBugs" and some of them does not work. I want to confirm which script should be tested, then try to add smoke test for each of them.

### Linux
- [x] addMessages
- [x] computeBugHistory
- [x] convertXmlToText
- [x] copyBuggySource
- [x] defectDensity
- [x] fb
- [x] fbwrap
- [x] filterBugs
- [x] findbugs-msv
- [x] listBugDatabaseInfo
- [x] mineBugHistory
- [x] printAppVersion
- [x] printClass
- [x] rejarForAnalysis
- [x] setBugDatabaseInfo
- [x] spotbugs
- [x] spotbugs2
- [x] unionBugs
- [x] xpathFind

### Windows
- [x] spotbugs.bat

**Comment by KengoTODA** [comment]
- [ ] `spotbugs` uses undefined `$CLASSPATH`, which makes script failed

**Comment by iloveeclipse** [comment]
I think this is fixed now, but feel free to reopen if I've missed something.
