### ISSUE TITLE
Java requirements clarification

### ISSUE THREAD

**Issue by rhwood** [spotbugs/spotbugs#427]
https://spotbugs.github.io states that Java 1.9.0 is a requirement. Is that a typo that should be 1.8.0?

Given that Java 9 is not going to receive long term support, I hope that SpotBugs will continue to support running on Java 1.8.0 until at least a long term support release of Java is made next year.

**Comment by iloveeclipse** [comment]
This was my fault I guess, it should read "requires 1.8". I will fix it as soon as I will have access to my PC.

Am 30. September 2017 12:56:06 MESZ schrieb Randall Wood <notifications@github.com>:
>https://spotbugs.github.io states that Java 1.9.0 is a requirement. Is
>that a typo that should be 1.8.0?
>
>Given that Java 9 is not going to receive long term support, I hope
>that SpotBugs will continue to support running on Java 1.8.0 until at
>least a long term support release of Java is made next year.

--
Kind regards,
Andrey Loskutov

http://google.com/+AndreyLoskutov

**Comment by iloveeclipse** [comment]
Fixed now, thanks for reporting!
