### ISSUE TITLE
Eclipse update sites are empty

### ISSUE THREAD

**Issue by wimjongman** [spotbugs/spotbugs#439]
All the advertised Eclipse update sites return a 404.

**Comment by iloveeclipse** [comment]
Have you tried to actually use that in Eclipse? I believe github doesn't allow to list directories content. If you add site.xml you will see that.

**Comment by wimjongman** [comment]
Of course.

**Comment by wimjongman** [comment]
This is an RDi running J9 vm. I also tried in Oxygen which worked. So it is probably a local problem. I will try to fix the problem and report here for future reference.

**Comment by wimjongman** [comment]
J9 certificate problem. Sorry for the noise.

Connection to https://spotbugs.github.io/eclipse/p2.index failed on com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is:
	java.security.cert.CertPathValidatorException: The certificate issued by CN=DigiCert High Assurance EV Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error. Retry attempt 0 started

**Comment by twigger7** [comment]
I have this problem as well. What did you do to fix the problem?

**Comment by wimjongman** [comment]
There are several options.

* Download the repo and install locally
* Install from eclipse marketplace
* Install the certificate in j9
* Run rdi with Oracle Java 8
