### ISSUE TITLE
Treat unit test setup methods as constructors for UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR

### ISSUE THREAD

**Issue by ThrawnCA** [spotbugs/spotbugs#453]
JUnit and TestNG test classes typically initialise their fields within a `setup` method, rather than the constructor, which often results in UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR. Can appropriately-annotated setup methods (`@Before`, `@BeforeMethod`, `@BeforeClass`) be treated as constructors for this purpose?

**Comment by rscarvalho** [comment]
any updates on this?

**Comment by jansohn** [comment]
We also start seeing this with JUnit 5 and its annotation `@BeforeEach`

**Comment by hazendaz** [comment]
Would need @BeforeAll as well.
