### ISSUE TITLE
Support for filtering by annotation

### ISSUE THREAD

**Issue by PhilippWendler** [spotbugs/spotbugs#464]
I would like to repeat [feature request 256](https://sourceforge.net/p/findbugs/feature-requests/256/) from FindBugs:
> Adding support to the filter file format for class level annotation presence would be very handy. In particular it would be great to be able to ignore any classes annotated with `javax.annotation.Generated` which many tools use to mark programmatically generated code.

This would be very useful for us as well, though it would be even better to be able to filter not only for class-level annotations, but also for other annotations (basically everything where a [filter for element name](https://spotbugs.readthedocs.io/en/latest/filter.html#java-element-name-matching) exists).

**Comment by lqc** [comment]
The problem with `javax.annotation.Generated` specifically is that it's retention is limited to source files, while the current code depends on analyzing byte code.

**Comment by gigaSproule** [comment]
You can add `lombok.extern.findbugs.addSuppressFBWarnings = true` to you `lombok.config` and it will cause all lombok generated code to be ignored (or at least it has for me). It would be much nicer if spotbugs could support `javax.annotation.Generated`, but until it does, that's all we can do

**Comment by iloveeclipse** [comment]
javax.annotation.Generated is source only annotation, SpotBugs can't see it in the class files. You can use spotbugs/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/SuppressFBWarnings.java

**Comment by PhilippWendler** [comment]
Note that this feature request is not only about `Generated`, but there are also many other cases where filtering for annotations would be useful. Please reconsider this.

**Comment by iloveeclipse** [comment]
> Please reconsider this.

This issue was about feature request 256 from FindBugs which was about source level annotations. There will be no support for such annotations. Please create new issue with proper description.

**Comment by CodeBear02** [comment]
> javax.annotation.Generated is source only annotation, SpotBugs can't see it in the class files. You can use spotbugs/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/SuppressFBWarnings.java

This does not solve the issue and is not a resolution. How can anybody add a suppress warnings to a generated file? The file is generated. Hence the @Generated annotation.
(I understand it is generated at source and so spotbugs cannot see the annotation but you're second comment is not a fix, just wanted to point this out to people.)
