### ISSUE TITLE
M2E connector for spotbugs?

### ISSUE THREAD

**Issue by iprem** [spotbugs/spotbugs#482]
Is there a m2e connector for spotbugs like we have m2e connector for findbugs?

**Comment by iloveeclipse** [comment]
What is it? Most likely you have to ask on m2e connector tracker.

**Comment by iprem** [comment]
Oh okay. I will get in touch with them. Thanks.

**Comment by vorburger** [comment]
@iprem https://github.com/m2e-code-quality/m2e-code-quality is what you are looking for.

But note #742 due to https://github.com/m2e-code-quality/m2e-code-quality/issues/110 ...
