### ISSUE TITLE
SpotBugs fails to detect unclosed stream

### ISSUE THREAD

**Issue by aaron-haskins** [spotbugs/spotbugs#483]
Foo.bar() method creates a stream, but SpotBugs doesn't complain that the stream is not being closed:

    import com.jcraft.jsch.KeyPair;
    import java.io.ByteArrayOutputStream;

    public class Foo {

        public void bar(final KeyPair keyPair) {
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            keyPair.writePrivateKey(os);
        }

    }

 I believe, SpotBugs should report a bug of an unclosed stream.

**Comment by Maaartinus** [comment]
@aaron-haskins I don't think so. On the opposite, I guess that it's smart enough to know that a `ByteArrayOutputStream` needn't be closed and avoids a useless warning. Just guessing.

**Comment by KengoTODA** [comment]
Your guess is right. [FindOpenStream](https://github.com/spotbugs/spotbugs/blob/761c198a698151be606efa24140fa6495c3c2b7c/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindOpenStream.java#L99-L100) treats that `ByteArrayOutputStream` is not necessary to close.
