### ISSUE TITLE
NP_NONNULL_PARAM_VIOLATION false-positive

### ISSUE THREAD

**Issue by boris-petrov** [spotbugs/spotbugs#484]
I just hit this, Googled and found:

https://sourceforge.net/p/findbugs/bugs/1403/

I have the same issue - `future.complete(null)` is giving a `NP_NONNULL_PARAM_VIOLATION` while it shouldn't.

P.S. SpotBugs 3.1.0.

**Comment by iloveeclipse** [comment]
Hi all, may be I'm wrong, but I don't see commits on the master. Was this only fixed on 3.1.0 branch? We should apply it to 4.0 too.

**Comment by iloveeclipse** [comment]
Arrgh, there is no way to put the issue to two milestones? OMG.

**Comment by varunnvs92** [comment]
Which version of maven plugin contains this fix?

**Comment by mikaelstaldal** [comment]
Same issue with `CompletableFuture.completedStage()`
