### ISSUE TITLE
XSS False positive when using OWASP Encoder taglib

### ISSUE THREAD

**Issue by gvasquez-waypoint** [spotbugs/spotbugs#485]
Seems like the plugin (or perhaps FindBugs itself) is not considering the use of the taglib version of the OWASP Encoder, as it is reporting a violation in the following excerpt:

`<br />MEDIANO PLAZO (${e:forHtmlContent(left)})<br />`

Considering:

`<%@taglib prefix="e" uri="https://www.owasp.org/index.php/OWASP_Java_Encoder_Project" %>`

Using withing SonarQube Version 6.5 (build 27846) and FindBugs plugin 3.6.0

**Comment by h3xstream** [comment]
I will close this issue because it is specific to FSB.
