### ISSUE TITLE
Eclipse plugin m2e-code-quality broken when switching from the FindBugs to the SpotBugs Eclipse plugin due to changed feature name

### ISSUE THREAD

**Issue by vorburger** [spotbugs/spotbugs#486]
Hi guys,

first of all, Thank You all very much for picking up where FindBugs left off - great work!

I've run in https://github.com/m2e-code-quality/m2e-code-quality/issues/110 and was wondering whether switching the ID of the feature of the Eclipse plugin from FB to SB was totally intentionally and you do firmly want to (eventually) switch everything, or whether you would be open to (a PR from me proposing to) revert that and keep the feature ID as it was?

Thanks again for SpotBugs!

**Comment by sewe** [comment]
The change of the feature ID was intentional. However, a `update.matchExp` in the feature’s `p2.inf` ensures that the new ID is recognized as an update of both `com.github.spotbugs.plugin.eclipse.feature.group` and `edu.umd.cs.findbugs.plugin.eclipse.feature.group` (the old ID). So, no need for a PR to revert the rename.

**Comment by vorburger** [comment]
@sewe hang on, I'm not following... currently it is not working, see the p2 installation error shown over in https://github.com/m2e-code-quality/m2e-code-quality/issues/110 ... I've actually no idea what an `update.matchExp` in the feature’s `p2.inf` is... are you saying that is something that could be done here to fix this problem? Or something that is already done and it should work already? Then why doesn't it? :confused:

**Comment by vorburger** [comment]
@sewe oh wait, I think I'm confusing the problem of the changed feature ID (which that p2 thing perhaps fixes..) and the plugin ID which also changed... and that the p2 thing, however it works, cannot possibly fix? 

With the [m2e.code.quality.findbugs/META-INF/MANIFEST.MF having a fixed Require-Bundle:  edu.umd.cs.findbugs.plugin.eclipse](https://github.com/m2e-code-quality/m2e-code-quality/blob/develop/com.basistech.m2e.code.quality.findbugs/META-INF/MANIFEST.MF#L17), there's really no way it could possibly ever work with the Spotbugs Eclipse plugin - right? 

In that case, unless you have some better idea, I'm guessing this issue should be closed as answered, and over in m2e-code-quality there should be `com.basistech.m2e.code.quality.spotbugs` plugin fork, which has a Require-Bundle: `com.github.spotbugs.plugin.eclipse` instead of `edu.umd.cs.findbugs.plugin.eclipse` .. perhaps I could contribute that there - just thought it was worth clarifying before here, if there's a better solution.

**Comment by vorburger** [comment]
Closing this issue; the "solution" to what I was whining about above is not in spotbots itself, but to extend m2e-code-quality to have support for spotbugs, which is what https://github.com/m2e-code-quality/m2e-code-quality/issues/110 is about.
