### ISSUE TITLE
Stop depending on needless asm artifacts

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#494]
To keep backward compatibility, SpotBugs 3.1.0 depends on all ASM artifacts (which was packaged into [asm-debug-all](https://mvnrepository.com/artifact/org.ow2.asm/asm-debug-all/6.0_BETA)).

From 4.0.0, we do not need to depends on needless artifacts. Delete them after we close #480.

refs #400

**Comment by gtoison** [comment]
This was fixed by https://github.com/spotbugs/spotbugs/commit/99d43b1ea939bba9b3b8a2ef49a9628a7c9a1fd5
