### ISSUE TITLE
upgrade dom4j version and fix JDK 9 warning

### ISSUE THREAD

**Issue by bshannon** [spotbugs/spotbugs#499]
SpotBugs is using dom4j version 1.6.1, which produces this warning when running with JDK 9:

     [java] WARNING: An illegal reflective access operation has occurred
     [java] WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/home/shannon/ws/javaxmail-spotbugs/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
     [java] WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
     [java] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
     [java] WARNING: All illegal access operations will be denied in a future release

The [current version of dom4j is 2.1.0](https://github.com/dom4j/dom4j/releases).  Upgrading to that version might fix this problem.  If not, please file a bug against dom4j so they'll fix this.

**Comment by KengoTODA** [comment]
Thank you! This issue is same with #300, which will be closed by #490.
