### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by jsotuyod** [spotbugs/spotbugs#5]
We need a new, more modern looking website.

Probably most of the old sections can be removed. I'd rather have a small description, bug descriptions, plugins / extensibility with APIs, and in-detail tutorials on how to use SpotBugs from different tools:

* Maven
* Ant
* Gradle
* Eclipse
* BlueJ
* stand-alone

**Comment by mebigfatguy** [comment]
We also need new graphics... anyone an artist?

**Comment by jsotuyod** [comment]
I just published a simplified website with responsive design.

I got rid of several sections. Instructions are still missing, and probably will remain that way until we release and are sure what pieces have been kept.

I'm not sure what to do with the manual and [sysprops](https://github.com/spotbugs/spotbugs.github.io/blob/master/sysprops.html). The manual could use some cleaning, and I'm not sure we want to support those sysprops (which are incomplete and outdated anyway). So far I left no link to those, but we will see.

I am also not sure of keeping the Japanese and French translations of the bug descriptions, since I doubt we will be able to maintain those moving forward (I know no French, and my Japanese is too rudimentary for this task).

**Comment by mebigfatguy** [comment]
i'm fine with nuking the translations

**Comment by KengoTODA** [comment]
I'm Japanese, I will handle Japanese language translations. I'll watch this issue.
But I also agree that moving forward is the highest priority for now.

**Comment by jsotuyod** [comment]
@KengoTODA Thanks for volunteering! You work on setting up Travis for FindBugs has been most useful to us when setting it up for SpotBugs.

**Comment by h3xstream** [comment]
I can help with the website design. If I can get a basic layout to start from, this would help to support mobile and tricky resolutions.

**Comment by jsotuyod** [comment]
Awesome! There is a basic responsive layout in the current site repo https://github.com/spotbugs/spotbugs.github.io

Feel free to start from there or fresh with Bootstrap or whatever you feel like.

**Comment by h3xstream** [comment]
@jsotuyod Do you have an estimated when you guys are hoping to release 3.1.0 ?

I would try to find some time before that..

**Comment by jsotuyod** [comment]
@h3xstream not really. As soon as posssible.

As far as I can tell, only #6 and #78 are blocking for a proper 3.1.0 release. We may also want to review the situation with jsr-305

**Comment by KengoTODA** [comment]
@jsotuyod If possible, it's better to fix #60 by #69 before we release 3.1.0. 

In my understanding, [BCEL 6.1](https://issues.apache.org/jira/browse/BCEL/fixforversion/12329156/) is necessary to fix this problem, but not released yet.

**Comment by jsotuyod** [comment]
@KengoTODA I guess the best we can do is ask @garydgregory and @mebigfatguy for eventual release plan on BECL 6.1.

**Comment by KengoTODA** [comment]
#112 proposes new manual pages, please check.

**Comment by iloveeclipse** [comment]
I find the page nice. One thing I miss: dedicated link to the new manual on readthedocs.

**Comment by KengoTODA** [comment]
Do you mean that we need a hyperlink at https://spotbugs.github.io/ or README.md to guide users to https://spotbugs.readthedocs.io/en/latest/ ?

**Comment by iloveeclipse** [comment]
I mean the link at https://spotbugs.github.io/. We have there few links to the tool integration but no dedicated link "manual is here".

**Comment by iloveeclipse** [comment]
Thanks to everyone contributed! I think we can close this now. New page and manual looks great.
