### ISSUE TITLE
Eclipse plugin extension name clash with old Findbugs plugin

### ISSUE THREAD

**Issue by Bananeweizen** [spotbugs/spotbugs#502]
Having both Findbugs and Spotbugs plugin installed, they still declare an identical extension:
`An extension already exists with id "de.tobject.findbugs.view.explorer.BugContentProvider".`

The below error message is a bit more cryptic, but it might also be related to declaring the same ID for the decorator in the old and new code maybe?
`Plugin com.github.spotbugs.plugin.eclipse, extension org.eclipse.ui.decorators, id de.tobject.findbugs.decorators.FileBugCountDecorator: Unknown extension tag found: decorator`

**Comment by iloveeclipse** [comment]
Please simply uninstall the old FB plugin.

**Comment by sewe** [comment]
> Having both Findbugs and Spotbugs plugin installed, they still declare an identical extension:
`An extension already exists with id "de.tobject.findbugs.view.explorer.BugContentProvider".`

@Bananeweizen Can you tell us a bit about how you ended up with both FindBugs and SpotBugs installed? After the fix to #209, SpotBugs should be recognized as an **update** of FindBugs, so adding the SpotBugs update site and *Check for Updates* should deactivate FindBugs. If you explicitly install both?

**Comment by Bananeweizen** [comment]
I think that was a machine were I already used Spotbugs before it was actually released. Trying to reproduce the same issue on another machine I end up with Findbugs being replaced by Spotbugs as you described. Therefore closing.

**Comment by carstenartur** [comment]
The spotbugs plugin in a maven configuration does not work for me, I get when I want to download the m2e plugin to handle it:
No marketplace entries found to handle spotbugs-maven-plugin:3.1.11:check in Eclipse.  
Only findbugs works for me.
Can it be that using the same id breaks p2 somehow?
