### ISSUE TITLE
False positive with @RequestParam NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS

### ISSUE THREAD

**Issue by jcamerin** [spotbugs/spotbugs#508]
Building a Spring HATEOAS Web Service, the attempt to add a link with the following code triggers a NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS

resource.add(ControllerLinkBuilder
                .linkTo(methodOn(JobRestController.class).getJobAnalytics(entity.getId(), null, null)).withRel("Job Analytics"));

The method definition in my Controller is below. Note the second and third parameter are optional RequestParameters.

@RequestMapping(value = "/{jobId}/analytics", method = RequestMethod.GET)
    @Transactional(readOnly = true)
    public ResponseEntity<JobAnalyticsResource> getJobAnalytics(@PathVariable("jobId") @NotNull int jobId,
            @RequestParam(name = "timespan", required = false, defaultValue = "ALL") Timespan timespan,
            @RequestParam(name = "channel", required = false) Channel channel) {

        return new ResponseEntity<JobAnalyticsResource>(
            jobAnalyticsService.getJobAnalytics(jobId, timespan, channel), HttpStatus.OK
        );
    }

**Comment by KengoTODA** [comment]
sorry I cannot catch your point, which part has problem? And if possible please propose a PR to reproduce it by unit test.

**Comment by gtoison** [comment]
This issue has been inactive for a while and there was never a clarification, please open a new issue if the problem persists
