### ISSUE TITLE
The download site for the Eclipse plugin is dead

### ISSUE THREAD

**Issue by GunnarAndersson** [spotbugs/spotbugs#510]
http://spotbugs.readthedocs.io/en/latest/eclipse.html contains links to three different update sites:

https://spotbugs.github.io/eclipse/
https://spotbugs.github.io/eclipse-candidate/
https://spotbugs.github.io/eclipse-latest/

These links are all dead, and I think they they have been dead for a while.

**Comment by iloveeclipse** [comment]
Sure they aren't dead, they are working fine. Only they do not contain index.html and Github silly server says 404 on that.

**Comment by GunnarAndersson** [comment]
This is good to hear. I don't understand why the website contains links if a 404 is expected behavior if you follow them, though. Wouldn't it be better to highlight them with e.g. a boldface font if the purpose with showing a link is to get a highlight?

The reason why I tried following the links is that Eclipse reports failure when I try to update from 3.1.0.20170610 to the latest version using https://spotbugs.github.io/eclipse/. I've tried a couple of times over the last couple of weeks. I thought that the reason for the failure was that the download site is down.

**Comment by GunnarAndersson** [comment]
Uninstalling 3.1.0.20170610 and trying to reinstall from https://spotbugs.github.io/eclipse/ or https://spotbugs.github.io/eclipse-latest/ didn't help, I still get "Cannot complete operation".

**Comment by iloveeclipse** [comment]
The links are for *Eclipse update manager*, not for browsing content. And https://spotbugs.github.io/eclipse/ works fine for me. Most likely an issue with your proxy or network provider.

"Cannot complete operation" can have multiple reasons, if you check the error log you will most likely find the root cause.

**Comment by GunnarAndersson** [comment]
Thanks, I'll try to locate the error log and see if I can find something there. I have never had any similar problems when installing/updating other packages, but maybe there's some subtle problem.

I understand that the links are to be used in the Eclipse update manager, but you link to them from a standard webpage. I can't immediately think of any situation when the Eclipse update manager would use the links from http://spotbugs.readthedocs.io/en/latest/eclipse.html. If there is such a situation, then it makes perfect sense to show the links as HTML links, otherwise it seems buggy to me.
