### ISSUE TITLE
Initial migration of the FindBugs-IDEA plugin to SpotBugs

### ISSUE THREAD

**Issue by scanban** [spotbugs/spotbugs#515]
I've took initial steps on migration . Just migrated to SpotBugs 3.1.1. Build system changed to gradle and gradle-intellij-plugin, Changed plugin name to "SpotBugs-IDEA" and replaced FindBugs to SpotBugs in plugin.xml description text. Tested with supplied java test project.
Please take a look:
https://github.com/scanban/findbugs-idea

**Comment by iloveeclipse** [comment]
I'm not using idea, so I can't verify here, but in general it sounds cool. 

What is your intention - do you want to be part of the main SpotBugs project repo, or just want to be mentioned on the documentation, or something else? For general announcements please use https://github.com/spotbugs/discuss.

**Comment by FeanorsCurse** [comment]
Any news on this? We're sticking to FindBugs for IDEA and it works fine, but I'd like to try a spotbugs version if possible.

**Comment by KengoTODA** [comment]
Currently SpotBugs team has no information, you may refer https://github.com/andrepdo/findbugs-idea/issues/265

If we need a repository in this organization, I'll come and handle it.

**Comment by FeanorsCurse** [comment]
Thanks!

**Comment by gkohen** [comment]
Issue opened with Jetbrains for IntelliJ
https://youtrack.jetbrains.com/issue/IDEA-201846
Vote if you think it's needed.

**Comment by doribd** [comment]
Any news as at the moment we are also stick using the findbugs instead?

**Comment by h3xstream** [comment]
When will this plugin https://github.com/scanban/findbugs-idea get published to the IntelliJ plugin repo?

**Comment by h3xstream** [comment]
I have worked on a new version that is working on the latest version of IntelliJ 2019+: https://github.com/GoSecure/findbugs-idea

There are minor changes needed for the support of the latest version : https://github.com/GoSecure/findbugs-idea/commit/3200b5b8b6ce9c7829c834abc73810cde6a5ea01

With this version it would finally be possible to Java 11 project.

**Comment by h3xstream** [comment]
I have published a first version. https://plugins.jetbrains.com/plugin/13518-spotbugs-idea/
It should worked on any IntelliJ version download in the last year. (2019.1 API)

Sorry if this is too fast. I thought the risk of publishing the extension was low.. I can always remove the plugin from the marketplace.

**Comment by mfbieber** [comment]
@h3xstream: It appears that JetBrains has the plugin under inspection and thus it cannot be downloaded from the marketplace. 

I just cloned your repository, compiled the plugin and I will be testing it. I am running it on 2019.3 and am using Java 12 and 13 mostly. The findbugs plugin was not working with this higher Java versions :)

Thanks! I will post any issues if I encounter any. You made my developer day today 😄 🎉 !

**Comment by h3xstream** [comment]
I have receive feedback from Jetbrains. The feedback include warning to fix. I will try to find time to fix those warnings.

**Comment by matus-gazo** [comment]
@h3xstream Hi, any news on this please? Very eager to get started with it :) Thanks so much for the effort!

**Comment by MCMicS** [comment]
@h3xstream If you need some help with fixes you can send me the warnings. I've maintain another idea plugin as well an made it 2020.1+ ready.

**Comment by testn** [comment]
any updates?

**Comment by amaembo** [comment]
Hello! JetBrains employee is here. We are working on our own fork of SpotBugs-IDEA plugin. Expect some news soon.

**Comment by amaembo** [comment]
Our fork is here: 
https://github.com/JetBrains/spotbugs-intellij-plugin
We are working now on polishing things before publishing the first version in the plugin repository.
It's a team project (not officially supported JetBrains product), so don't expect much support, but we will try to address the critical issues.

Also, a minimal compatibility version is set to IDEA 2019.3. We don't have enough resources to test compatibility with older versions.

**Comment by amaembo** [comment]
The plugin is published officially:
https://plugins.jetbrains.com/plugin/14014-spotbugs
Please report all the issues to the plugin tracker 
https://github.com/JetBrains/spotbugs-intellij-plugin/issues

@iloveeclipse I think, this could be closed

**Comment by iloveeclipse** [comment]
Thanks Tagir.

**Comment by okohll** [comment]
> The plugin is published officially:
> https://plugins.jetbrains.com/plugin/14014-spotbugs
> Please report all the issues to the plugin tracker
> https://github.com/JetBrains/spotbugs-intellij-plugin/issues
> 
> @iloveeclipse I think, this could be closed

Thank you!
