### ISSUE TITLE
Unused variable reported with wrong name

### ISSUE THREAD

**Issue by trancexpress** [spotbugs/spotbugs#516]
See attached screenshot.

Steps to reproduce:

1. Import project from attached archive.
2. Open the only source, SomeClass.java.
3. Run SpotBugs (right click in the editor, SpotBugs -> Find Bugs).
4. Mouse over on the annotation of the unused variable / double click on it.
5. Observe that the bug report is a dead store in "myString", as opposed to "unused". 

Its not possible to ignore the SpotBugs issue via an exclude filter xml, unless the name of the variable is set to the wrong one. In this case, we have to exclude "myString" and not "unused". Excluding "unused" does not result in suppressed error, which is very confusing.

Originally seen due to https://bugs.eclipse.org/bugs/show_bug.cgi?id=420984.

[BugExample.zip](https://github.com/spotbugs/spotbugs/files/1600246/BugExample.zip)
![wrong_name_of_unused_variable](https://user-images.githubusercontent.com/24752155/34520003-19cac39c-f087-11e7-8f71-2276451c9712.png)

Environment:

SpotBugs 4.0.0.201711300223-0081ca4 com.github.spotbugs.plugin.eclipse.feature.group SpotBugs Project

Eclipse SDK
Version: Photon (4.8)
Build id: I20171217-2000

Further notes:

Code is:

```
class SomeClass {

    int someCounter = 0;

    void doSomething(Object object) {
        try {
        	int myNumber = 0;
            String myVariable = object.toString();
            if ((!myVariable.equals("something"))) {
            	doSomething(myNumber);
            }
        } catch (Throwable t) {
            if (t instanceof RuntimeException) {
                final RuntimeException unused = (RuntimeException) t;
                //throw unused;
            }
            throw new RuntimeException(t);
        }
    }

    private void doSomething(int i) {
    	someCounter += i;
    }
}
```

The behavior seems to depend on the number of local variables which are defined in the method. If I e.g. remove "myNumber", _no problem is reported at all_ by SpotBugs.

Also if I remove the instanceof if, I also see no reported error.
[bytecode.txt](https://github.com/spotbugs/spotbugs/files/1600292/bytecode.txt)

**Comment by iloveeclipse** [comment]
If I read the bytecode right, Eclipse compiler "forgets" to add an entry to the local variable table for the "unused" variable, so that ASTORE uses local variable index which is invalid (because it is not defined in the current scope).  SpotBugs should not warn here at all, because it should check if the index is valid or not.

I will check this and create a bug report for the Eclipse compiler.

**Comment by iloveeclipse** [comment]
Below is the reduced example.
```
package ghIssues;

class Issue516 {
	static void missingLvtEntry() throws Throwable {
		try {
			int var1 = 0;
			int var2 = var1;
			System.out.println(var2);
		} catch (Throwable t) {
			Throwable unused = t.getCause();
			// throw unused;
		}
	}
}
```

Here is what Eclipse compiler (4.8 latest build) generates for the method:

```
   // access flags 0x8
  static missingLvtEntry() : void throws Throwable 
    TRYCATCHBLOCK L0 L1 L2 Throwable
   L0
    LINENUMBER 6 L0
    ICONST_0
    ISTORE 0
   L3
    LINENUMBER 7 L3
    ILOAD 0: var1
    ISTORE 1
   L4
    LINENUMBER 8 L4
    GETSTATIC System.out : PrintStream
    ILOAD 1: var2
    INVOKEVIRTUAL PrintStream.println(int) : void
   L1
    LINENUMBER 9 L1
    GOTO L5
   L2
   FRAME SAME1 Throwable
    ASTORE 0
   L6
    LINENUMBER 10 L6
    ALOAD 0: t
    INVOKEVIRTUAL Throwable.getCause() : Throwable
    ASTORE 1
   L5
    LINENUMBER 13 L5
   FRAME SAME
    RETURN
    LOCALVARIABLE var1 int L3 L1 0
    LOCALVARIABLE var2 int L4 L1 1
    LOCALVARIABLE t Throwable L6 L5 0
    MAXSTACK = 2
    MAXLOCALS = 2
```

Please note this block 
```
   L6
    LINENUMBER 10 L6
    ALOAD 0: t
    INVOKEVIRTUAL Throwable.getCause() : Throwable
    ASTORE 1
   L5
```

where `ASTORE 1` references to the local variable `1` in the scope `L5 L6`.
The LVT for 1 contains however only one occurrence for `var2` in the L4 L1 scope : `LOCALVARIABLE var2 int L4 L1 1`. What is missing is this entry:  `LOCALVARIABLE unused Throwable L7 L5 1`, which one can see by removing the comment from `// throw unused;`

**Comment by iloveeclipse** [comment]
Here is what javac + javap (JDK 1.8.0_144) generate from commented out code:
```
$ javac -g Issue516.java
$ javap -c -l Issue516.class
...
  static void missingLvtEntry() throws java.lang.Throwable;
    Code:
       0: iconst_0
       1: istore_0
       2: iload_0
       3: istore_1
       4: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
       7: iload_1
       8: invokevirtual #3                  // Method java/io/PrintStream.println:(I)V
      11: goto          20
      14: astore_0
      15: aload_0
      16: invokevirtual #5                  // Method java/lang/Throwable.getCause:()Ljava/lang/Throwable;
      19: astore_1
      20: return
    Exception table:
       from    to  target type
           0    11    14   Class java/lang/Throwable
    LineNumberTable:
      line 6: 0
      line 7: 2
      line 8: 4
      line 12: 11
      line 9: 14
      line 10: 15
      line 13: 20
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          2       9     0  var1   I
          4       7     1  var2   I
         15       5     0     t   Ljava/lang/Throwable;
```

and from "fixed" code:

```
  static void missingLvtEntry() throws java.lang.Throwable;
    Code:
       0: iconst_0
       1: istore_0
       2: iload_0
       3: istore_1
       4: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
       7: iload_1
       8: invokevirtual #3                  // Method java/io/PrintStream.println:(I)V
      11: goto          22
      14: astore_0
      15: aload_0
      16: invokevirtual #5                  // Method java/lang/Throwable.getCause:()Ljava/lang/Throwable;
      19: astore_1
      20: aload_1
      21: athrow
      22: return
    Exception table:
       from    to  target type
           0    11    14   Class java/lang/Throwable
    LineNumberTable:
      line 6: 0
      line 7: 2
      line 8: 4
      line 12: 11
      line 9: 14
      line 10: 15
      line 11: 20
      line 13: 22
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          2       9     0  var1   I
          4       7     1  var2   I
         20       2     1 unused   Ljava/lang/Throwable;
         15       7     0     t   Ljava/lang/Throwable;
```

**Comment by iloveeclipse** [comment]
I have a fix for SpotBugs, but I have not yet analyzed why both compilers are not generating LVT entry for unused variables - is this per purpose or not?

The wrong name is coming from commit 64746a7648eed0ccc1da6eb1dd23b7a920e13393 (in FindBugs 1.3.6) which was an attempt to "fix" the weird local variable ranges:

> ranges for local variables are weird
> If we find only a single variable at a porticular index, we'll just it even if the range isn't correct

I don't think that this was a good idea. As we see in this bug, LVT entries with same index can be generated for completely different variables, so "fixing" that (sometimes incomplete) information manually is weird too.

**Comment by iloveeclipse** [comment]
The specs does not allow compiler to generate the variable info in this case, so we can't fix compiler and can only close this bug now with the workaround in SpotBugs.
