### ISSUE TITLE
RV_RETURN_VALUE_IGNORED should check com.google.errorprone.annotations.CanIgnoreReturnValue

### ISSUE THREAD

**Issue by Bananeweizen** [spotbugs/spotbugs#518]
We are using Guava [Preconditions.checkNotNull(someMethodArgument)](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Preconditions.html#checkNotNull-T-) and similar preconditions. Spotbugs complains about not using the return value when writing the precondition as statement.

It would be nice if Spotbugs could check such methods for the [CanIgnoreReturnValue](https://github.com/google/error-prone/blob/master/annotations/src/main/java/com/google/errorprone/annotations/CanIgnoreReturnValue.java) annotation, which indicates exactly that the check should not be applied.

**Comment by KengoTODA** [comment]
refs #429

**Comment by Bananeweizen** [comment]
Just to be sure: I'm asking for the ErrorProne annotation, not for the JSR305 annotation. :)

**Comment by vorburger** [comment]
Just FTR, this works around that of course, but is not so nice:

    @SuppressFBWarnings("RV_RETURN_VALUE_IGNORED") // OK because guaranteed only once; also https://github.com/spotbugs/spotbugs/issues/518

**Comment by philipl** [comment]
Fixed by #538
