### ISSUE TITLE
Merge 3.1.x fixes into 4.0

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#519]
We have #478 and #484 which are fixed only on 3.1.0 branch, and a pending PR #516 on 3.1.0 which also want to travel into master.

We should merge them into master too.

**Comment by KengoTODA** [comment]
Just merge release branch to master with a merge commit, then we can close this issue.

**Comment by iloveeclipse** [comment]
OK, I wil do that.
