### ISSUE TITLE
Supported annotations are not documented?

### ISSUE THREAD

**Issue by rhwood** [spotbugs/spotbugs#522]
I cannot find any equivalent to http://findbugs.sourceforge.net/manual/annotations.html for SpotBugs. 

Can such a page be added to the SpotBugs documentation?

**Comment by iloveeclipse** [comment]
Sure, if someone would contribute a patch :-)

**Comment by jscancella** [comment]
As part of hacktoberfest I was going to submit a PR for this, but I can't seem to find any package named annotations in  https://github.com/spotbugs/spotbugs/tree/master/spotbugs/src/main/java/edu/umd/cs/findbugs
Were they removed at some point?

**Comment by KengoTODA** [comment]
I think you can refer the javadoc instead: https://javadoc.io/doc/com.github.spotbugs/spotbugs-annotations/

**Comment by KengoTODA** [comment]
@jscancella Now it's located in different submodule:
https://github.com/spotbugs/spotbugs/tree/master/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs

**Comment by nhumblot** [comment]
Hi :wave: 

With the merge of #1024, shouldn't this issue be closed?

**Comment by KengoTODA** [comment]
Yes, thanks for your notice!
