### ISSUE TITLE
Support @org.checkerframework.checker.nullness.compatqual.NullableDecl etc.

### ISSUE THREAD

**Issue by PhilippWendler** [spotbugs/spotbugs#523]
Guava 23.6 has [switched](https://github.com/google/guava/issues/2960#issuecomment-350721044) from using `javax.annotation.Nonnull` to `org.checkerframework.checker.nullness.compatqual.NullableDecl` for non-null parameters etc. Please support this annotation (and possibly the other annotations from the same package), because otherwise SpotBugs creates a lot of false alarms when calling Guava methods. I tested this with SpotBugs 3.1.1.

**Comment by iloveeclipse** [comment]
@PhilippWendler : it would be great if you could provide here a map which checker annotation corresponds to which "old" annotation.

The fix itself will be probably trivial.

**Comment by PhilippWendler** [comment]
Thanks.

It seems that [`org.checkerframework.checker.nullness.compatqual.NullableDecl`](https://github.com/typetools/checker-framework/blob/b3cf0567ec81c0b89ab74d1da13531d03bbad182/checker/src/org/checkerframework/checker/nullness/compatqual/NullableDecl.java) for `Nullable` and [`org.checkerframework.checker.nullness.compatqual.NonNullDecl`](https://github.com/typetools/checker-framework/blob/b3cf0567ec81c0b89ab74d1da13531d03bbad182/checker/src/org/checkerframework/checker/nullness/compatqual/NonNullDecl.java) for `NonNull` would at least need to be supported.

There are more annotations in [`org.checkerframework.checker.nullness.qual`](https://github.com/typetools/checker-framework/tree/b3cf0567ec81c0b89ab74d1da13531d03bbad182/checker/src/org/checkerframework/checker/nullness/qual) for more complex nullness analysis (the above annotations are the compatibility annotations for Java 7 code), but I am not sure whether SpotBugs could support them, and it seems Guava does not use them. Maybe just [`org.checkerframework.checker.nullness.qual.Nullable`](https://github.com/typetools/checker-framework/blob/b3cf0567ec81c0b89ab74d1da13531d03bbad182/checker/src/org/checkerframework/checker/nullness/qual/Nullable.java) and [`org.checkerframework.checker.nullness.qual.NonNull`](https://github.com/typetools/checker-framework/blob/b3cf0567ec81c0b89ab74d1da13531d03bbad182/checker/src/org/checkerframework/checker/nullness/qual/NonNull.java) for now? This would allow Java 8 code to keep using annotations named `Nullable` instead of `NullableDecl`.
If SpotBugs supports it, the `qual` annotations can also be used on types, not only on declarations.

For reference: I have this from https://github.com/JetBrains/kotlin/pull/1421, which is the PR that the Guava guys have submitted for the Kotlin nullness analyzer. It mentions these four annotations [here](https://github.com/JetBrains/kotlin/pull/1421/files#diff-f73479c784a745d7532df67cb00cf6c5).

**Comment by iloveeclipse** [comment]
Yep.

**Comment by gkeighren** [comment]
I'm not sure #539 fully addresses this issue. Specifically, it didn't add any support for `org.checkerframework.checker.nullness.compatqual.NullableDecl`, only `org.checkerframework.checker.nullness.qual.Nullable`.

Guava 23.6-jre (for example) uses `NullableDecl`, so SpotBugs 3.1.2 is producing a lot of `NP_METHOD_PARAMETER_TIGHTENS_ANNOTATION` false-positives in my code when overriding a method which has a parameter annotated with `NullableDecl`, as my code currently uses `javax.annotations.Nullable` for the annotation.

For example, see `FutureCallback.onSuccess(V result)` in Guava 23.6-jre.

**Comment by anatoliy-balakirev** [comment]
Hi. I'm trying to use guava 25.1-jre, namely `MoreObjects.toStringHelper().add("name", value)`, where signature looks like this:
`public ToStringHelper add(String name, @ org.checkerframework.checker.nullness.qual.Nullable Object value)`

I'm passing in a value (name is just a string literal), which is marked with old `@ javax.annotation.CheckForNull` and getting some errors from spotbugs (version 3.1.3):
> [INFO] Total bugs: 12
> [INFO] Null passed for non-null parameter of com.google.common.base.MoreObjects$ToStringHelper.add(String, Object) in ...

Is that supposed to work?

**Comment by anatoliy-balakirev** [comment]
Actually, just tried to replace `javax.annotation.CheckForNull` with `org.checkerframework.checker.nullness.qual.Nullable` in our code and that helped. Not sure if this is an expected behavior though. I thought old annotations are still supported as well...
