### ISSUE TITLE
Gradle Plugin 1.6 does not seem to be working with android

### ISSUE THREAD

**Issue by vanniktech** [spotbugs/spotbugs#524]
I've got the following configuration:

```groovy
buildscript {
  repositories {
    mavenCentral()
    jcenter()
    google()
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.github.spotbugs:gradlePlugin:1.6.0"
  }
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: "com.github.spotbugs"
```

Thus I'd expect to get the `spotbugsMain` and `spotbugsTest` generated according to the [documentation](http://spotbugs.readthedocs.io/en/latest/gradle.html). However none is being generated.

Applying this plugin in a Java library (`apply plugin: 'java-library'`) works without any problems.

**Comment by KengoTODA** [comment]
Could you check http://spotbugs.readthedocs.io/en/latest/gradle.html#generate-spotbugs-tasks-with-android-gradle-plugin firstly?

**Comment by vanniktech** [comment]
Closing as my interest in spotbugs has gotten less and it does not seem like it's supposed to work with Android.
