### ISSUE TITLE
RFC: idea to distribute test harness for plugin developers

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#53]
SpotBugs has test harness classes introduced at #35. As a plugin developer, I want to use these classes in my plugin project. It should be valuable for all plugin developers.

Now we put these classes in `findbugs/src/test/java` directory, so `spotbugs.jar` doesn't contain them. Is it possible to distribute them as separated artifact? Maybe we have several options:

1. Easy options:
    * Generate another `.jar` file by gradle without any code change, or
    * Move test harness classes into `findbugs/src/main/java`, to package them into `spotbugs.jar`.
2. Right options:
    * Create another module in this repository, to build harness classes. We should have extra work, to solve cyclic reference (`spotbugs (src/test/java)` -&gt; `harness` -&gt; `spotbugs (src/main/java)`), or
    * Create another repository to build harness classes. It also has the same extra work.
 
To solve cyclic reference, we may need to separate `findbugs/src/main/java` into two modules: SpotBugs core and SpotBugs detectors. Then reference will be simplified like `detector` -&gt; `harness` -&gt; `core`.

I think the 1st 'Right option' (create sub-modules to host spotbugs-core, spotbugs-detector and spotbugs-test-harness) is the best. But I remember that some of us don't like multiple modules in one project (refs #4). How do you think?

**Comment by jsotuyod** [comment]
I love this! I've been thinking about it for some time.

It would split the codebase making it more mantainable, it would allow third parties to use the test infrastructure AND it allows plugin developers to easily run just their detectors without the defaults ones.

Also of note, it forces ourselves to respect the public API provided by the core, making it more obvious if we ever break anything for third parties.

As far as I'm concerned, feel free to push this forward as part of our project structure changes.

**Comment by KengoTODA** [comment]
I will list "core" classes which is depending on detector:

```
findbugs/src/main/java/edu/umd/cs/findbugs/FindBugs2.java:import edu.umd.cs.findbugs.detect.NoteSuppressedWarnings;
findbugs/src/main/java/edu/umd/cs/findbugs/ba/AnalysisContext.java:import edu.umd.cs.findbugs.detect.UnreadFields;
findbugs/src/main/java/edu/umd/cs/findbugs/ba/AnalysisContext.java:import edu.umd.cs.findbugs.detect.UnreadFieldsData;
findbugs/src/main/java/edu/umd/cs/findbugs/ba/FieldSummary.java:import edu.umd.cs.findbugs.detect.UnreadFieldsData;
findbugs/src/main/java/edu/umd/cs/findbugs/ba/XFactory.java:import edu.umd.cs.findbugs.detect.BuildObligationPolicyDatabase;
findbugs/src/main/java/edu/umd/cs/findbugs/ba/vna/ValueNumberFrameModelingVisitor.java:import edu.umd.cs.findbugs.detect.FindNoSideEffectMethods.MethodSideEffectStatus;
findbugs/src/main/java/edu/umd/cs/findbugs/ba/vna/ValueNumberFrameModelingVisitor.java:import edu.umd.cs.findbugs.detect.FindNoSideEffectMethods.NoSideEffectMethodsDatabase;
findbugs/src/test/java/edu/umd/cs/findbugs/ba/ch/Subtypes2Test.java:import edu.umd.cs.findbugs.detect.FindRefComparison;
```

It seems difficult to move all detectors to new sub module, I will move a part of them.
