### ISSUE TITLE
Gradle build failing with "Failed to run Gradle SpotBugs Worker"

### ISSUE THREAD

**Issue by plorenz** [spotbugs/spotbugs#530]
```
* What went wrong:
Execution failed for task ':spotbugsMain'.
> Failed to run Gradle SpotBugs Worker
   > Process 'Gradle SpotBugs Worker 38' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
2 actionable tasks: 1 executed, 1 up-to-date
```

Is there anything I can do to get more information? I've tried running with --stacktrace and --debug and neither provides any useful information.

**Comment by ArkantosC** [comment]
I'm facing a similar problem. For my side the problem is happening when I added a classpath with java classses in the dependencies section.

**Comment by michalkowol** [comment]
I have the same problem.

**Comment by KengoTODA** [comment]
maybe better to discuss at https://github.com/spotbugs/spotbugs-gradle-plugin/

and could you share some project which can reproduce this issue?

**Comment by hongqijia** [comment]
I ran into this problem too.  Is there any updates on this issue?

**Comment by jeven2016** [comment]
I encountered this problem too.....   need help ...........

**Comment by JewelPengin** [comment]
Linking - https://github.com/spotbugs/spotbugs-gradle-plugin/issues/11

**Comment by KengoTODA** [comment]
I'll close this issue, please use spotbugs/spotbugs-gradle-plugin#11 instead.
