### ISSUE TITLE
SIC_INNER_SHOULD_BE_STATIC: should be ignored on classes with JUnit5's @Nested

### ISSUE THREAD

**Issue by lqc** [spotbugs/spotbugs#560]
JUnit5 allows grouping tests by nesting test classes with ``@Nested`` annotation. Citing [JUnit's documentation](https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested): 

> Only non-static nested classes (i.e. inner classes) can serve as @Nested test classes. Nesting can be arbitrarily deep [...]

As ``@Nested`` is a runtime annotation, it would be enough to allow filtering errors on annotations of classes they occur.

**Comment by fgenu** [comment]
Saw this happen before, but I can't seem to reproduce it anymore. Perhaps it has been fixed...?

**Comment by akilan07** [comment]
Still this issue exists. Is there any fix?
