### ISSUE TITLE
Rank matcher and its documentation do not match

### ISSUE THREAD

**Issue by matthiasjordan** [spotbugs/spotbugs#566]
According to the documentation, the Rank matcher "matches warnings with a particular bug rank". According to its implementation, it matches if the bug's rank is >= the matcher's rank. This is in contradiction of the documentation. Also, I don't see the use case for "let's break the build if any bug is found that is less important than rank X".

There is a workaround using <Not> and <And> but it makes the filter code ridiculous (matching exactly rank 4 would need to match "4 and not 5").

**Comment by KengoTODA** [comment]
closed by #1359
