### ISSUE TITLE
LO_INVALID_STRING_FORMAT_NOTATION should handle Log4j2 formatter logger

### ISSUE THREAD

**Issue by ksobolew** [spotbugs/spotbugs#572]
Currently when I create a Log4j2 logger like this:
`private static final Logger log = LogManager.getFormatterLogger(Foo.class);`
then spotbugs will complain about using it:
`log.debug("Foo %s barred %d times", theFoo, barTimes);`
with `LO_INVALID_STRING_FORMAT_NOTATION` as it expects me to use the "{}" placeholders, which is wrong for formatter loggers.

**Comment by ThrawnCA** [comment]
This is not a FindBugs core detector; it comes from `fb-contrib`. It was raised and fixed at https://github.com/mebigfatguy/fb-contrib/issues/267
