### ISSUE TITLE
Manifest missing from jar after ./gradlew build

### ISSUE THREAD

**Issue by Sigurthorb** [spotbugs/spotbugs#575]
I am trying to build spotbugs to execute in command line

After running `./gradlew build` in the root folder it generates a build folder with the following structure

`/spotbugs/build$ tree`
.
├── libs
│   └── spotbugs-3.1.3-SNAPSHOT.jar
└── tmp
    └── jar
        └── MANIFEST.MF

3 directories, 2 files

When I execute the jar in the build/lib folder, 
`java -jar spotbugs-3.1.3-SNAPSHOT.jar`
it fails with the following error
`no main manifest attribute, in spotbugs-3.1.3-SNAPSHOT.jar`

**Comment by Sigurthorb** [comment]
Is there anyone who can help me with this?

**Comment by Sigurthorb** [comment]
@iloveeclipse Could you help me out with this?

**Comment by pzygielo** [comment]
@Sigurthorb - why do you expect it to be runnable jar?

**Comment by Sigurthorb** [comment]
@pzygielo There is no documentation on where the runnable jar is built. this was my best guess since I am not getting anything else in the the build directory
