### ISSUE TITLE
how does one get around this

### ISSUE THREAD

**Issue by mebigfatguy** [spotbugs/spotbugs#58]
gradle tasks
Note: in order to honour the org.gradle.jvmargs and/or org.gradle.java.home values specified for this build, it is necessary to fork a new JVM.
To avoid the slowdown associated with this extra process, you might want to consider running Gradle with the daemon enabled.
Please see the user guide chapter on the daemon at http://gradle.org/docs/1.4/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/dave/dev/spotbugs/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'spotbugs'.
> Could not find method jcenter() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by jsotuyod** [comment]
You seem to have installed gradle (possibly a 2.x version)  ans be running that. 

The recommended way is using de gradle wrapper (./gradlew script at the root). That way the proper gradle version ia used for each project with no extra configuration and not needing anyone to install gradle. 

`./gradlew tasks`

**Comment by mebigfatguy** [comment]
yup apt-get'ed it. ok, thanks.
