### ISSUE TITLE
Support for error_prone's @CanIgnoreReturnValue does not work for guava < 23.6-jre

### ISSUE THREAD

**Issue by ArloL** [spotbugs/spotbugs#582]
This is related to #463.

Steps to reproduce:

1. Checkout <https://github.com/ArloL/spotbugs-error-prone-demo>. A demo where `com.google.guava.guava:23.5-jre` `Multimap.put` is used without checking the return value.
2. `mvn verify`
3. See BUILD FAILURE due to RV_RETURN_VALUE_IGNORED
4. Change the guava version to 23.6-jre
5. `mvn verify`
6. See BUILD SUCCESS

Behavior:

spotbugs-maven-plugin 3.1.3 inconsistently reports RV_RETURN_VALUE_IGNORED

Expected behavior:

RV_RETURN_VALUE_IGNORED is not reported for both 23.5-jre and 23.6-jre.

Hope you can reproduce the issue with these steps. If I can be of more assistance just let me know!

**Comment by lqc** [comment]
I can confirm this is an issue on Guava 22 as well. Tried to find the cause, but I can't spot what is the difference between the test and the ``Multimap.put()`` method which is also the culprit for me.

**Comment by KengoTODA** [comment]
https://github.com/google/guava/compare/v23.5...v23.6#diff-4b591cf67ad3e6b49fb4bdedd6af1940R218
Maybe this change is root cause

**Comment by KengoTODA** [comment]
URL above doesn't work……
https://github.com/google/guava/commit/6c2fe3711683897c25054ddad1d79de4c59f32dd#diff-4b591cf67ad3e6b49fb4bdedd6af1940
