### ISSUE TITLE
Dead links in Eclipse Marketplace

### ISSUE THREAD

**Issue by tobymurray** [spotbugs/spotbugs#583]
The Eclipse marketplace listing for SpotBugs (https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin) contains the following:

> Update sites:
> 
>     https://spotbugs.github.io/eclipse/ - provides official releases of SpotBugs Eclipse plugin.
>     https://spotbugs.github.io/eclipse-candidate/ - provides official releases and release candidates of SpotBugs Eclipse plugin.
>     https://spotbugs.github.io/eclipse-latest/ - provides latest SpotBugs Eclipse plugin built from master branch.

All 3 of these links (https://spotbugs.github.io/eclipse/, https://spotbugs.github.io/eclipse-candidate/, https://spotbugs.github.io/eclipse-latest/) presently yield 404s.

**Comment by KengoTODA** [comment]
Duplicated with #510

I'll try to put a simple `index.html` into each URL.
