### ISSUE TITLE
Is it possible to develop a new spotbugs plugin to analyze XML configuration files?

### ISSUE THREAD

**Issue by garciagonzalezdavid** [spotbugs/spotbugs#585]
I am trying to develop a plugin that analyzes spring-security xml configuration files, but it seems this plugin only analyzes Java class files. 

Is it possible to implement a spotbugs plugin that analyzes XML files to search possible problems in configurations?

**Comment by ThrawnCA** [comment]
This sounds like something to raise with the FindSecBugs project, but it would be dependent on https://github.com/spotbugs/spotbugs/issues/186 completing first.
