### ISSUE TITLE
Plugin file handles are leaking

### ISSUE THREAD

**Issue by roberthubert** [spotbugs/spotbugs#589]
When investigating the **File handle to findsecbugs-plugin.jar is leaking** issue reported in sonar-findbugs (https://github.com/spotbugs/sonar-findbugs/issues/128)

I found out that the actual issues are in spotbugs.

Here is the commit that demonstrates the issue and a quick-and-dirty fix:
https://github.com/roberthubert/spotbugs/commit/7c471388c5e946cdc14abf21aea0a4320d43b3d3

I found two major issues in spotbugs:
- URLClassLoaders are not closed
- JarURLConnection are created with the useCaches flag set to true

I would like to kindly ask for a review.
(The code I provided isn't ready for the pull request.)

**Comment by h3xstream** [comment]
Excellent work. 👍 
Is there a PR for the fix ?

**Comment by gtoison** [comment]
This was fixed by https://github.com/spotbugs/spotbugs/pull/2025
