### ISSUE TITLE
Java 9 Illegal reflective access warning

### ISSUE THREAD

**Issue by hheg** [spotbugs/spotbugs#594]
[java] WARNING: An illegal reflective access operation has occurred
     [java] WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/home/user/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
     [java] WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
     [java] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
     [java] WARNING: All illegal access operations will be denied in a future release
Its SpotBugs 3.1.1 and the maven plugin

I would have submitted this to dom4j, but since there are newer versions of dom4j, they probably will tell me to update the dom4j version :)

**Comment by KengoTODA** [comment]
Already fixed by 3.1.2, see 8509aa42474cdde30a7c9ac078a1bd896b3c11e4 and #300.
