### ISSUE TITLE
Adding SpotBugs as plugin causes JavaCC compile failure

### ISSUE THREAD

**Issue by thpr** [spotbugs/spotbugs#612]
Add the following line to the plugins {} section in Gradle
id "com.github.spotbugs" version '1.6.1'

No other changes in the gradle file, now a new task is generated: compileJavaccJava

This new task attempts to compile items not related to compileJavacc, and which are from directories that have external library dependencies that are not comprehended by the javacc source set:
sourceSets {
...
javacc {
java {
srcDirs 'code/src/javacc'
}
}
...
}

nor by:

compileJavacc {
inputDirectory = file('code/src/javacc/')
outputDirectory = file('code/src/java/')
}

The result is a compile failure.

The full repository with the change in place (as well as some additional spotbugs configuration that is valuable to us but not necessary to reproduce the error) can be found here: https://github.com/thpr/pcgen-formula/tree/SpotBugs

**Comment by KengoTODA** [comment]
Let me close this issue, please create another one in spotbugs-gradle-plugin project.
