### ISSUE TITLE
JDK 6 compatibility

### ISSUE THREAD

**Issue by Donnerbart** [spotbugs/spotbugs#636]
Our project still needs to be JDK 6 compatible (I know, not our choice, we have paying customers), but of course we also need to support JDK 9 and newer. So migrating from FindBugs to SpotBugs was a logical step for us.

We used the `annotations` dependency from `com.google.code.findbugs` in version `3.0.0` before. I switched this to `spotbugs-annotations` from `com.github.spotbugs` with version `3.1.3` like recommended in the migration documentation.

We execute SpotBugs with a newer JDK, so no issues there. But our deploy job still runs with JDK 6, which then fails with:
```java
14:25:34 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project hazelcast: Compilation failure
14:25:34 [ERROR] /scratch/jenkins/workspace/Hazelcast-3.x-deploy/hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java:[31,-1] cannot access edu.umd.cs.findbugs.annotations.SuppressFBWarnings
14:25:34 [ERROR] bad class file: edu/umd/cs/findbugs/annotations/SuppressFBWarnings.class(edu/umd/cs/findbugs/annotations:SuppressFBWarnings.class)
14:25:34 [ERROR] class file has wrong version 52.0, should be 50.0
```

I reverted the annotations dependency to `com.google.code.findbugs` for now, which still works fine together. Any recommendation how to improve this?

**Comment by KengoTODA** [comment]
See #19, support for old JDK has been dropped.
