### ISSUE TITLE
SimpleDateFormat string checks

### ISSUE THREAD

**Issue by Hansyperman** [spotbugs/spotbugs#637]
There is a discussion about date format strings on
https://news.ycombinator.com/item?id=17066739 

Can  spotbugs check if bad combinations of date format flags exist in the formatting string?

Some rules, from that discussion:

* %Y can not appear with %M and %d unless also %w appears.  You need probably %y
* %h or %K requires %a, or %H or %k forbids %a.

**Comment by ThrawnCA** [comment]
It’s certainly possible to do. For new, experimental detectors, you might have more success at fb-contrib (https://github.com/mebigfatguy/fb-contrib). Or you could try your hand at writing it, and submit a pull request :)

**Comment by ThrawnCA** [comment]
Sure, but you don't actually need to be assigned. It's more of a nudge than anything.

**Comment by gayatrib** [comment]
Hello, team, just checking in? Is this issue still open and up for grabs for first timers like me?

**Comment by ThrawnCA** [comment]
@gayatrib It's been assigned to @arnab44 so I'd recommend discussing it with arnab first. Otherwise, sure.
