### ISSUE TITLE
Need to increase test coverage

### ISSUE THREAD

**Issue by ThrawnCA** [spotbugs/spotbugs#639]
SpotBugs currently has very low unit test coverage, which makes fixing bugs more risky; it would be easy to unknowingly break things. Increasing coverage would be a very large job, but with substantial benefits.

We should also consider what kind of coverage threshold we want to target, and perhaps start using SonarQube or a similar tool to ensure that new code doesn't reduce coverage.

**Comment by buzzsawddog** [comment]
I would be willing to help out some with this.  Should I make a pull against master or release-3.1?

**Comment by iloveeclipse** [comment]
release-3.1 please.

**Comment by hazendaz** [comment]
closing this as coverage is already tracked by a badge.  So I don't think a ticket telling us the same we already see on readme is necessary given our hundreds of years old tickets.
