### ISSUE TITLE
Null passed for non-null parameter  in MapSqlParameterSource

### ISSUE THREAD

**Issue by lengarski** [spotbugs/spotbugs#642]
I have following problem when pass null to MapSqlParameterSource 

        final MapSqlParameterSource paramMap = new MapSqlParameterSource()
                .addValue("ALERT_ID", null);

In my case "null" passed as parameter to db is correct.

Code | Warning
-- | --
NP | Null passed for non-null parameter of org.springframework.jdbc.core.namedparam.MapSqlParameterSource.addValue(String, Object) in bug.DocDao.test()
  | Bug type NP_NONNULL_PARAM_VIOLATION (click for details) In class bug.DocDaoIn method bug.DocDao.test()Called method org.springframework.jdbc.core.namedparam.MapSqlParameterSource.addValue(String, Object)Argument 2 is definitely null but must not be nullAt DocDao.java:[line 15]

Very short sample source code is attached here. 

https://github.com/lengarski/bug

**Comment by KengoTODA** [comment]
it's problem in spring framework:

* https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/package-info.java#L13
* https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/MapSqlParameterSource.java#L86

if it's really nullable, they need to add `@Nullable` annotation to 2nd argument.
