### ISSUE TITLE
Update to ASM 6.2

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#648]
ASM 6.2 released, see https://mail.ow2.org/wws/arc/asm/2018-05/msg00004.html.

We should consider moving to it.

Note: I haven't checked if this release is compatible or not with SpotBugs.

**Comment by ThrawnCA** [comment]
The release notes sound minor, so it should be backwards-compatible.

**Comment by iloveeclipse** [comment]
Thanks, @KengoTODA !
