### ISSUE TITLE
Best way to add detection of a specific bug to spotbugs?

### ISSUE THREAD

**Issue by Romain-Telecom** [spotbugs/spotbugs#660]
As part of my internship, my job is to make spotbugs capable of detecting a specific bug pattern my tutor has found, what would be the best way to go about it?

I've thought of building my own extension like fb-contrib, but I would first like to know if there is another way.

**Comment by Romain-Telecom** [comment]
My bad, I thought this was the mailing list.

**Comment by ThrawnCA** [comment]
No, raising this here is fine. Do you need to write a new detector, or are you just trying to enable a single existing detector without enabling everything else?

**Comment by Romain-Telecom** [comment]
I'll probably need to write a new detector. [This](https://hal.archives-ouvertes.fr/hal-01518606/document) document explains the bug in part 2. Basically whenever an element stored in a sorted data structure is modified, it needs to be removed and added again, or the structure will break.

**Comment by gtoison** [comment]
It looks like there was no further question so I'll close this issue
