### ISSUE TITLE
Unable to read repository

### ISSUE THREAD

**Issue by droutzahn** [spotbugs/spotbugs#674]
I am trying to download the Eclipse plugin using the Eclipse IDE / Marketplace and I receive the following error:  Unable to read repository at https://spotbugs.github.io/eclipse/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by KengoTODA** [comment]
Could you tell me which JDK you're using? openjdk?

**Comment by Javatii** [comment]
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

**Comment by droutzahn** [comment]
jdk-8u171-windows-x64

**Comment by KengoTODA** [comment]
maybe this is similar question with following one, please have a try:

* https://stackoverflow.com/a/51030918/814928

**Comment by droutzahn** [comment]
Hi Kengo,  I was able to follow the instructions in this attached url and download the spotbugs plugin in eclipse. https://developer.salesforce.com/forums/?id=9060G000000BhSjQAK

**Comment by droutzahn** [comment]
I also added this line to my eclipse.ini file -Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclient4

**Comment by KengoTODA** [comment]
So can we close this issue, @droutzahn ?

**Comment by KengoTODA** [comment]
Thanks!
