### ISSUE TITLE
Long Option names

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs#677]
`L D BC: Unchecked/unconfirmed cast from org.eclipse.jgit.lib.BaseRepositoryBuilder to org.eclipse.jgit.storage.file.FileRepositoryBuilder of return value in com.xenoterracide.gradle.plugin.SemVerPlugin.apply(Project)  At SemVerPlugin.java:[line 26]`

this `L D BC` yeah that's impossible to look up in the docs, is there an option to show the long names? if so can it be documented? if not can you please add this. Also for short names would make more sense to print `L,D,BC` so it can just be copied into the exclude file.

**Comment by creffett** [comment]
@xenoterracide did you try -longBugCodes?

**Comment by xenoterracide** [comment]
no? is that documented somewhere? how do you set it via the gradle plugin?

**Comment by creffett** [comment]
It's documented in the manual page and https://spotbugs.readthedocs.io/en/stable/running.html as an argument to -textui. I don't use spotbugs with Gradle so I can't speak to whether there's a way to enable it through the Gradle plugin.

**Comment by xenoterracide** [comment]
ok, don't know why I didn't find that when I looked before

**Comment by gtoison** [comment]
It looks to me like the question was answered, please don't hesitate to comment here or to open a new one
