### ISSUE TITLE
Spotbugs jar file

### ISSUE THREAD

**Issue by A-AFTAHI** [spotbugs/spotbugs#679]
after building spotbugs using gradlew i can't find the jar file in order to run spotbugs.

**Comment by ThrawnCA** [comment]
How are you trying to run it? Ant? Maven? Gradle?

If you used `./gradlew build`, then it should have installed spotbugs to your local Maven repository, with group ID `com.github.spotbugs` and artifact ID `spotbugs`. It also builds a Gradle plugin. If you need to manually copy the JAR files somewhere, eg if you're using Ant, then you can find them at `spotbugs/build/distributions`.
