### ISSUE TITLE
How to build spotbugs from src instead of using binary distribution

### ISSUE THREAD

**Issue by chengxiao19961022** [spotbugs/spotbugs#690]
How to build spotbugs from src instead of using bin distribution?I have seen the official documents but only found the way to use bin/spotbugs directly. 
I have tried to access into spotbugs/spotbugs and run `../gradlew clean build` . After that I got a Spotbugs.jar(3.4M).Then I replace it to the binary distribution(lib/) but cannot excute spotbugs.
Thanks!

**Comment by ThrawnCA** [comment]
SpotBugs isn't really a self-executable tool; probably the closest you get to that is using Ant. You can also use Maven, Gradle, or your IDE of choice probably has a plugin.

The `spotbugs-ant` directory has Ant tasks you can use.

**Comment by ThrawnCA** [comment]
Normally you would integrate SpotBugs with your build tool of choice. The source tree includes Ant tasks and a Gradle plugin, and there are plugins for Maven and Eclipse.

That said, yes there is a shell script in `spotbugs/bin` that doesn't seem to be working...possibly hasn't been since we forked FindBugs? I'll take a look if I find time.

**Comment by KengoTODA** [comment]
@thrawnCA I guess that it's CLASSPATH problem. SpotBugs jar needs related libraries in the specific path. Instead of the jar file in `build/libs`, unzip zip file `build/distributions` file and use jar file in it.

**Comment by iloveeclipse** [comment]
Shell script works fine.

**Comment by chengxiao19961022** [comment]
@KengoTODA Thanks for your attention! I have unziped zip file `build/distributions/spotbugs-3.1.6-SNAPSHOT.zip` and access into bin.then run `./spotbug`but raise an error:cannot load main class 2.lib.buggy.icns
then replace jar belong to the directory mentioned above. got the same error...

**Comment by chengxiao19961022** [comment]
@ThrawnCA Thank you! I have successfully debug the src code in eclipse so I guess the code is ok. I want to know how the core works and maybe change something.But I stuck in rebuild the project and get the spotbugs.jar to work fine.

**Comment by chengxiao19961022** [comment]
@iloveeclipse Do you mean the shell script in `spotbugs/spotbugs/build/bin` or `spotbugs/spotbugs/build/distribution/spotbugs-3.1.6-SNAPSHOT/bin`?
