### ISSUE TITLE
Deploy Eclipse plugin to update site on maintenance builds

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#701]
Right now we deploy Eclipse plugin to daily update site for the master branch only, see `.travis.yml`.

This was OK before we started 4.x on master, but now we see that the most changes are still happening on 3.x branch.

This leads to the problem, that eclipse daily update site never contain "latest" builds from 3.x branch.

I think we should switch it and start pushing to this site from 3.x branch or create eclipse-maintenance-daily update and push on builds to this site.

@KengoTODA : WDYT?

**Comment by KengoTODA** [comment]
e9ed483854682badf7e28fa9a8954a4d63008679 solved this issue, so next 3.1.6 will be released as expected.

**Comment by iloveeclipse** [comment]
Not sure if I got it right - I meant, *daily* builds on every commit - are they now published to the daily eclipse update site too?

**Comment by KengoTODA** [comment]
So you want to deploy to https://spotbugs.github.io/eclipse-latest/?

If so, is it OK to stop deployment from `master` to this update site?

**Comment by iloveeclipse** [comment]
I think the best would be to have https://spotbugs.github.io/eclipse-stable-latest for 3.x branch and deploy to this update site. If this is too much effort, then just publish 3.x builds to the https://spotbugs.github.io/eclipse-latest/, and stop doing so from master.
