### ISSUE TITLE
Travis CI cannot deploy SNAPSHOT artifacts to Sonatype repo

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#709]
https://travis-ci.org/spotbugs/spotbugs/jobs/407082674

It suddenly failed by 401 Unauthorized error. I've already confirmed the sonatype account is still active and valid.

**Comment by iloveeclipse** [comment]
Yep. Last time job failed again: https://travis-ci.org/spotbugs/spotbugs/builds/408573048
