### ISSUE TITLE
is there release notes?

### ISSUE THREAD

**Issue by radopas** [spotbugs/spotbugs#712]
Hello,
I might be not searching in the correct places, but i don't find a release notes list. Is it possible to have such for every release?

Edit: I've just found the CHANGELOG.md inside the github repository files. Maybe you could create a link to it on the site or the github wiki.

**Comment by KengoTODA** [comment]
We use `CHANGELOG.md` and [release page](https://github.com/spotbugs/spotbugs/releases).
I believe Wiki isn't right place to put release note.
