### ISSUE TITLE
Support Spotbugs Eclipse Preferences in userPrefs

### ISSUE THREAD

**Issue by dlwildschut** [spotbugs/spotbugs#728]
The -userPrefs option for Spotbugs doesn't parse the .epf Preferences produced by the SpotBugs Eclipse Plugin.
The SpotBugs plugin preferences contain the prefix _/instance/com.github.spotbugs.plugin.eclipse/_, which is not removed in the `edu.umd.cs.findbugs.config.UserPreferences.read(@WillClose InputStream in)` method.
Please remove the prefix, which is already being done with _/instance/edu.umd.cs.findbugs.plugin.eclipse/_ from the Preferences produced by the old FindBugs Eclipse plugin.

**Comment by iloveeclipse** [comment]
Do you want to contribute a patch?

**Comment by dlwildschut** [comment]
I created a pull request https://github.com/spotbugs/spotbugs/pull/729, could you please review my changes?
