### ISSUE TITLE
Java 11 Compatibility check: Findbugs annotations

### ISSUE THREAD

**Issue by KryniuPL** [spotbugs/spotbugs#733]
Hi,
We are reaching out to you to check Java 11 compatibility of the library Findbugs annotations.

Could you help us by answering the following questions:

1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

Appreciate your response by 19.08.2018.

Thanks,
Krzysztof Dragan,
PTC Inc. Contractor

**Comment by tcfurrer** [comment]
Java 11 is out, and with FindBugs itself I get:

Warning: Unknown version of Java
edu.umd.cs.findbugs.JavaVersionException: Could not parse Java version string: 11

...which is how I ended up googling and discovered spotbugs... never heard of it until now.  I haven't tried it yet to see whether it has a similar issue...

**Comment by RahulNagekar** [comment]
These links could help.
[Support policy about Java versions issue](https://github.com/spotbugs/spotbugs/issues/787)
[Support policy about Java versions commit](https://github.com/spotbugs/spotbugs/pull/815/commits/cd1959f967137424f3a3798bfa2dd238ddd47913)

**Comment by hazendaz** [comment]
spotbugs works fine on most jdks, closing.
