### ISSUE TITLE
Eclipse plugin load

### ISSUE THREAD

**Issue by alu0100502114** [spotbugs/spotbugs#739]
Cannot load Spotbugs using Eclipse Photon on a macOS High Sierra 10.13.6
It works perfectly using Windows 10.

**Comment by iloveeclipse** [comment]
What do you mean by load? Installation into Eclipse? Any errors in the log?

**Comment by iloveeclipse** [comment]
?  You said SpotBugs can't be loaded, and now the opposite? Can you please describe the problem in a way an average developer can understand it?

**Comment by alu0100502114** [comment]
Problem description to include average developers:
Spotbugs WORKS using Windows 10 Eclipse Photon.
Spotbugs DOES NOT WORK using same Eclipse on Mac High Sierra 10.13.6.
No message on log files.

**Comment by hazendaz** [comment]
closing as old and not enough details to the problem.  Most of this use case would no longer apply.  Eclipse doesn't use the same naming scheme and so much has changed in last 5 years.  If still an issue on latest, we can look at, in that case open new ticket.
