### ISSUE TITLE
Update to ASM 6.2.1 for initial JDK 12 support

### ISSUE THREAD

**Issue by iamatgit** [spotbugs/spotbugs#741]
ASM version 6.2.1 was released https://asm.ow2.io/versions.html and it has support for JDK 12 class file version.

Please consider moving to it.

**Comment by iamatgit** [comment]
Patch attached works when tested.

------
diff --git a/CHANGELOG.md b/CHANGELOG.md
index bd690021f..6ef51a56b 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -7,6 +7,7 @@ Currently the versioning policy of this project follows [Semantic Versioning v2.
 ## Unreleased - 2018-??-??
 
 ### Fixed
+* Update asm to 6.2.1 for better Java 12 support ([#741](https://github.com/spotbugs/spotbugs/issues/741))
 * Don't print exit code related output if '-quiet' is passed ([#714](https://github.com/spotbugs/spotbugs/pull/714))
 * Don't underflow the stack at INVOKEDYNAMIC when modeling stack frame types ([#500](https://github.com/spotbugs/spotbugs/issues/500))
 
diff --git a/spotbugs/build.gradle b/spotbugs/build.gradle
index 6f3b00f10..dca91c454 100644
--- a/spotbugs/build.gradle
+++ b/spotbugs/build.gradle
@@ -38,12 +38,12 @@ sourceSets {
 }
 
 dependencies {
-  compile 'org.ow2.asm:asm:6.2'
-  compile 'org.ow2.asm:asm-analysis:6.2'
-  compile 'org.ow2.asm:asm-commons:6.2'
-  compile 'org.ow2.asm:asm-tree:6.2'
-  compile 'org.ow2.asm:asm-util:6.2'
-  compile 'org.ow2.asm:asm-xml:6.2'
+  compile 'org.ow2.asm:asm:6.2.1'
+  compile 'org.ow2.asm:asm-analysis:6.2.1'
+  compile 'org.ow2.asm:asm-commons:6.2.1'
+  compile 'org.ow2.asm:asm-tree:6.2.1'
+  compile 'org.ow2.asm:asm-util:6.2.1'
+  compile 'org.ow2.asm:asm-xml:6.2.1'
   compile 'org.apache.bcel:bcel:6.2'
   compile 'net.jcip:jcip-annotations:1.0'
   compile 'org.dom4j:dom4j:2.1.0'
diff --git a/spotbugs/etc/MANIFEST-findbugs.MF b/spotbugs/etc/MANIFEST-findbugs.MF
index 367f365eb..174b2d574 100644
--- a/spotbugs/etc/MANIFEST-findbugs.MF
+++ b/spotbugs/etc/MANIFEST-findbugs.MF
@@ -1,3 +1,3 @@
 Manifest-Version: 1.0
 Main-Class: edu.umd.cs.findbugs.LaunchAppropriateUI
-Class-Path: bcel.jar dom4j-2.1.0.jar jaxen-1.1.6.jar asm-6.2.jar asm-analysis-6.2.jar asm-commons-6.2.jar asm-tree-6.2.jar asm-util-6.2.jar asm-xml-6.2.jar jsr305.jar commons-lang-2.6.jar
+Class-Path: bcel.jar dom4j-2.1.0.jar jaxen-1.1.6.jar asm-6.2.1.jar asm-analysis-6.2.1.jar asm-commons-6.2.1.jar asm-tree-6.2.1.jar asm-util-6.2.1.jar asm-xml-6.2.1.jar jsr305.jar commons-lang-2.6.jar
diff --git a/spotbugs/etc/MANIFEST-findbugsGUI.MF b/spotbugs/etc/MANIFEST-findbugsGUI.MF
index d84793cae..8ba157ac5 100644
--- a/spotbugs/etc/MANIFEST-findbugsGUI.MF
+++ b/spotbugs/etc/MANIFEST-findbugsGUI.MF
@@ -1,3 +1,3 @@
 Manifest-Version: 1.0
 Main-Class: edu.umd.cs.findbugs.LaunchAppropriateUI
-Class-Path: bcel.jar dom4j-2.1.0.jar jaxen-1.1.6.jar asm-6.2.jar asm-analysis-6.2.jar asm-commons-6.2.jar asm-tree-6.2.jar asm-util-6.2.jar asm-xml-6.2.jar jsr305.jar commons-lang-2.6.jar plastic.jar
+Class-Path: bcel.jar dom4j-2.1.0.jar jaxen-1.1.6.jar asm-6.2.1.jar asm-analysis-6.2.1.jar asm-commons-6.2.1.jar asm-tree-6.2.1.jar asm-util-6.2.1.jar asm-xml-6.2.1.jar jsr305.jar commons-lang-2.6.jar plastic.jar
diff --git a/spotbugs/jnlp/findbugs.jnlp b/spotbugs/jnlp/findbugs.jnlp
index 548876a03..b08ca24ae 100644
--- a/spotbugs/jnlp/findbugs.jnlp
+++ b/spotbugs/jnlp/findbugs.jnlp
@@ -21,12 +21,12 @@
     <jar href="AppleJavaExtensions.jar"/>
     <jar href="bcel.jar"/>
     <jar href="dom4j-2.1.0.jar"/>
-    <jar href="asm-6.2.jar"/>
-    <jar href="asm-analysis-6.2.jar"/>
-    <jar href="asm-commons-6.2.jar"/>
-    <jar href="asm-tree-6.2.jar"/>
-    <jar href="asm-util-6.2.jar"/>
-    <jar href="asm-xml-6.2.jar"/>
+    <jar href="asm-6.2.1.jar"/>
+    <jar href="asm-analysis-6.2.1.jar"/>
+    <jar href="asm-commons-6.2.1.jar"/>
+    <jar href="asm-tree-6.2.1.jar"/>
+    <jar href="asm-util-6.2.1.jar"/>
+    <jar href="asm-xml-6.2.1.jar"/>
     <jar href="jaxen-1.1.6.jar"/>
     <jar href="commons-lang-2.6.jar"/>
     <jar href="jsr305.jar"/>
diff --git a/spotbugs/src/sampleXml/analysisResultsWithFilterAndUserAnnotations.xml b/spotbugs/src/sampleXml/analysisResultsWithFilterAndUserAnnotations.xml
index db9b7d5ad..76d84ef34 100644
--- a/spotbugs/src/sampleXml/analysisResultsWithFilterAndUserAnnotations.xml
+++ b/spotbugs/src/sampleXml/analysisResultsWithFilterAndUserAnnotations.xml
@@ -10,12 +10,12 @@
     <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/dom4j-2.1.0.jar</AuxClasspathEntry>
     <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/AppleJavaExtensions.jar</AuxClasspathEntry>
     <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/junit.jar</AuxClasspathEntry>
-    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-6.2.jar</AuxClasspathEntry>
-    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-analysis-6.2.jar</AuxClasspathEntry>
-    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-commons-6.2.jar</AuxClasspathEntry>
-    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-tree-6.2.jar</AuxClasspathEntry>
-    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-util-6.2.jar</AuxClasspathEntry>
-    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-xml-6.2.jar</AuxClasspathEntry>
+    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-6.2.1.jar</AuxClasspathEntry>
+    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-analysis-6.2.1.jar</AuxClasspathEntry>
+    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-commons-6.2.1.jar</AuxClasspathEntry>
+    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-tree-6.2.1.jar</AuxClasspathEntry>
+    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-util-6.2.1.jar</AuxClasspathEntry>
+    <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/asm-xml-6.2.1.jar</AuxClasspathEntry>
     <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/jaxen-1.1.6.jar</AuxClasspathEntry>
     <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/jsr305.jar</AuxClasspathEntry>
     <AuxClasspathEntry>/Users/pugh/Documents/fb-trunk/findbugs/lib/jFormatString.jar</AuxClasspathEntry>
--------

**Comment by iamatgit** [comment]
Attached patch file works fine.

[741.txt](https://github.com/spotbugs/spotbugs/files/2327060/741.txt)

**Comment by KengoTODA** [comment]
Thanks for your patch, I applied it just now!
