### ISSUE TITLE
Maintain (a fork of) m2e-code-quality under the https://github.com/spotbugs org?

### ISSUE THREAD

**Issue by vorburger** [spotbugs/spotbugs#742]
Fork https://github.com/m2e-code-quality/m2e-code-quality under https://github.com/spotbugs to enable a real community around maintaining it, and avoid getting stuck as in https://github.com/m2e-code-quality/m2e-code-quality/issues/110 ?

Personally I wouldn't really have time, but I laid the foundation over in https://github.com/m2e-code-quality/m2e-code-quality/issues/110, and there seem to be other people interested there, perhaps some of them want to step up? I would.. "stay around".

see related earlier #482 and #486 (@sewe)

**Comment by victornoel** [comment]
Good idea, I would be a user, I can contribute (testing, investigating, maybe some PRs), but I cannot maintain.

I wonder if spotbugs should take the responsibility of all the tools supported by m2e-code-quality or instead if it should just start from the one for findbugs/spotbugs… It would be best for everyone if it did take responsibility of all, but in practice…

**Comment by hd42** [comment]
I could assist with tests and bug fixes but am not sure I'd have the time to maintain the project.

**Comment by antoine-morvan** [comment]
Hi, I'd gladly close(/archive) my fork (see https://github.com/m2e-code-quality/m2e-code-quality/issues/120#issuecomment-401296997) and redirect the update site URL :+1:

**Comment by victornoel** [comment]
For the record I've made an update site with support spotbugs and eclipse photon: https://victornoel.github.io/m2e-code-quality/site/

I won't be really maintaining it though, don't consider this a replacement for what is discussed here…

**Comment by pgalbraith** [comment]
@vorburger I'm not too familiar with GitHub, but checking https://github.com/orgs/m2e-code-quality/people I only see you there, is it possible the original owner has passed on control to you already, to continue maintaining the original m2e-code-quality/m2e-code-quality repo?

**Comment by vorburger** [comment]
Closing this issue, because (as far as I can tell from the comments above), no spotbugs commiter has jumped up with joy to accept a move of m2e-code-quality under this repo and maintain it for free... :smile: Instead I'll do my best to provide the minimum possible "keep on life support" over in m2e-code-quality itself; see https://github.com/m2e-code-quality/m2e-code-quality/issues/124.
