### ISSUE TITLE
Inconsistency between maven and eclipse plugin

### ISSUE THREAD

**Issue by victornoel** [spotbugs/spotbugs#745]
I'm trying to run the maven plugin and the eclipse plugin with the same configuration (I hope) on the same projects, but the maven plugin find bugs such as `URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD` while the eclipse plugins find nothing.

There is no error anywhere in Eclipse and on other projects it can detect bugs, so I think it's working.

Is this some known problem?

**Comment by victornoel** [comment]
What particular thing is that I set-up the project in eclipse via its properties, so the global preferences have not the same settings.
Could it be that the project properties are not properly overriding the global one?

**Comment by ThrawnCA** [comment]
Can you provide a sample of code that is treated differently?

**Comment by victornoel** [comment]
@ThrawnCA it seemed my eclipse project was in a bad state and after changing the confidence threshold setting to low and then back to medium, bugs started to appear.

Sorry for the noise :)

**Comment by ThrawnCA** [comment]
No need to apologise. Good job sorting it out, and good luck squashing the bugs.
