### ISSUE TITLE
upgrade to 3.1.6 from 3.1.5 result in stacktrace in maven build output

### ISSUE THREAD

**Issue by romani** [spotbugs/spotbugs#746]
all details are at https://github.com/checkstyle/checkstyle/issues/6098

I not sure if spotbugs is working well, but build is not failing.

FYI: I am not sure that I make case like required at https://github.com/spotbugs/spotbugs/blob/release-3.1/.github/CONTRIBUTING.md , but issue is not obvious I could try.

**Comment by romani** [comment]
moved https://github.com/spotbugs/spotbugs-maven-plugin/issues/74

**Comment by rnveach** [comment]
If it wasnt clear, this issue was re-opened. See https://github.com/spotbugs/spotbugs/issues/746#issuecomment-417502149

**Comment by romani** [comment]
for some reason we can not reproduce problem on 3.1.9
