### ISSUE TITLE
Build fails on Eclipse plugin - missing local.properties

### ISSUE THREAD

**Issue by ThrawnCA** [spotbugs/spotbugs#75]
I can't yet build the project; the ``eclipsePlugin`` module complains that I'm missing local.properties. Anyone have any suggestions? Am I meant to have copied it from another file?

**Comment by jsotuyod** [comment]
It needs to point to an Eclipse plugin folder. Check [how we do it on Travis](https://github.com/spotbugs/spotbugs/blob/master/.travis.yml#L23)

**Comment by ThrawnCA** [comment]
Umm...what if I (or whoever is building it) don't care about building an Eclipse plugin?

**Comment by jsotuyod** [comment]
This was already discussed in #40. In the future we can tune the gradle build to either skip the eclipse plugin build or fail with a better error if the property is missing.

In the meantime, you can simply do `./gradlew :findbugs:build` to just build the library.

**Comment by ThrawnCA** [comment]
OK, that works. Thanks.

Do you want me to work on said fine-tuning?

**Comment by jsotuyod** [comment]
Feel free to do so if you are comfortable with Gradle! If you aren't don't worry, we will eventually get to that.
