### ISSUE TITLE
404 (not found) on the links for the 3.1.7 distribution files

### ISSUE THREAD

**Issue by eant60** [spotbugs/spotbugs#755]
I get a 404 (not found) on the links for the 3.1.7 distribution files...

http://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/3.1.7/spotbugs-3.1.7.tgz

http://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/3.1.7/spotbugs-3.1.7.zip

**Comment by ijuma** [comment]
cc @KengoTODA

**Comment by ijuma** [comment]
@eant60 those links work for me.

**Comment by KengoTODA** [comment]
Yes finally deploy finished successfully. I will close this.
