### ISSUE TITLE
(Eclipse) run_automatically key in UserPreferences

### ISSUE THREAD

**Issue by Alexander-Krause** [spotbugs/spotbugs#761]
We use the Spotbugs Eclipse plugin for development and want to check-in the Eclipse Spotbugs configuration, i.e., `edu.umd.cs.findbugs.core.prefs` at the time of writing, in our source control. 

The configuration file contains all settings but does not save the `Run automatically` setting of the Eclipse GUI dialog. Therefore, even after a simple Eclipse restart, the setting will be set to uncheck.

Is there a reason for this behavior? Might this be an improvement?

**Comment by iloveeclipse** [comment]
The setting you mention is not stored in the edu.umd.cs.findbugs.core.prefs, it is project builder /nature change and stored in .project. No, there can be no improvement here, you have to track .projects too.
