### ISSUE TITLE
Release Maven plugin 3.1.7

### ISSUE THREAD

**Issue by dmitry-timofeev** [spotbugs/spotbugs#764]
Hi,

It seems spotbugs maven plugin was not uploaded to the repository when 3.1.7 was released. Would you please publish it?

### Workaround
```xml
        <plugin>
           <groupId>com.github.spotbugs</groupId>
           <artifactId>spotbugs-maven-plugin</artifactId>
           <version>3.1.6</version>
           <dependencies>
             <dependency>
               <groupId>com.github.spotbugs</groupId>
               <artifactId>spotbugs</artifactId>
               <version>3.1.7</version>
             </dependency>
           </dependencies>
         </plugin>
```

See:
- https://search.maven.org/search?q=a:spotbugs-maven-plugin
- #763

**Comment by KengoTODA** [comment]
Please see https://github.com/spotbugs/spotbugs-maven-plugin/issues, it seems that it's blocked by the release from other products.

**Comment by dmitry-timofeev** [comment]
I see, thanks!
