### ISSUE TITLE
UR_UNINIT_READ_CALLED_FROM_SUPER_CONSTRUCTOR invalid in Scala

### ISSUE THREAD

**Issue by nilskp** [spotbugs/spotbugs#768]
This is correct in Java, where the super constructor is called, first thing.

However this is not the case in Scala. Witness the following REPL output:

```scala
scala> abstract class Foo { def name: String; val lowerName = name.toLowerCase }
defined class Foo

scala> class Bar(val name: String) extends Foo
defined class Bar

scala> new Bar("HANK")
res9: Bar = Bar@42e14655

scala> res9.lowerName
res10: String = hank
```

The reasons this works is that Scala's compiler assigns fields _before_ calling super constructor. The byte code for the above code:
```
0: aload_0
1: aload_1
2: putfield      #25                 // Field name:Ljava/lang/String;
5: aload_0
6: invokespecial #32                 // Method Foo."<init>":()V
9: return
```

**Comment by nilskp** [comment]
I guess this should just be disabled through a filter. Sorry for the noise.

**Comment by ThrawnCA** [comment]
Even if the `name` field isn't technically uninitialized, as far as I can see it will still be `null` at the point where `lowerName` is assigned, so...this still doesn't look like good code. An inline assignment that depends on the value of a field that *isn't* initialized inline doesn't seem like a good move.

**Comment by nilskp** [comment]
@ThrawnCA, no it actually works as expected.

**Comment by dsilvasc** [comment]
Note that `name` is `null` when the scala subclass defines `name` as a member instead of a constructor argument.  See https://github.com/scala/bug/issues/11401 for an example.
