### ISSUE TITLE
spotbugs Eclipse install gives unsigned content security warning

### ISSUE THREAD

**Issue by pjsanfil** [spotbugs/spotbugs#779]
Tried to install using the [platformUiTools.p2f](http://git.eclipse.org/c/platform/eclipse.platform.ui.git/plain/releng/org.eclipse.ui.releng/platformUiTools.p2f) and get the warning shown.

![eclipse plugin dev tool install warning 2018-10-20](https://user-images.githubusercontent.com/17651080/47269302-73e7ac80-d521-11e8-8eb8-effb2d966e7d.png)

**Comment by iloveeclipse** [comment]
What Eclipse here says is that the plugin is not signed, and this is true, I haven't time yet to look into signing business.

Nevertheless, you can ignore the warning and continue.

**Comment by KengoTODA** [comment]
@iloveeclipse To sign .jar files, do we need to purchase an original domain such as `spotbugs.org` or `spotbugs.io`? Is there way that needs less running cost (both money and manual task)?

I've checked the following site:

* https://wiki.eclipse.org/JAR_Signing

**Comment by iloveeclipse** [comment]
I don't know, I've never spent time on this.

**Comment by iloveeclipse** [comment]
I would ask in the eclipse forums https://www.eclipse.org/forums/

**Comment by KengoTODA** [comment]
Thanks, it's really huge and I cannot choose which forum is suitable to asl for me.

...maybe at https://www.eclipse.org/forums/index.php/f/14/ ?

**Comment by iloveeclipse** [comment]
Yep

**Comment by KengoTODA** [comment]
I've posted in that forum, and waiting approval from its admin.

**Comment by KengoTODA** [comment]
I tried to sign jar files by certs provided by [Let's Encrypt](https://letsencrypt.org/).
It can sign but `jarsigner` command prints following warning:

> Warning:
> The signer certificate's ExtendedKeyUsage extension doesn't allow code signing.
> The signer certificate will expire within six months.

Latter one is OK, however I'm not sure former one is acceptable or not.

### code
```sh
$ openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -name eclipse-plugin -out ~/spotbugs.p12
$ keytool -importkeystore -deststorepass $PASS -srcstorepass $PASS -destkeystore spotbugs.jks -srckeystore spotbugs.p12 -srcstoretype PKCS12
$ jarsigner -verbose \
  -keystore spotbugs.jks \
  -storepass $PASS \
  -keypass $PASS \
  -tsa http://timestamp.digicert.com \
  path/to/plugin-jar.jar \
  eclipse-plugin
```
