### ISSUE TITLE
IllegalArgumentException in OpcodeStack.constantToInt

### ISSUE THREAD

**Issue by jsotuyod** [spotbugs/spotbugs#78]
Spotbugs issue to track https://github.com/findbugsproject/findbugs/issues/125

Provided sample code is:

```
package fb;

import java.io.File;
import java.io.PrintWriter;

public class FbTest {
    
    public void test() throws Exception {
        {
            String a;
            String b;
            String c = "";
        }
        {
            String d;
            for (int i = 0; i < 3; i++) {
            }
            String e;
            for (int i = 0; i < 3; i++) {
                try (PrintWriter writer = new PrintWriter(new File(""), "UTF-8")) {
                }
            }
        }
    }
}
```

**Comment by jsotuyod** [comment]
The issue is caused at `OpcodeStackDetector.visitCode` when doing `OpcodeStack.getJumpInfo, during   `stack.resetForMethodEntry(this)`. There is a stack corruption. The bytecode is (redacted):

```
         2: astore_3  // register 3 is initialized to "" (variable String c)
...
        16: iconst_0
        17: istore_3 // register 3 is overwritten with value 0 (for int i)
...
        81: iinc          3, 1 // add 1 to register 3
```

However, when analyzed, at the point of the `iinc` instruction, the empty string is still found and the error raises.

However, this does not happen to all `OpcodeStackDetector` implementations, only to `UnreadFields` and `OverridingEqualsNotSymmetrical`. I'm still not sure what is so special about these two.

**Comment by iloveeclipse** [comment]
The snippet doesn't trigger any error on master anymore, similar stack however is in #893 and I have a patch, so closing this one.
