### ISSUE TITLE
Write docs that explain support policy about Java versions 

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#787]
We have no document about Java support policy, so we should have document that explains:

1. SpotBugs is built on JDK8.
2. Java8 is supported to scan.
3. Java11 and 12+ are also supported, but we have unclosed problem listed in GitHub issues.
4. Java 9, 10 and older than 8 are not supported.

**Comment by forresthopkinsa** [comment]
> SpotBugs can scan bytecode (class files) generated by JDK8 and newer versions. However, support for Java 11 and newer is still experimental.

Is this still accurate?
