### ISSUE TITLE
New rule for checking runtime PatternSyntaxException in regex usages

### ISSUE THREAD

**Issue by lasselindqvist** [spotbugs/spotbugs#798]
Inspired by comment https://github.com/spotbugs/spotbugs/pull/797#issuecomment-438466959 on #797 
implement a new detector which finds faulty regex patterns.

The detector should find faulty regexes in standard library methods
Pattern.compile(String regex)
Pattern.compile(String regex, int flags)
String.replaceFirst(String regex, String replacement)
String.replaceAll(String regex, String replacement)
String.split(String regex, int limit)
String.split(String regex)
String.matches(String regex)

The warning should happen when the parameter is a constant or otherwise easily determined.
Some other possible methods might be missing here.

**Comment by ThrawnCA** [comment]
A simple example:

    import java.util.regex.Pattern;

    public class BadPatternSyntax {
        public static final Pattern INVALID_PATTERN = Pattern.compile("[abc");
    }

**Comment by lasselindqvist** [comment]
Note: RE_POSSIBLE_UNINTENDED_PATTERN also catches unintended regexes though not in this way. So while implementing, it is good to use common methods and maybe extract a common superclass for the existing BadSyntaxForRegularExpression detector and the new detector.

**Comment by lasselindqvist** [comment]
I checked the codebase and BadSyntaxForRegularExpression.java already produces RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSION if it finds faulty syntax.

**Comment by fathalls** [comment]
Hi! I'd like to work on this - is it still up for grabs?

**Comment by gtoison** [comment]
> I checked the codebase and BadSyntaxForRegularExpression.java already produces RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSION if it finds faulty syntax.

Indeed this feature already seems to exist so we can close this
