### ISSUE TITLE
Findbugs plugin-3.8.0 in Sonarqube version 7.4 causing error 

### ISSUE THREAD

**Issue by SreeSusmitha** [spotbugs/spotbugs#802]
I’m trying to analyse using Sonarqube version 7.4 passing maven goal sonar:sonar and getting the following error which is related to findbugs plugin

**org.sonar.plugins.findbugs.FindbugsConfiguration has unsatisfied dependency ‘class** org.sonar.plugins.findbugs.FindbugsProfileExporter’ for constructor ‘public org.sonar.plugins.findbugs.FindbugsConfiguration(org.sonar.api.batch.fs.FileSystem,org.sonar.api.config.Configuration,org.sonar.api.profiles.RulesProfile,org.sonar.plugins.findbugs.FindbugsProfileExporter,org.sonar.plugins.java.api.JavaResourceLocator)’ from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@60f21960:312<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@e76b097:233<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@3dffc764:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@58dad04a:50<

Please reply ASAP. Thank you.

**Comment by ThrawnCA** [comment]
This sounds like a defect in the SonarQube FindBugs plugin, not in SpotBugs. I'm not sure where to find the issue tracker for that plugin, but it isn't here.
