### ISSUE TITLE
enhanced xml options not recognized as textui mode

### ISSUE THREAD

**Issue by sjjianshen** [spotbugs/spotbugs#806]
In the latest release version 3.1.9, when I run spotbugs in command line with xml enhanced options, it werenot recognized as textui mode.
```
java -jar ./lib/spotbugs.jar -high -quiet -xml:withMessages /path/to/classFiles
```
![image](https://user-images.githubusercontent.com/9349921/49127977-6a154e00-f304-11e8-91e9-6a26cdd8d169.png)

It`s not a serious issue though, we can specify the textui mode in our command, but it will be nice if we can skip a param

**Comment by iloveeclipse** [comment]
Do you want to contribute a patch?

**Comment by sjjianshen** [comment]
@iloveeclipse yeah although a small fix, it's cool for me to contribute, please help me review the PR https://github.com/spotbugs/spotbugs/pull/807

**Comment by iloveeclipse** [comment]
It is not yet merged.

**Comment by sjjianshen** [comment]
OK, got it
