### ISSUE TITLE
spotbugs-maven-plugin 3.1.9 not available in maven repos

### ISSUE THREAD

**Issue by kemitix** [spotbugs/spotbugs#812]
The `spotbugs` and `spotbugs-annotations` 3.1.9 artifacts are available, but `spotbugs-maven-plugin` appears to be missing.

**Comment by KengoTODA** [comment]
Actually [spotbugs-maven-plugin](https://github.com/spotbugs/spotbugs-maven-plugin/) is not released yet.
It follows the different release cycle with spotbugs itself.

If you want to use spotbugs 3.1.9 with spotbugs-maven-plugin 3.1.8, see [official document](https://spotbugs.readthedocs.io/en/stable/maven.html) and add `<dependency>` into your `pom.xml`.
