### ISSUE TITLE
SLF4J as transitive dependency since 3.1.9

### ISSUE THREAD

**Issue by mkordas** [spotbugs/spotbugs#823]
My build has failed after upgrading SpotBugs in Gradle from 3.1.8 to 3.1.9. due to duplicate binding on the classpath. And indeed, [3.1.9 POM](http://central.maven.org/maven2/com/github/spotbugs/spotbugs/3.1.9/spotbugs-3.1.9.pom) contains this entry but previously it didn't:
```xml
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>1.8.0-beta2</version>
  <scope>compile</scope>
</dependency>
```
Error:
```
SLF4J: Found binding in [jar:file:/app/gradle-user-home/caches/jars-3/0a7bcfe1020d8b116d1ed7440a74e963/gradle-api-4.2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/gradle-user-home/wrapper/dists/gradle-4.2.1-all/ceplzodv028ati8m526tu6dfe/gradle-4.2.1/lib/gradle-logging-4.2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]

**Comment by KengoTODA** [comment]
Yes we introduced SLF4J from this version, to eliminate all stdout and stderr for logging.

I guess your problem comes from old Gradle version, consider to upgrade to 5.0 or later.

**Comment by KengoTODA** [comment]
I'll close this stale issue, please feel free to reopen.

**Comment by mkordas** [comment]
@KengoTODA we're still working on Gradle update, I'll let you know if problem goes away with Gradle 5.0

**Comment by daggerok** [comment]
Hello,

using gradle 5.2.1 ans also has similar issue on spotbugsTest task execution:

```bash
> Task :modules:thymeleaf:spotbugsTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :apps:rest:app:spotbugsTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

# ...
```

---
Regards,
Maksim

**Comment by binkley** [comment]
Still a thing with Gradle 5.1.1 and SpotBugs plugin.

**Comment by oneiros-de** [comment]
See also https://github.com/spotbugs/spotbugs-gradle-plugin/issues/133
