### ISSUE TITLE
Compilation errors in spotbugs Eclipse projects after #828

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#829]
PR #828 breaks compilation inside Eclipse, com.apple dependency is missing on the generated .classpath files. Also exported architecture package is marked as missing in the manifest. Later fix is trivial, the com.apple however is a bit more complicated, I don't see where it was configured before.

**Comment by KengoTODA** [comment]
I believe that we can close this issue. Feel free to reopen if necessary.
