### ISSUE TITLE
Import some of the fb-contrib utils

### ISSUE THREAD

**Issue by ThrawnCA** [spotbugs/spotbugs#83]
`fb-contrib` has some helpful constants and utility methods around things like signature creation. These could move to SpotBugs core and help with cleaning it up.

**Comment by levonk** [comment]
It would be great to add the http://h3xstream.github.io/find-sec-bugs/ checkers too.

**Comment by jsotuyod** [comment]
@levonk we won't be adding checkers from existing plugins. Those are stand alone projects and opt-in by users even if we may recommend them.

What this issue concerns however, are helpers and utilities that, even if created by third party plugin developers, have proved to be useful for all kinds of detectors, either third parties or not.

**Comment by iloveeclipse** [comment]
Feel free to provide a PR with replacing existing code through some use of better utilities. Adding utilities just because they could be useful in the future does not make sense.
