### ISSUE TITLE
Ant task improvement. Exclude individual bug patterns instead of detectors

### ISSUE THREAD

**Issue by FoxyBOA** [spotbugs/spotbugs#833]
It would be nice to have a possibility to exclude individual bug patterns (e.g. RV_RETURN_VALUE_IGNORED_BAD_PRACTICE) instead of a detector (MethodReturnCheck). The detector could have useful bug patterns except one (my case with MethodReturnCheck which I would like to keep except RV_RETURN_VALUE_IGNORED_BAD_PRACTICE)

**Comment by KengoTODA** [comment]
the filter is what you need.

https://spotbugs.readthedocs.io/en/stable/filter.html

**Comment by FoxyBOA** [comment]
Yes. Got it

**Comment by FoxyBOA** [comment]
Yes. Got it
