### ISSUE TITLE
release-3.1 contains unexpected changes introduced by #832

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#849]
The base branch of #832 was unexpectedly `release-3.1`, that should be `master` according to its PR subject. We need to exclude 4bd6e43146e0739437d76f21298420efc5c4a4ad from `release-3.1`.

Here is current my idea about how to fix this problem:

```
git checkout 554d102c963fd8b318339ea046bb78385385cf8d
git branch -D release-3.1
git checkout -b release-3.1
git cherry-pick 8cd5f90266d2706a72176858ff0803586bd47fc5..0d1b933dc92a398ebf0cbbac7dca97585b577303
git push origin +HEAD
```

You can see [the new branch created by this method](https://github.com/spotbugs/spotbugs/commits/fixed-release-3.1) at GitHub.

**Comment by KengoTODA** [comment]
@spotbugs/core-devs sorry for my careless, I made this problem when I propose &amp; merge that PR.

This fix needs force-push so I want to ask some of you to confirm that my proposal is right to follow. Please review this process and [the fixed-release-3.1 branch](https://github.com/spotbugs/spotbugs/commits/fixed-release-3.1) which will be new `release-3.1` branch after this fix.

**Comment by henrik242** [comment]
Why do you need a force push? Just revert the offending commit(s) as usual

**Comment by KengoTODA** [comment]
I prefer force-push to make Git history intuitive. It helps us to ease tracing change by `git blame` etc.

I've prepared [the reverted branch](https://github.com/spotbugs/spotbugs/commits/reverted-release-3.1) as reference, but I still prefer force-push solution...

**Comment by iloveeclipse** [comment]
I haven't looked into details yet, but were there *breaking* changes merged? Do we actually *need* to change anything?

I'm not against force push, if there would be a quick note/recipe how to fix the cloned repos. 
Revert will probably cause too many "false positive" results in git blame.

**Comment by KengoTODA** [comment]
OK I will propose a PR to merge a commit to revert. I've confirmed that its contents (files) is totally same with my branch that does not contains that PR. Thank you guys!
