### ISSUE TITLE
Allow multiple output types

### ISSUE THREAD

**Issue by mcandre** [spotbugs/spotbugs#857]
Could we get simultaneous XML and HTML reports, so that CI systems can provide both machine- and human-consumable reports at once?

**Comment by iloveeclipse** [comment]
Yes. Patches are welcome.

**Comment by Vampire** [comment]
Isn't this supported since 4.5.0?

**Comment by Vampire** [comment]
Yes it is.
https://github.com/spotbugs/spotbugs/releases/tag/4.5.0
> Multiple types of report can be generated in batch. Set multiple commandline options for report configuration like -html=report/spotbugs.html -xml:withMessages=report/spotbugs.xml. 

So this can be closed
