### ISSUE TITLE
[Java-11] jdk 11.0.1 false positive: FCBL_FIELD_COULD_BE_LOCAL

### ISSUE THREAD

**Issue by RemusRD** [spotbugs/spotbugs#865]
The following class:  

    package org.sample.models;

    import java.math.BigDecimal;
    import java.time.LocalDateTime;
    import java.util.Objects;

    public final class User {

    private String state;

    private User() {}

    private User(Builder builder) {
        this.state = builder.state;
    }

    public String getState() {
        return state;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User that = (User) o;
        return  Objects.equals(state, that.state);
    }

    @Override
    public int hashCode() {
        return Objects.hash(state);
    }

    public static final class Builder {

        private String state;

        public Builder withState(String state) {
            this.state = state;
            //Class org.sample.models.User$Builder defines fields that are used only as locals
            return this;
        }

        public User build() {
            return new User(this);
        }
    }
    }

This is the recommended way of implementing the Builder pattern by "Effective Java", it should not prompt an exception.

compiled with jdk OpenJDK Runtime Environment 18.9 (build 11.0.1+13) and running spotbugs 3.1.8(findbugs 3.9.1) generates a false positive.

No issues when compiling with jdk 1.8

**Comment by gtoison** [comment]
This bug is raised by [fb-contrib](https://github.com/gtoison/fb-contrib) so the issue should reported in the issue tracker of the project

**Comment by mpet** [comment]
@gtoison is this really completed? I just checked the link https://github.com/gtoison/fb-contrib but it has been under investigation for a while.

**Comment by gtoison** [comment]
I have no idea unfortunately, I have closed the issue here meaning that this won't be fixed by SpotBugs, but I did not follow up with fb-contrib

**Comment by JuditKnoll** [comment]
I think the confusion is because @gtoison, you linked your own fork, not the official one: https://github.com/mebigfatguy/fb-contrib 
@mpet you can check it there.

**Comment by gtoison** [comment]
Ah.. I see it now, sorry for the confusion!

**Comment by mpet** [comment]
@JuditKnoll thx I will check
