### ISSUE TITLE
Gradle 4.10.1 is unsupported in Gradle Plugin 1.6.10

### ISSUE THREAD

**Issue by vkotovv** [spotbugs/spotbugs#884]
I'm trying to use Spotbugs Gradle plugin in my Android app. Here is the part of my build.gradle:
```groovy
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
        classpath "gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:1.6.10"
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: "com.github.spotbugs"

repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
}
```
It produces the following error on applying Spotbugs plugin while syncing:

> ERROR: Gradle version Gradle 4.10.1 is unsupported. Please use Gradle 5.0 or later.

But it is stated that Gradle v4 is supported [here](https://spotbugs.readthedocs.io/en/latest/gradle.html):

> Note that SpotBugs Gradle Plugin does not support Gradle v3, you need to use v4 or later.

Is Gradle v4 supported? What version of the plugin should I use?

**Comment by KengoTODA** [comment]
Use Gradle 5.0 or later instead. Please check [CHANGELOG](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/1.6.10/CHANGELOG.md#removed) about the reason.

**Comment by KengoTODA** [comment]
I will update official site later.
