### ISSUE TITLE
replace jcip-annotations dependency with newer licensed apache 2 version

### ISSUE THREAD

**Issue by jjYBdx4IL** [spotbugs/spotbugs#887]
no clue how this could end up in maven central:

http://repo1.maven.org/maven2/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.pom

but it has no licensing information and my maven license plugin throws up when collecting dependency license information to generate a 3rd party license file.

The package seems to contain only 4 trivial annotations. Please move them to your project in order to avoid that dependency - copyright for such a triviality shouldn't be an issue.

TY!

**Comment by jtnord** [comment]
jcip annotations have the following copyright:  (https://jcip.net/) 

> This software is copyright (c) 2005 Brian Goetz and Tim Peierls and is released under the Creative Commons Attribution License (http://creativecommons.org/licenses/by/2.5). The official home for this software is http://www.jcip.net. Any republication or derived work distributed in source code form must include the copyright and license notice.

**Comment by hazendaz** [comment]
also in jsr305.  Not seeing point of keeping legacy around.  Plus many different variations https://search.maven.org/search?q=jcip-annotations.  Need to look more but expect to replace it.  Others rebuilt and re-licensed under apache 2.  It would make sense to use one of them and probably one with osgi headers too.

**Comment by hazendaz** [comment]
changed title as why something ended up in sonatype is a different story.  Many, many years ago such requirements did not exist.  So that is why its there that way.  That cannot happen today though.

**Comment by hazendaz** [comment]
Switching to apache 2 version from com.github.stephenc.jcip as used elsewhere.
