### ISSUE TITLE
Unnecessary Dependency Conflict

### ISSUE THREAD

**Issue by jawaff** [spotbugs/spotbugs#888]
Hello,

So my company has a Gradle plugin that forces our dependencies to be of the same version. This is done in order to prevent dependency hell issues.

Ex:
```
configurations.all {
  resolutionStrategy {
    failOnVersionConflict()
  }
}
```

I found that spotbugs has a conflict in its dependency tree and there's no clear reason for it. I've attempted to use a resolution strategy on the spotbugs configuration to force asm-commons to be version 7.0, but that didn't get rid of the conflict for some reason. We decided to just disable Spotbugs and keep using PMD, but I'd really like to use Spotbugs for all of our projects. Can you guys just fix your dependency tree so that there isn't a version conflict? I doubt there's a real reason that the conflict is necessary.

Attempt to Force the asm-commons Version:
```
configurations.all {
  resolutionStrategy {
    force 'org.ow2.asm:asm-commons:7.0'
  }
}
```

Conflicting Dependencies:
```
$ gradle :dependencyInsight --configuration spotbugs --dependency org.ow2.asm:asm-analysis --refresh-dependencies
org.ow2.asm:asm-analysis:7.0
+--- com.github.spotbugs:spotbugs:3.1.11
|    \--- spotbugs
\--- org.ow2.asm:asm-util:7.0
     \--- com.github.spotbugs:spotbugs:3.1.11 (*)

org.ow2.asm:asm-analysis:6.2.1 -> 7.0
\--- org.ow2.asm:asm-commons:6.2.1
     \--- com.github.spotbugs:spotbugs:3.1.11
          \--- spotbugs
```

**Comment by KengoTODA** [comment]
The `com.github.spotbugs:spotbugs:3.1.11` depends on `asm-commons:7.0`.

https://github.com/spotbugs/spotbugs/blob/3.1.11/spotbugs/build.gradle#L60

So I'm not sure what happened in your project. Consider to share mcve project.

**Comment by jawaff** [comment]
Interesting... I'm not sure what happened either. I'll have to look into
that a bit closer. Thanks for the quick response and sorry for the
misunderstanding.

**Comment by hazendaz** [comment]
closing as old and we are well past that version at this point.
