### ISSUE TITLE
Ask to release BCEL 6.1

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#89]
* [x] Send email to [Apache Commons user ML](http://mail-archives.apache.org/mod_mbox/commons-user/) to ask volunteer to push out a release.
    * We need a [release manager](http://www.apache.org/dev/release-publishing.html#release_manager) to release new version
* [ ] Update SpotBugs' dependency to BCEL 6.1
* [ ] Stop releasing shade jar (a jar file which includes BCEL classes)

**Comment by KengoTODA** [comment]
http://mail-archives.apache.org/mod_mbox/commons-user/201612.mbox/browser

**Comment by KengoTODA** [comment]
v6.1 is not released yet.

https://commons.apache.org/proper/commons-bcel/download_bcel.cgi

**Comment by sewe** [comment]
FYI, I just [asked again for a BCEL 6.1 release](http://mail-archives.apache.org/mod_mbox/commons-user/201708.mbox/%3C8d38d79a-7c0b-a109-f828-4408aff5d39f%40codetrails.com%3E) on `user@commons.apache.org`. Maybe the mention of our willingness to fork (#327) drives the point home this time.

**Comment by PascalSchumacher** [comment]
https://mail-archives.apache.org/mod_mbox/commons-dev/201708.mbox/%3C66E59081-4A47-4611-95B6-1DA1F5FDA83E%40apache.org%3E

Hopefully there will be a release soon.

**Comment by PascalSchumacher** [comment]
Release happened yesterday:

https://mail-archives.apache.org/mod_mbox/commons-dev/201709.mbox/%3C081D7D7E-AF65-41BC-8577-2E04234C059A%40apache.org%3E
