### ISSUE TITLE
Performance of SpotBugs is slower than FindBugs when target class has many ancestor classes

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#894]
This issue is reported by @megascus. In his project that has long history, the performance of SpotBugs is 10~20% slower than FindBugs. He can reproduce this at least from the version 3.1.0 RC2 that depends on the BCEL version 6.1-SNAPSHOT.

I've checked thread dump provided by him, and it seems that it takes much time when it searches the target method to analyse ([1](https://github.com/spotbugs/spotbugs/blob/3.1.11/spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/analysis/ClassInfo.java#L331), [2](https://github.com/spotbugs/spotbugs/blob/3.1.11/spotbugs/src/main/java/edu/umd/cs/findbugs/ba/Hierarchy2.java#L286), [3](https://github.com/spotbugs/spotbugs/blob/3.1.11/spotbugs/src/main/java/edu/umd/cs/findbugs/ba/Hierarchy2.java#L271)).

So I guess this problem comes when we have many classes to analyse, that means one class has many ancestor classes, because they do not use interface so much in that project.

### FindBugs 3.0.1  (n=578)

```
166 edu.umd.cs.findbugs.classfile.analysis.ClassInfo.findMethod(ClassInfo.java:331)
 81 edu.umd.cs.findbugs.ba.Hierarchy2.getXClass(Hierarchy2.java:284)
 53 edu.umd.cs.findbugs.ba.Hierarchy2.findMethod(Hierarchy2.java:269)
 33 java.lang.Throwable.fillInStackTrace(java.base@11.0.2/Native
 24 java.util.HashMap.hash(java.base@11.0.2/HashMap.java:339)
 13 java.util.HashMap$HashIterator.nextNode(java.base@11.0.2/HashMap.java:1497)
  8 java.util.HashMap.putVal(java.base@11.0.2/HashMap.java:626)
  7 edu.umd.cs.findbugs.classfile.DescriptorFactory.canonicalizeString(DescriptorFactory.java:78)
  7 edu.umd.cs.findbugs.ba.Frame.<init>(Frame.java:114)
  6 java.util.HashMap.remove(java.base@11.0.2/HashMap.java:794)
  6 java.lang.StringLatin1.replace(java.base@11.0.2/StringLatin1.java:315)
  6 java.lang.StringBuilder.append(java.base@11.0.2/StringBuilder.java:174)
  6 edu.umd.cs.findbugs.ba.Frame.copyFrom(Frame.java:618)

```

### SpotBugs 3.1.11 (n=607)

```
187 edu.umd.cs.findbugs.classfile.analysis.ClassInfo.findMethod(ClassInfo.java:331)
117 edu.umd.cs.findbugs.ba.Hierarchy2.getXClass(Hierarchy2.java:286)
 57 edu.umd.cs.findbugs.ba.Hierarchy2.findMethod(Hierarchy2.java:271)
 18 java.util.HashMap$HashIterator.nextNode(java.base@11.0.2/HashMap.java:1497)
 14 java.util.HashMap.hash(java.base@11.0.2/HashMap.java:339)
 14 java.lang.ThreadLocal$ThreadLocalMap.getEntryAfterMiss(java.base@11.0.2/ThreadLocal.java:464)
 12 java.util.Arrays.hashCode(java.base@11.0.2/Arrays.java:4685)
  8 edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:655)
  6 java.util.HashMap.resize(java.base@11.0.2/HashMap.java:730)
  5 java.util.HashMap.putVal(java.base@11.0.2/HashMap.java:659)
  5 edu.umd.cs.findbugs.ba.Frame.<init>(Frame.java:114)
```

### Reference

* [gclog.zip](https://github.com/spotbugs/spotbugs/files/2924121/gclog.zip)

**Comment by hazendaz** [comment]
closing as old, would need redone but checking against findbugs at this point in time would make no sense regardless of what it did at that point many years ago.  Spotbugs has far more code at this point.  It does far more in general so I don't think any of this data is useful at this point.  not disputing code has issues, I'm sure it certainly does and needs some good housecleaning but just that this data is too old to make a call.
