### ISSUE TITLE
Dead code removal

### ISSUE THREAD

**Issue by jsotuyod** [spotbugs/spotbugs#9]
As per #4, dead code should be removed.

We are so far agreed on removing:

* BlueJ support
* Update Check support
* Cloud plugins
* Non-published artifacts such as:
  - NullPointerBenchmark
  - sandbox

Others may arise.

**Comment by mebigfatguy** [comment]
As requested by Stephen Connolly on the mailing list,

we should also remove the use of JSR305, as (qutoting from him)

"One particular concern I have is the use of the javax.annotation packages for the @Nonnull annotations etc.

Anyone distributing code with a JRE is in breach of the JRE redistribution terms if they have any use of javax.* annotations where those annotations were not released as part of the JSR process."

**Comment by jsotuyod** [comment]
I read that too. I would love to check the license myself to be sure, and if so, I'd gladly add it to the list. He is probably right 'though.

**Comment by henrik242** [comment]
Also, are the `.idea` and `.settings` needed?

**Comment by jsotuyod** [comment]
@henrik242 those have to go too, but only after #4 is solved to allow a proper project import.

**Comment by henrik242** [comment]
@jsotuyod Or #40 , I guess :)

**Comment by jsotuyod** [comment]
I've a working version with update checks / cloud plugin code removed. I'm looking into ways of testing the eclipse plugin to submit a PR.
