### ISSUE TITLE
Difference gradlePlugin vs spotbugs-gradle-plugin

### ISSUE THREAD

**Issue by tabishfayyaz** [spotbugs/spotbugs#908]
I have been trying forever to get your plugin to work on an Android project, the least you can do is to upload a working sample project utilizing latest version of gradle. What is the difference between these two dependencies:
https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/

gradlePlugin vs spotbugs-gradle-plugin

Which one should be used? I have seen your documentation already: https://spotbugs.readthedocs.io/en/latest/gradle.html#generate-spotbugs-tasks-with-android-gradle-plugin it is not helpful at all

**Comment by KengoTODA** [comment]
[spotbugs-gradle-plugin](https://github.com/spotbugs/spotbugs-gradle-plugin) is latest, please use that. You can find the guidance for installation at: https://plugins.gradle.org/plugin/com.github.spotbugs
