### ISSUE TITLE
spotbugs 4 eclipse plugin already published

### ISSUE THREAD

**Issue by Bananeweizen** [spotbugs/spotbugs#914]
If I get it right, spotbugs 4 is only in beta right now. The eclipse plugin however is already published at the normal update site https://spotbugs.github.io/eclipse/, so all existing installations will upgrade, if they are configured for automatic updates.

Just to be clear: I can live with that. Just in case you have breaking changes in confguration files, it's hard to synchronize the eclipse and maven versions then. However, since there is already another issue about more synchronized publishing of integrations, feel free to close this issue, if you feel there are no additional things to do.

**Comment by KengoTODA** [comment]
Ahh, this is my mistake. Current build script cares `_RC` only, it should care `_beta` too.

https://github.com/spotbugs/spotbugs/blob/d56101aa32bdc4dbda2edb26f3f7a3c6955188d0/.travis.yml#L112

For now eclipse plugin contains no breaking change. So I think it's not painful, however, I will fix build script later.
