### ISSUE TITLE
Maven plugin site is down

### ISSUE THREAD

**Issue by cristalp** [spotbugs/spotbugs#922]
In https://spotbugs.readthedocs.io/en/latest/maven.html#goals-of-spotbugs-maven-plugin you link to the Maven plugin's site, but all the links are dead:

https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html
https://spotbugs.github.io/spotbugs-maven-plugin/check-mojo.html
https://spotbugs.github.io/spotbugs-maven-plugin/gui-mojo.html

**Comment by jtnord** [comment]
Duplicate issue has been closed and the links appear to be working for me.  Someone with permissions could likely close this issue.
