### ISSUE TITLE
RuntimeExceptionCapture causes ArrayIndexOutOfBoundsException in addError

### ISSUE THREAD

**Issue by Flugtiger** [spotbugs/spotbugs#943]
When analysing our project we encountered the following error:

> [java] The following errors occurred during analysis:
>      [java]   Exception analyzing ----- using detector edu.umd.cs.findbugs.detect.RuntimeExceptionCapture
>      [java]     java.lang.ArrayIndexOutOfBoundsException: 5
>      [java]       At edu.umd.cs.findbugs.BugCounts.addError(PackageStats.java:51)
>      [java]       At edu.umd.cs.findbugs.PackageStats.addError(PackageStats.java:240)
>      [java]       At edu.umd.cs.findbugs.ProjectStats.addBug(ProjectStats.java:272)
>      [java]       At edu.umd.cs.findbugs.SortedBugCollection.add(SortedBugCollection.java:956)
>      [java]       At edu.umd.cs.findbugs.SortedBugCollection.add(SortedBugCollection.java:224)
>      [java]       At edu.umd.cs.findbugs.BugCollectionBugReporter.doReportBug(BugCollectionBugReporter.java:99)
>      [java]       At edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:177)
>      [java]       At edu.umd.cs.findbugs.DelegatingBugReporter.reportBug(DelegatingBugReporter.java:69)
>      [java]       At edu.umd.cs.findbugs.FilterBugReporter.reportBug(FilterBugReporter.java:49)
>      [java]       At edu.umd.cs.findbugs.FilterBugReporter.reportBug(FilterBugReporter.java:49)
>      [java]       At edu.umd.cs.findbugs.BugAccumulator.reportBug(BugAccumulator.java:200)
>      [java]       At edu.umd.cs.findbugs.BugAccumulator.reportAccumulatedBugs(BugAccumulator.java:181)
>      [java]       At edu.umd.cs.findbugs.detect.RuntimeExceptionCapture.visitJavaClass(RuntimeExceptionCapture.java:119)
>      [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
>      [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
>      [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
>      [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
>      [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
>      [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
>      [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)

**Comment by yann9** [comment]
same issue with relaxed mode on SpotBugs 4.0.0

**Comment by Koziolek** [comment]
Probably bug is [here](https://github.com/spotbugs/spotbugs/blob/b1c2a5ecebe33328b3c5fb951641ef658ec82b3a/spotbugs/src/main/java/edu/umd/cs/findbugs/PackageStats.java#L50)
Bug priority is bigger than maximum array size.

**Comment by hazendaz** [comment]
Seems more widespread of a problem.  Seeing this with some very simple groovy code [here](https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/main/groovy/sample/mybatis/groovy/domain/City.groovy).  The build has site disabled to skip the report at the moment.  I think spotbugs needs to protect better from this as issue for me is UnreadFields detector.

**Comment by gtoison** [comment]
This should be fixed by #3000
