### ISSUE TITLE
Cannot generate HTML because of TransformerConfigurationException

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#944]
### Problem

SpotBugs 4.0.0-beta1 cannot generate HTML report with `fancy-hist.xsl` due to internal exception. This is caused by #881.

* CI build reproducing this problem: https://travis-ci.org/spotbugs/spotbugs-gradle-plugin/jobs/531604063
* Necessary change to reproduce this problem in local: https://github.com/spotbugs/spotbugs-gradle-plugin/commit/af0b7c9175c393cec60bece77fb4899852474bca
    * Simply run `./gradlew test` to reproduce

### Exception

```
14:11:07.695 [ERROR] [system.err] ERROR:  'Syntax error in '(/BugCollection/Project/@projectName, /BugCollection/Project/@filename)[1]'.'
14:11:07.695 [ERROR] [system.err] FATAL ERROR:  'Syntax error in '(@priority_4, 0)[1]'.'
14:11:07.700 [ERROR] [system.err] The following errors occurred during analysis:
14:11:07.700 [ERROR] [system.err]   Could not generate HTML output
14:11:07.707 [ERROR] [system.err]     javax.xml.transform.TransformerConfigurationException: Syntax error in '(@priority_4, 0)[1]'.
14:11:07.708 [ERROR] [system.err]       At com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1020)
14:11:07.708 [ERROR] [system.err]       At com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:791)
14:11:07.708 [ERROR] [system.err]       At edu.umd.cs.findbugs.HTMLBugReporter.finish(HTMLBugReporter.java:64)
14:11:07.708 [ERROR] [system.err]       At edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
14:11:07.708 [ERROR] [system.err]       At edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
14:11:07.709 [ERROR] [system.err]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1126)
14:11:07.709 [ERROR] [system.err]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
14:11:07.710 [ERROR] [system.err]       At com.github.spotbugs.internal.spotbugs.SpotBugsExecutor.runSpotbugs(SpotBugsExecutor.java:23)
14:11:07.710 [ERROR] [system.err]       At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:11:07.713 [ERROR] [system.err]       At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:11:07.714 [ERROR] [system.err]       At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:11:07.714 [ERROR] [system.err]       At java.lang.reflect.Method.invoke(Method.java:498)
14:11:07.714 [ERROR] [system.err]       At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:110)
14:11:07.715 [ERROR] [system.err]       At org.gradle.process.internal.worker.request.WorkerAction.runThenStop(WorkerAction.java:93)
14:11:07.715 [ERROR] [system.err]       At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:11:07.715 [ERROR] [system.err]       At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:11:07.715 [ERROR] [system.err]       At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:11:07.718 [ERROR] [system.err]       At java.lang.reflect.Method.invoke(Method.java:498)
14:11:07.718 [ERROR] [system.err]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
14:11:07.718 [ERROR] [system.err]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
14:11:07.718 [ERROR] [system.err]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
14:11:07.718 [ERROR] [system.err]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
14:11:07.718 [ERROR] [system.err]       At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
14:11:07.718 [ERROR] [system.err]       At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
14:11:07.719 [ERROR] [system.err]       At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
14:11:07.719 [ERROR] [system.err]       At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
14:11:07.719 [ERROR] [system.err]       At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
14:11:07.719 [ERROR] [system.err]       At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
14:11:07.719 [ERROR] [system.err]       At java.lang.Thread.run(Thread.java:745)
```

**Comment by KengoTODA** [comment]
@Vampire could you check this issue in your spare time? Thanks in advance :)

**Comment by Vampire** [comment]
According to the exception Xalan-J is used as XSLT engine. Xalan-J is an XSL 1 transformer. The stylesheet is XSL 2 though and should be transformed with Saxon.

**Comment by KengoTODA** [comment]
Wmm in my local I got `Provider net.sf.saxon.TransformerFactoryImpl not found` when I set `"javax.xml.transform.TransformerFactory"` property. I will continue investigation.

**Comment by Vampire** [comment]
I wouldn't use the property as you control the transforming code, but set it when requesting the new transformer.

**Comment by Vampire** [comment]
If you expect Saxon to be used but Xalan-J is used, this is most often an issue with non-exact code and classpath ordering.
If you just do `TransformerFactory.newInstance()` you tell Java to give you any available transformer.
Now if you test successfully with Saxon in the classpath and later add Xalan-J (e. g. by a transitive dependency or because your lib / plugin is used with some other lib / pluing that requires it) and it comes first in the classpath, you suddenly get Xalan-J as transformer.
So it is generally a good idea to be explicit and use `TransformerFactory.newInstance('net.sf.saxon.TransformerFactoryImpl')` or `TransformerFactory.newInstance('net.sf.saxon.TransformerFactoryImpl', getClass().classLoader)` to specify explicitly which transformer factory you want.
Setting the property will in turn influence also all other transformer usages that might actually need Xalan-J to work properly why it is usually a bad idea to set the property.

**Comment by Vampire** [comment]
That it doesn't find the factory for you sounds strange, as far as I remember, Spotbugs has it as dependency.

**Comment by KengoTODA** [comment]
> Spotbugs has it as dependency

I cannot find Saxon in [the SpotBugs' compile dependency](https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs/4.0.0-beta1), could you confirm? 

It seems that we can solve this issue by adding dependency explicitly: https://github.com/spotbugs/spotbugs-gradle-plugin/commit/a6eb05dea1c560222e916c0967b67ee4eb30de11

**Comment by KengoTODA** [comment]
If this problem comes from spotbugs' side (not spotbugs-gradle-plugin), I think it's better to fix in this spotbugs and release `4.0.0-beta2` for users.

**Comment by Vampire** [comment]
Oh, strange, I thought I had seen it in the dependencies.
Maybe I just assumed it is a dependencies as the XSL stylesheets are version 2.
If Saxon actually is not a dependency, it should be added to spotbugs itself, not the Gradle plugin, as using the fancy stylesheet with spotbugs standalone will probably also fail.
It probably worked before as Xalan-J is lenient about the version and there were no actual XSLT 2 features used before my rework of the stylesheet.
But declaring the stylesheets as version 2 and then using an XSLT 1 processor to process them is bad anyway, also because it is not fully backwards compatible.

**Comment by Vampire** [comment]
Yeah, it seems in commit 1d3e8940480d47911e5509000e4e8e5d96341c74 only the versions were increased without actually using an XSLT 2 processor like Saxon-HE.

**Comment by KengoTODA** [comment]
Created a PR #945 to fix this issue.
