### ISSUE TITLE
Feature request: detect NPE in method reference

### ISSUE THREAD

**Issue by perlun** [spotbugs/spotbugs#946]
Thanks for a great project. :+1: 

It would be incredibly nice if Spotbugs could detect invalid constructs like the one below:

![image](https://user-images.githubusercontent.com/630613/57763464-12c83600-770a-11e9-9f28-6b411dc33ef7.png)

The `clientServiceCacheLoader::getSubscriberById` method is defined to be `@Nullable` here, and the relevant parts of `SupplierWithFallback` follows:

```java
class SupplierWithFallback<TRequest, TReply> {

    private final NullablePredicate<TReply> replyValidator;

    SupplierWithFallback( NullableFunction<TRequest, TReply> primaryFunction, NonNullFunction<TRequest, TReply> secondaryFunction, NullablePredicate<TReply> replyValidator ) {
        this.primaryFunction = primaryFunction;
        this.secondaryFunction = checkNotNull( secondaryFunction, "secondaryFunction cannot be null" );
        this.replyValidator = checkNotNull( replyValidator, "replyValidator cannot be null" );
    }

    public TReply apply( TRequest request ) throws ServerException {
        TReply reply = primaryFunction.apply( request );

        if ( replyValidator == null || replyValidator.test( reply ) ) {
            return checkNotNull( reply, "reply cannot be null" );
        }

        // ...
    }
```

`NullablePredicate` is defined thusly, i.e. explicitly marking the `t` parameter to be nullable - which enables IntelliJ to draw the (correct) conclusion in this case, that this usage is dodgy and might throw exceptions at runtime.

```java
public interface NullablePredicate<T> {

    /**
     * Evaluates this predicate on the given argument.
     *
     * @param t the input argument
     * @return {@code true} if the input argument matches the predicate,
     * otherwise {@code false}
     */
    boolean test( @Nullable T t );
}
```

I have tested enabling all Spotbugs visitors (which we do not normally use, because it increases build times and also interferes with some of our existing code) and from what I can tell, the above construct is not properly detected by Spotbugs at the moment. We are using version 3.1.12.

Any suggestions? Or is this just not implemented at the moment?

**Comment by ThrawnCA** [comment]
The `Nullable` annotation does not mean what you think it means in SpotBugs. It has the same effect as no annotation at all. You probably want `CheckForNull` instead. Incidentally, which package are you getting it from?

**Comment by hazendaz** [comment]
closing as old and never got a response back, question seemed answered otherwise.
