### ISSUE TITLE
ExecutorService.submit and similar in RV_RETURN_VALUE_IGNORED_BAD_PRACTICE

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs#948]
`RV_RETURN_VALUE_IGNORED_BAD_PRACTICE` complains about this:

```java
protected void executeAsync(Runnable commandExecutor) {
    getExecutorService().submit(() -> {
        try {
            commandExecutor.run();
        } catch (Throwable t) {
            logger.error("Exception while executing command asynchronously", t);
        }
    });
}
```

Why should this be bad practice?
Besides that catching `Throwable` per-se is bad practice, here it is done to at least log `Error`s that happen as they  are otherwise just swallowed.
So the future can never complete with error, as all throwables are caught.

Also, what would be the recommended non-bad practice alternative?
Always calling `get()` on the returned future?
That would block the current thread and thus go against the intention of the future.

One could actually wrap the `Future` in a `CompletableFuture` and do the exception handling there like

```java
protected void executeAsync(Runnable commandExecutor) {
    CompletableFuture.runAsync(commandExecutor, getExecutorService())
            .exceptionally(throwable -> {
                logger.error("Exception while executing command asynchronously", throwable);
                return null;
            });
}
```

But is this really that much cleaner?
It is actually the exact same behaviour.

**Comment by ThrawnCA** [comment]
Which return value does SpotBugs say you're ignoring?

**Comment by Vampire** [comment]
> Which return value does SpotBugs say you're ignoring? Is it the `Future` returned by the executor service?

Yes, the `Future`.

> Without capturing that, you don't have any idea when your command has finished. Which, OK, maybe you don't care about, but often it's pretty important. If you're sure it's not important to you, feel free to exclude the rule in this case, but in general, I think this is a code structure that SpotBugs _should_ warn you about.

But then again, what would Spotbugs suggest to use? If it says "this is bad practice" it should also say "do that instead".
Calling `get()` directly on the `Future`?
That would be a pretty bad recommendation.
It would totally contradict the sense of a future.

Knowing when a future completed often is not interesting at all.
Whe more often would probably be interesting is whether it completed successfully or not.
But that I tested already inside the lambda, so therefor the `get()` also is not necessary.

If you think Spotbugs should really warn about the construct, fine, but then please provide a good recommendation for a better practice.

**Comment by ThrawnCA** [comment]
> Calling get() directly on the Future?
That would be a pretty bad recommendation.
It would totally contradict the sense of a future.

Not necessarily. There are other methods that could be called, eg `isDone`. Moreover, it's not unreasonable to trigger a job, do a bunch of other work, then block and wait for the job to complete.

Ultimately, if you don't care about the returned `Future`, then why are you calling `submit` instead of `execute`?

**Comment by Vampire** [comment]
> Not necessarily. There are other methods that could be called, eg `isDone`. Moreover, it's not unreasonable to trigger a job, do a bunch of other work, then block and wait for the job to complete.

But it's also not unreasonable to not wait, but ... see below
 
> Ultimately, if you don't care about the returned `Future`, then why are you calling `submit` instead of `execute`?

Because I somehow overlooked it totally.
You are right, if you don't want to check the future, `execute` is more appropriate.
In my code I now anyway switched to `CompletableFuture.runAsync`, then I can also do proper error handling without triggering the rule to not catch `Exception` and to have a bit cleaner code. :-D
