### ISSUE TITLE
android annotation support?

### ISSUE THREAD

**Issue by GeekMin** [spotbugs/spotbugs#96]
As I know: 
Findbugs has added support for these annotations:
@com.google.common.base.Nullable
@org.jetbrains.annotations.Nullable
@org.jetbrains.annotations.NotNull
@org.eclipse.jdt.annotation.Nullable
@org.eclipse.jdt.annotation.NonNull
@org.eclipse.jdt.annotation.NonNullByDefault
+
JSR305

but  android-related:
android.support.annotation.NonNull;
android.support.annotation.Nullable;

is not supported-yet?

If I want to add support for android annotation, how can I do?

**Comment by jsotuyod** [comment]
Android support is in our backlog, but we will probably not address it for 3.1.0. However, you are free to submit a PR. Fortunately for you, doing so shouldbe relatively easy. You could check this PR originally submitted for Findbugs (never merged) https://github.com/findbugsproject/findbugs/pull/117

With that in place, you can write a proper integration test using our new testing framework. You can check how to write [a sample class to be analyzed](https://github.com/spotbugs/spotbugs/blob/master/findbugsTestCases/src/java/lambdas/Issue20.java) and then [write an integration test](https://github.com/spotbugs/spotbugs/blob/master/findbugs/src/test/java/edu/umd/cs/findbugs/integration/FindNullDerefIntegrationTest.java)

With that you can submit a PR and we will gladly look into it and merge it.
