### ISSUE TITLE
Undetected or false positive DM_DEFAULT_ENCODING

### ISSUE THREAD

**Issue by Jojor** [spotbugs/spotbugs#985]
With the following code : 

```
 try (FileWriter output = new FileWriter("./foo.txt")) {}
```

Spotbug yells `[ERROR] Found reliance on default encoding in test.SpotbugsIssue.main(String[]): new java.io.FileWriter(String) [test.SpotbugsIssue] At SpotbugsIssue.java:[line 12] DM_DEFAULT_ENCODING`

The FileWriter constructor [documentation says](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/FileWriter.html#%3Cinit%3E(java.io.File)) that it uses the `Charset#defaultCharset()`

```
public FileWriter​(File file)
           throws IOException
Constructs a FileWriter given the File to write, using the platform's default charset
```

So it's the same as writing 
```
try (FileWriter output = new FileWriter("./foo.txt", Charset.defaultCharset())) {}
```

However, in the latter case, spotbugs doesn't detect the DM_DEFAULT_ENCODING.

It seems to be either a false positive in the first case or an undetected issue in the second case.

**Comment by ThrawnCA** [comment]
If you explicitly pass the default charset, then presumably you have some reason for doing so, rather than just defaulting to the simpler API method. I think that the current behavior is fine.

Incidentally, in most cases I'd suggest using `StandardCharsets.UTF_8` instead of defaultCharset.

**Comment by Jojor** [comment]
Ok I understand, thanks for the clarification and the advice.
I'm closing it.
