### ISSUE TITLE
how generated xdoc maven.

### ISSUE THREAD

**Issue by andreluizf** [spotbugs/spotbugs#991]
Hi, I looked at all the documentation and I'm not able to generate the report xdoc by the maven plugin.

Has anyone done this?

I need to generate xdoc because logstash does not recognize the legacy xml.

**Comment by hazendaz** [comment]
closing as against wrong repo.  haven't heard of such issue reported over at the maven plugin I primarily deal with but this is pretty old.  If an issue still, please go search through maven plugin for help there.
